Pbc/tax management
spryker/spryker-docs pull request #1068
Opened 2022-07-07 13:10 UTC by andriitserkovnyi

## PR Description

Tax management PBC + includes

## Checklist
- [x] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2022-07-13 13:27 UTC, VadymSachenko approved these changes

2022-07-13 14:28 UTC, jeremyfourna requested changes
There are too many file changes in this PR to make a good review. Please roll back most of your change in the PBC area because the master already has a better structure around PSP and ratings and Reviews, same for ACP, where we moved the files around.
Ideally we should make multiple PR out of this ones.
1. Put all guides in the includes part PR
2. Tax PBC PR

2022-07-13 14:28 UTC, jeremyfourna commented on _data/sidebars/scos_dev_sidebar.yml
>        - title: 'Reference information: Tax module'
All those tax pages in the dev section must also be moved to the PBC area

2022-07-13 14:28 UTC, jeremyfourna commented on _data/sidebars/scos_user_sidebar.yml
>          - title: Managing tax rates
Why is this part not removed?

2022-07-13 14:28 UTC, jeremyfourna commented on _data/sidebars/scos_user_sidebar.yml
>          - title: Managing tax sets
Why is this part not removed?

2022-07-13 14:28 UTC, jeremyfourna commented on _data/sidebars/scos_user_sidebar.yml
>      - title: Taxes
Why is this part not removed?

2022-07-13 14:28 UTC, jeremyfourna commented on _data/sidebars/scos_user_sidebar.yml
>        - title: Avalara
Why is this part not removed?

2022-07-13 14:28 UTC, jeremyfourna commented on _includes/pbc/all/data-import-and-export/file-details-product-abstract.csv.md
> +| avalara_tax_code |  | String | | [Avalara tax code](/docs/pbc/all/tax-management/tax-feature-overview.html#avalara-system-for-automated-tax-compliance) for automated tax calculation. |
We should only mention this part in the Avalara doc, not in the PIM default CSV import

2022-07-13 14:28 UTC, jeremyfourna commented on docs/acp/user/apps/bazaarvoice.md
> +---
This file must be located in the PBC area, you can remove it

2022-07-13 14:28 UTC, jeremyfourna commented on docs/acp/user/apps/payone.md
>  template: howto-guide-template
This file must be located in the PBC area, you can remove it

2022-07-13 14:28 UTC, jeremyfourna commented on docs/acp/user/apps/usercentrics.md
> +---
This file must be located in the PBC area, you can remove it

2022-07-13 14:28 UTC, jeremyfourna commented on docs/pbc/all/payment-service-providers/psp.md
> ----
Please rollback the file

2022-07-13 14:28 UTC, jeremyfourna commented on docs/pbc/all/payment-service-providers/unzer/unzer.md
> ----
Please rollback the file

2022-07-13 14:28 UTC, jeremyfourna commented on css/components/_sidebar-nav.scss
> +            font-weight: normal;
You can rollback the change

2022-07-13 14:28 UTC, jeremyfourna commented on _layouts/home.html
> +                            <li><a href="/docs/pbc/all/pbc-landing.html">PBC guides</a></li>
You can rollback the change

2022-07-15 12:47 UTC, andriitserkovnyi commented on _data/sidebars/pbc_all_sidebar.yml
> +        url: /docs/pbc/all/tax-management/tax-feature-overview.html
Then, do you want to rewrite all feature overviews as capability overviews so we can use them as landing pages?

2022-07-15 12:52 UTC, andriitserkovnyi commented on _data/sidebars/pbc_all_sidebar.yml
> +              - title: Create tax sets
same

2022-07-15 13:03 UTC, andriitserkovnyi commented on _data/sidebars/pbc_all_sidebar.yml
> +          - title: Manage via Glue API
Not sure what you mean

2022-08-04 06:52 UTC, andriitserkovnyi commented
Split this PR

2022-08-04 06:52 UTC, closed without merging