СС-18569 Migration guide - Switch from Yarn to NPM v8
spryker/spryker-docs pull request #1113
Opened 2022-07-19 16:58 UTC by danilmoro3

Ticket: https://spryker.atlassian.net/browse/CC-18569

2022-07-20 12:38 UTC, FRITS-Kh requested changes

2022-07-20 12:38 UTC, FRITS-Kh commented on docs/scos/dev/front-end-development/migration-guide-switch-to-npm.md
> +```
I think we shouldn't provide commands for updating other tools.
Please add links to the appropriate docs.

2022-07-20 12:38 UTC, FRITS-Kh commented on docs/scos/dev/front-end-development/migration-guide-switch-to-npm.md
> +In this article, you will find instructions on how to upgrade NPM to version 8 in your Spryker project.
```suggestion
This article provides instructions for migrating from YARN to NPM version 8 in your Spryker project.
```

2022-07-20 12:38 UTC, FRITS-Kh commented on docs/scos/dev/front-end-development/migration-guide-switch-to-npm.md
> +We've been using Yarn v2 since the beginning of Merchant Portal project to install dependencies in a workspace.
```suggestion
Yarn v2 has been used since the beginning of the Merchant Portal project to install dependencies in a workspace.
```

2022-07-20 15:33 UTC, FRITS-Kh submitted a review, later dismissed

2022-07-22 08:11 UTC, FRITS-Kh submitted a review, later dismissed

2022-07-25 10:03 UTC, gibmirmilch approved these changes

2022-07-25 10:03 UTC, merged