BO-2260: Added IG for merchant portal forgot password functionality.
spryker/spryker-docs pull request #112
Opened 2021-06-24 08:43 UTC by sakharova-yuliia

## PR Description

TBD

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2021-12-13 10:08 UTC, asmarovydlo requested changes

2021-12-13 10:08 UTC, asmarovydlo commented on docs/marketplace/dev/feature-integration-guides/202106.0/merchant-portal-core-feature-integration.md
>  Open access to the Merchant Portal login page by default:
Should be part of `Set up Configuration` section
https://spryker.atlassian.net/wiki/spaces/DOCS/pages/478118714/Feature+integration+guides

2021-12-13 10:08 UTC, asmarovydlo commented on docs/marketplace/dev/feature-integration-guides/202106.0/merchant-portal-core-feature-integration.md
> +### 4) Set up transfer objects
Sections go in the wrong order, please see https://spryker.atlassian.net/wiki/spaces/DOCS/pages/478118714/Feature+integration+guides for the correct one, and re-arrange.

2021-12-13 10:08 UTC, asmarovydlo commented on docs/marketplace/dev/feature-integration-guides/202106.0/merchant-portal-core-feature-integration.md
> +            ->add(new MerchantUserPasswordResetMailTypePlugin());
Wrong indentation

2021-12-13 10:08 UTC, asmarovydlo commented on docs/marketplace/dev/feature-integration-guides/202106.0/merchant-portal-core-cms-feature-integration.md
> +### 2) Create CMS blocks
Should be the part of `Data Import` section,  please re-arrange according to https://spryker.atlassian.net/wiki/spaces/DOCS/pages/478118714/Feature+integration+guides

2021-12-20 12:36 UTC, asmarovydlo commented on docs/marketplace/dev/feature-integration-guides/202108.0/merchant-portal-core-cms-feature-integration.md
> +Make sure that the following data has been added ti the database
The sentence is not complete.

2022-01-19 10:13 UTC, asmarovydlo requested changes
Changes for `marketplace-merchant-portal-core-feature-integration.md` that previously was part of the PR disappeared, you can find them by clicking on any comment added to the file. (e.g. https://github.com/spryker/spryker-docs/pull/112/files/6690187e68912a5a5ae0d25f2c7c8f601d03bb0b#diff-72315b4688facf268d0d1c50127d0dd2d326509668972065606383235cfec84c)

Please get them back

2025-01-04 10:47 UTC, andriitserkovnyi commented on _includes/pbc/all/install-features/202410.0/marketplace/install-merchant-portal-core-cms-feature.md
> +| Marketplace Merchant Portal Core | {{page.version}} | [Marketplace Merchant Portal Core](/docs/marketplace/dev/feature-integration-guides/{{ page.version }}/merchant-portal-core-feature-integration
Add correct doc names and links

2025-01-04 10:50 UTC, andriitserkovnyi commented on _includes/pbc/all/install-features/202410.0/marketplace/install-merchant-portal-core-cms-feature.md
> +```
Something is missing here

2025-01-04 11:29 UTC, andriitserkovnyi commented on _includes/pbc/all/install-features/202410.0/marketplace/install-merchant-portal-core-cms-feature.md
> +* `spy_cms_block_store`
This is not clear. I assume the database tables should be updated?

2025-01-04 11:32 UTC, andriitserkovnyi commented on _includes/pbc/all/install-features/202410.0/marketplace/install-the-marketplace-merchant-portal-core-feature.md
> +| MerchantUserPasswordResetMailTypePlugin | Builds the mail of merchant password restore type. |  | Spryker\Zed\MerchantUserPasswordResetMail\Communication\Plugin\Mail  |
Does it create an email?

2025-01-04 11:37 UTC, andriitserkovnyi commented on _includes/pbc/all/install-features/202410.0/marketplace/install-merchant-portal-core-cms-feature.md
> +title: Marketplace Merchant Portal Core feature + CMS integration
1. Move the doc to incudes
2. Update the name
3. Update the filename

2025-01-06 15:08 UTC, asmarovydlo commented on _includes/pbc/all/install-features/202410.0/marketplace/install-the-marketplace-merchant-portal-core-feature.md
> +| MerchantUserPasswordResetMailTypePlugin | Builds the mail of merchant password restore type. |  | Spryker\Zed\MerchantUserPasswordResetMail\Communication\Plugin\Mail  |
It creates a transfer that is further used to create email. Rephrased a bit.

2025-01-21 04:24 UTC, merged