СС-18569 Docs update - Switch from Yarn to NPM v8
spryker/spryker-docs pull request #1121
Opened 2022-07-21 13:40 UTC by danilmoro3

Ticket: https://spryker.atlassian.net/browse/CC-18568

2022-07-22 08:51 UTC, FRITS-Kh requested changes

2022-07-22 08:51 UTC, FRITS-Kh commented on docs/cloud/dev/spryker-cloud-commerce-os/configuring-deployment-pipelines/upcoming-release/configuring-github-actions.md
> +                  node-version: '12'
```suggestion
                  node-version: '16'
```

2022-07-22 08:51 UTC, FRITS-Kh commented on docs/cloud/dev/spryker-cloud-commerce-os/configuring-deployment-pipelines/upcoming-release/configuring-github-actions.md
> +                  sudo npm install -g --unsafe-perm speccy@0.11.0
```suggestion
                  sudo npm install --location=global --unsafe-perm speccy@0.11.0
```

2022-07-22 08:51 UTC, FRITS-Kh commented on docs/marketplace/dev/feature-integration-guides/upcoming-release/marketplace-merchant-portal-core-feature-integration.md
> +npm i -g @angular/cli@12.2.16
```suggestion
npm i --location=global @angular/cli@12.2.16
```

2022-07-22 09:46 UTC, FRITS-Kh approved these changes

2022-07-22 09:48 UTC, danilmoro3 commented
Do not merge until the release 
`upcoming-release` folder should be renamed

2022-07-29 11:00 UTC, gibmirmilch submitted a review, later dismissed

2022-09-01 09:26 UTC, VadymSachenko approved these changes

2022-09-01 09:26 UTC, merged