CC-16934 Glue support for Unzer IG.
spryker/spryker-docs pull request #1167
Opened 2022-08-09 15:43 UTC by romanhavrylko

## PR Description

- Epic: https://spryker.atlassian.net/browse/CC-16934

- Ticket for IG: https://spryker.atlassian.net/browse/CC-16965

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2022-08-10 11:25 UTC, kkicheglovspryker submitted a review, later dismissed

2022-08-10 12:19 UTC, DmitryLymarenko commented on docs/pbc/all/payment-service-providers/unzer/install-unzer/integrate-unzer-glue.md
> +**src/Pyz/Glue/CheckoutRestApi/CheckoutRestApiConfig.php**
file looks wrong

2022-08-10 12:23 UTC, DmitryLymarenko commented on docs/pbc/all/payment-service-providers/unzer/install-unzer/integrate-unzer-glue.md
> +**Request:**
```suggestion
**Request Example:**
```

2022-08-10 12:23 UTC, DmitryLymarenko commented on docs/pbc/all/payment-service-providers/unzer/install-unzer/integrate-unzer-glue.md
> +**Response:**
```suggestion
**Response Example:**
```

2022-08-10 12:23 UTC, DmitryLymarenko commented on docs/pbc/all/payment-service-providers/unzer/install-unzer/integrate-unzer-glue.md
> +**Request:**
same here and below

2022-08-10 13:24 UTC, DmitryLymarenko approved these changes

2022-08-11 08:22 UTC, AdvaBD submitted a review, later dismissed

2022-08-11 09:16 UTC, VadymSachenko requested changes

2022-08-11 09:16 UTC, VadymSachenko commented on docs/pbc/all/payment-service-providers/unzer/install-unzer/integrate-unzer-glue.md
> +Take care that requests body differs for each Unzer payment method.
```suggestion
Ensure that the request body differs for each Unzer payment method.
```

2022-08-11 09:16 UTC, VadymSachenko commented on docs/pbc/all/payment-service-providers/unzer/install-unzer/integrate-unzer-glue.md
> +- Property `paymentMethodName` of `payments` has to be replaced by the used method—for example, `Unzer Sofort` or `Unzer Credit Card`.
```suggestion
- Property `paymentMethodName` of `payments` must be replaced by the used method—for example, `Unzer Sofort` or `Unzer Credit Card`. 
```

2022-08-11 09:16 UTC, VadymSachenko commented on docs/pbc/all/payment-service-providers/unzer/install-unzer/integrate-unzer-glue.md
> +**Response Example:**
```suggestion
<details><summary markdown='span'>Response example:</summary>
```

2022-08-11 09:16 UTC, VadymSachenko commented on docs/pbc/all/payment-service-providers/unzer/install-unzer/integrate-unzer-glue.md
> +
```suggestion

</details>

```

2022-08-11 09:16 UTC, VadymSachenko commented on docs/pbc/all/payment-service-providers/unzer/install-unzer/integrate-unzer-glue.md
> +Take care that requests body differs for each Unzer payment method.
```suggestion
Ensure that the request body differs for each Unzer payment method:
```

2022-08-11 09:16 UTC, VadymSachenko commented on docs/pbc/all/payment-service-providers/unzer/install-unzer/integrate-unzer-glue.md
> +- Property `paymentMethodName` of `payments` has to be replaced by used method (e.g. `Unzer Sofort`, `Unzer Credit Card`, etc.).
```suggestion
- Property `paymentMethodName` of `payments` must be replaced by the used method—for example, `Unzer Sofort` or `Unzer Credit Card`.
```

2022-08-11 09:16 UTC, VadymSachenko commented on docs/pbc/all/payment-service-providers/unzer/install-unzer/integrate-unzer-glue.md
> +- Property `paymentResource` of `payments` is not required for `Unzer Sofort`, `Unzer Marketplace Sofort`, `Unzer Bank Transfer`.
```suggestion
- Property `paymentResource` of `payments` is not required for `Unzer Sofort`, `Unzer Marketplace Sofort`, and  `Unzer Bank Transfer`.
```

2022-08-11 09:16 UTC, VadymSachenko commented on docs/pbc/all/payment-service-providers/unzer/install-unzer/integrate-unzer-glue.md
> +- Property `paymentResource` of `payments` is not required for `Unzer Sofort`, `Unzer Marketplace Sofort`, `Unzer Bank Transfer`.
```suggestion
- Property `paymentResource` of `payments` is not required for `Unzer Sofort`, `Unzer Marketplace Sofort`, and  `Unzer Bank Transfer`.
```

2022-08-11 09:16 UTC, VadymSachenko commented on docs/pbc/all/payment-service-providers/unzer/install-unzer/integrate-unzer-glue.md
> +- Property `paymentSelection` of `payments` has to be replaced by used method (e.g. `unzerSofort`, `unzerCreditCard`, `unzerMarketplaceCreditCard`, etc.).
```suggestion
- Property `paymentSelection` of `payments` has to be replaced by used method—for example, `unzerSofort`, `unzerCreditCard`, or `unzerMarketplaceCreditCard`.
```

2022-08-11 09:25 UTC, VadymSachenko commented on docs/pbc/all/payment-service-providers/unzer/install-unzer/integrate-unzer-glue.md
> +
Add an introductory sentence explaining what we verify—for example, "Verify that the following API requests work:"

2022-08-11 09:28 UTC, VadymSachenko commented on docs/pbc/all/payment-service-providers/unzer/install-unzer/integrate-unzer-glue.md
> +{% info_block infoBox %}
If the steps listed in this infoBox are mandatory, then replace `{% info_block infoBox %}` with  `{% info_block warningBox %}`

2022-08-11 09:28 UTC, VadymSachenko commented on docs/pbc/all/payment-service-providers/unzer/install-unzer/integrate-unzer-glue.md
> +{% info_block infoBox %}
If the steps listed in this infoBox are mandatory, then replace `{% info_block infoBox %}` with  `{% info_block warningBox %}`

2022-08-11 10:10 UTC, VadymSachenko commented on docs/pbc/all/payment-service-providers/unzer/install-unzer/integrate-unzer-glue.md
> +Follow the steps below to install the Glue for Unzer.
I think this sentence is even better.
```suggestion
Follow the steps below to install the Unzer Glue API feature core.
```

2022-08-11 11:54 UTC, VadymSachenko approved these changes

2022-08-11 11:54 UTC, merged