SUPESC-621 Updated Unzer IG.
spryker/spryker-docs pull request #1169
Opened 2022-08-11 14:17 UTC by romanhavrylko

## PR Description

Ticket: https://spryker.atlassian.net/browse/SUPESC-621

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2022-08-11 15:10 UTC, kkicheglovspryker submitted a review, later dismissed

2022-08-12 09:19 UTC, DmitryLymarenko commented on docs/pbc/all/payment-service-providers/unzer/install-unzer/integrate-unzer.md
> +```yaml
not a yaml

2022-08-12 09:21 UTC, DmitryLymarenko commented on docs/pbc/all/payment-service-providers/unzer/install-unzer/integrate-unzer.md
> +| UnzerRouteProviderPlugin | Adds Unzer module routes to RouteCollection. | None          | SprykerEco\Yves\Unzer\Plugin\Router\UnzerRouteProviderPlugin |
namespace is wrong

2022-08-12 09:24 UTC, DmitryLymarenko commented on docs/pbc/all/payment-service-providers/unzer/install-unzer/integrate-unzer.md
> +| UnzerCredentialsCartOperationPostSavePlugin | Expands `QuoteTransfer` with `UnzerCredentialsTransfer` according to added items.
please fix data at `namespace` column
namespaces are wrong

2022-08-12 09:28 UTC, DmitryLymarenko commented on docs/pbc/all/payment-service-providers/unzer/install-unzer/integrate-unzer.md
>  <summary markdown='span'>src/Pyz/Zed/UnzerGui/UnzerGuiDependencyProvider.php</summary>
please check this block
path and namespace do not match each other
class definition is missing

2022-08-12 10:19 UTC, DmitryLymarenko approved these changes

2022-08-12 14:51 UTC, AdvaBD reviewed
Optional: if the main seller is a merchant, select MERCHANT REFERENCE. > if the operator is a merchant, select MERCHANT REFERENCE.

2022-08-12 14:54 UTC, AdvaBD requested changes

2022-08-12 14:54 UTC, AdvaBD commented on docs/pbc/all/payment-service-providers/unzer/install-unzer/integrate-unzer.md
> +This document describes how to integrate the [Unzer](/docs/pbc/all/payment-service-providers/unzer/unzer.html) into a Spryker project.
This document describes how to integrate Unzer > delete the

2022-08-12 15:05 UTC, AdvaBD approved these changes

2022-08-16 08:16 UTC, lenadoc approved these changes

2022-08-16 08:16 UTC, merged