[WIP] Merchant Portal > Products
spryker/spryker-docs pull request #120
Opened 2021-06-29 15:09 UTC by gibmirmilch

## PR Description

TBD

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2021-08-20 17:11 UTC, AdvaBD requested changes
can we arrange the topic of manage abstract products based on the order they are displayed in the drawer
all comments regarding abstract attributes images prices etc are relevant for the concrete product as well

2021-08-20 17:11 UTC, AdvaBD commented on docs/marketplace/user/merchant-portal-user-guides/202108.0/products/concrete-products/creating-marketplace-concrete-product.md
> +By selecting **Autogenerate SKU**s, the SKU numbers for the concrete products are generated automatically, based on the SKU of their abstract product.
SKU prefix

2021-08-30 10:39 UTC, gibmirmilch commented on docs/marketplace/user/merchant-portal-user-guides/202108.0/products/abstract-products/creating-marketplace-abstract-product.md
> +template: back-office-user-guide-template
We don't have a separate template for Merchant Portal guides. We use a single back-office-user-guide-template. If needed, I can create a separate one for Merchant Portal guides. However, customers on the website will not be able to see it on the website, it's needed for the internal use.

2021-08-30 10:45 UTC, gibmirmilch commented on docs/marketplace/user/merchant-portal-user-guides/202108.0/products/abstract-products/creating-marketplace-abstract-product.md
> +   3. Select **Abstract product has 1 concrete product** if you are creating an abstract product with a single concrete product. *Create an Abstract Product with 1 Concrete Product* drawer opens.
added

2021-08-30 10:45 UTC, gibmirmilch commented on docs/marketplace/user/merchant-portal-user-guides/202108.0/products/abstract-products/creating-marketplace-abstract-product.md
> +   Select **Abstract product has multiple concrete products** if the abstract product you are creating will contain multiple concrete products assigned to it.
added

2021-08-30 10:45 UTC, gibmirmilch commented on docs/marketplace/user/merchant-portal-user-guides/202108.0/products/abstract-products/creating-marketplace-abstract-product.md
> +      1. Select a super attribute that define your concrete products.
added

2021-08-30 10:45 UTC, gibmirmilch commented on docs/marketplace/user/merchant-portal-user-guides/202108.0/products/abstract-products/creating-marketplace-abstract-product.md
> +      2. In the field next to the super attribute you've selected, select one or more product attribute values. Upon adding the super attribute values, the preview of the concrete products will be di
added

2021-08-30 12:13 UTC, gibmirmilch commented on docs/marketplace/user/merchant-portal-user-guides/202108.0/products/abstract-products/creating-marketplace-abstract-product.md
> +| SKU prefix                                      | Unique abstract product identifier that is used to track unique information related to the product. |
Autogenerate SKUs is described later, in the reference information. No need to add it here.

2021-08-30 12:15 UTC, gibmirmilch commented on docs/marketplace/user/merchant-portal-user-guides/202108.0/products/abstract-products/creating-marketplace-abstract-product.md
> +| Autogenerate SKU         | Select this checkmark if you want the SKU to be generated automatically. By default, -1 is added to the abstract product SKU. For example, |
added.

2021-08-30 12:34 UTC, gibmirmilch commented on docs/marketplace/user/merchant-portal-user-guides/202108.0/products/abstract-products/creating-marketplace-abstract-product.md
> +## Creating a marketplace abstract product
we call the features the way they are named in the release app https://release.spryker.com/features/view/108

2021-08-31 14:18 UTC, gibmirmilch commented on docs/marketplace/user/merchant-portal-user-guides/202108.0/products/concrete-products/creating-marketplace-concrete-product.md
> +Once the product is created, it needs to be [activated by the Marketplace administrator in the Back Office](/docs/marketplace/user/back-office-user-guides/{{ page.version }}/catalog/products/managing
updated the info

2021-09-07 12:14 UTC, gibmirmilch commented on docs/marketplace/user/merchant-portal-user-guides/202108.0/products/abstract-products/managing-marketplace-abstract-product-prices.md
> +description: This topic describes how to manage marketplace abstract product prices in the Merchant Portal.
added volume prices information

2021-09-10 10:06 UTC, AdvaBD requested changes

2021-09-15 12:39 UTC, lenadoc requested changes

2021-09-15 12:39 UTC, lenadoc commented on docs/marketplace/user/merchant-portal-user-guides/202108.0/products/concrete-products/managing-marketplace-concrete-product.md
> +title: Managing a marketplace concrete product
```suggestion
title: Managing marketplace concrete products
```

2021-09-15 12:39 UTC, lenadoc commented on docs/marketplace/user/merchant-portal-user-guides/202108.0/products/concrete-products/managing-marketplace-concrete-product.md
> +## (De)Activating a concrete product
```suggestion
## Activating and deactivating a concrete product
```

2021-09-15 12:39 UTC, lenadoc commented on docs/marketplace/user/merchant-portal-user-guides/202108.0/products/concrete-products/managing-marketplace-concrete-product.md
> +title: Managing a marketplace concrete product
Please change the link accordingly as well

2021-09-15 12:39 UTC, lenadoc commented on docs/marketplace/user/merchant-portal-user-guides/202108.0/products/concrete-products/managing-marketplace-concrete-product.md
> +To edit the existing marketplace concrete product:
```suggestion
To edit an existing marketplace concrete product:
```

2021-09-15 12:39 UTC, lenadoc commented on docs/marketplace/user/merchant-portal-user-guides/202108.0/products/concrete-products/managing-marketplace-concrete-product.md
> +2. In the *Stock* pane, enter the quantity in the *Quantity* field.
```suggestion
2. In the *Stock* pane, populate the *Quantity* field.
```

2021-09-15 12:39 UTC, lenadoc commented on docs/marketplace/user/merchant-portal-user-guides/202108.0/products/concrete-products/managing-marketplace-concrete-product.md
> +6. In the *Searchability* pane, from the drop-down menu select the locale(s) where the product is searchable.
```suggestion
6. In the *Searchability* pane, from the drop-down menu select the locales where the product is searchable.
```

2021-09-15 12:39 UTC, lenadoc commented on docs/marketplace/user/merchant-portal-user-guides/202108.0/products/concrete-products/managing-marketplace-concrete-product.md
> +|                |  Concrete Product is online    | The check-box that once selected will make the product active and available in the store. |               |
```suggestion
|                |  Concrete Product is online    | The selected check box makes the product active and available in store. |               |
```

2021-09-15 12:39 UTC, lenadoc commented on docs/marketplace/user/merchant-portal-user-guides/202108.0/products/concrete-products/managing-marketplace-concrete-product.md
> +|                 |   Reserved Stock           | The number of items of this concrete product that are reserved according to *Orders*. |               |
```suggestion
|                 |   Reserved Stock           | Number of items of this concrete product that are reserved according to *Orders*. |               |
```

2021-09-15 12:39 UTC, lenadoc commented on docs/marketplace/user/merchant-portal-user-guides/202108.0/products/concrete-products/managing-marketplace-concrete-product.md
> +|                  |  Quantity                 | The number of items available in the warehouse. The default is 0. | ✓ |
```suggestion
|                  |  Quantity                 | Number of items available in the warehouse. The default is 0. | ✓ |
```

2021-09-15 12:39 UTC, lenadoc commented on docs/marketplace/user/merchant-portal-user-guides/202108.0/products/concrete-products/managing-marketplace-concrete-product.md
> +|                  |  Always in Stock           | The check-box that once selected will make the product always available to be purchased. |               |
```suggestion
|                  |  Always in Stock           | The selected check box makes the product always available for purchase. |               |
```

2021-09-15 12:39 UTC, lenadoc commented on docs/marketplace/user/merchant-portal-user-guides/202108.0/products/concrete-products/managing-marketplace-concrete-product.md
> +| Name                  |  | The name of your product that will be displayed in the online store for your customers. | ✓ |
```suggestion
| Name                  |  | Name of your product displayed on the Storefront. | ✓ |
```

2021-09-15 12:39 UTC, lenadoc commented on docs/marketplace/user/merchant-portal-user-guides/202108.0/products/concrete-products/managing-marketplace-concrete-product.md
> +|               |  Use Abstract Product name for all locales   | Once the checkbox is selected, the name from the abstract product is taken over. |              |
```suggestion
|               |  Use Abstract Product name for all locales   | Select the check box to take over the name of the abstract. |              |
```

2021-09-15 12:39 UTC, lenadoc commented on docs/marketplace/user/merchant-portal-user-guides/202108.0/products/concrete-products/managing-marketplace-concrete-product.md
> +| Description           |  | The description of the product that your customer sees in the online store. |           |
```suggestion
| Description           |  | Product description. |           |
```

2021-09-15 12:39 UTC, lenadoc commented on docs/marketplace/user/merchant-portal-user-guides/202108.0/products/concrete-products/managing-marketplace-concrete-product.md
> +|              |  Use Abstract Product description for all locales    | Once the checkbox is selected, the description from the abstract product is taken over. |       |
```suggestion
|              |  Use Abstract Product description for all locales    | Select the check box to take over the description of the abstract.. |       |
```

2021-09-15 12:39 UTC, lenadoc commented on docs/marketplace/user/merchant-portal-user-guides/202108.0/products/concrete-products/managing-marketplace-concrete-product.md
> +| Price                 |  | In this pane, you can manage prices for your concrete product. See [Managing marketplace concrete product prices](/docs/marketplace/user/merchant-portal-user-guides/{{ pa
The link does not display as link on a website locally

2021-09-15 12:39 UTC, lenadoc commented on docs/marketplace/user/merchant-portal-user-guides/202108.0/products/concrete-products/managing-marketplace-concrete-product.md
> +- [Manage concrete product prices](/docs/marketplace/user/merchant-portal-user-guides/{{ page.version }}/products/concrete-products/managing marketplace-concrete-product-prices.html)
the link does not work

2021-09-15 12:39 UTC, lenadoc commented on docs/marketplace/user/merchant-portal-user-guides/202108.0/products/concrete-products/managing-marketplace-concrete-products-image-sets.md
> +3. In the *SET NAME*, enter the name of the set.
```suggestion
3. In *SET NAME*, enter the name of the set.
```

2021-09-15 12:39 UTC, lenadoc commented on docs/marketplace/user/merchant-portal-user-guides/202108.0/products/concrete-products/managing-marketplace-concrete-products-image-sets.md
> +4. In the *IMAGE ORDERED*,enter the number which defines the order of the images displayed.
```suggestion
4. In *IMAGE ORDER*, enter the number which defines the order of the images displayed.
```

2021-09-15 12:39 UTC, lenadoc commented on docs/marketplace/user/merchant-portal-user-guides/202108.0/products/concrete-products/managing-marketplace-concrete-products-image-sets.md
> +5. In the *SMALL IMAGE URL*, enter the URL.
```suggestion
5. In *SMALL IMAGE URL*, enter the URL.
```

2021-09-15 12:39 UTC, lenadoc commented on docs/marketplace/user/merchant-portal-user-guides/202108.0/products/concrete-products/managing-marketplace-concrete-products-image-sets.md
> +6. In the *LARGE IMAGE URL*, enter the URL.
```suggestion
6. In *LARGE IMAGE URL*, enter the URL.
```

2021-09-15 12:39 UTC, lenadoc commented on docs/marketplace/user/merchant-portal-user-guides/202108.0/products/concrete-products/managing-marketplace-concrete-products-image-sets.md
> +    - IMAGE ORDERED
```suggestion
    - IMAGE ORDER
```

2021-09-15 12:39 UTC, lenadoc commented on docs/marketplace/user/merchant-portal-user-guides/202108.0/products/concrete-products/managing-marketplace-concrete-products-image-sets.md
> +To delete an image in the image set for the marketplace concrete product:
```suggestion
To delete an image in the image set for a marketplace concrete product:
```

2021-09-15 12:39 UTC, lenadoc commented on docs/marketplace/user/merchant-portal-user-guides/202108.0/products/concrete-products/managing-marketplace-concrete-products-image-sets.md
> +2. Select a default or a specific locale you want to delete an image for.
```suggestion
2. Select a default or a specific locale you want to delete the image for.
```

2021-09-15 12:39 UTC, lenadoc commented on docs/marketplace/user/merchant-portal-user-guides/202108.0/products/abstract-products/managing-marketplace-abstract-product-image-sets.md
> +2. Select a default or specific locale you want to delete an image for.
```suggestion
2. Select a default or specific locale you want to delete the image for.
```

2021-09-15 12:39 UTC, lenadoc commented on docs/marketplace/user/merchant-portal-user-guides/202108.0/products/abstract-products/managing-marketplace-abstract-product-image-sets.md
> +| Image ordered   | If you add several images to an image set, specify the order in which they are to be shown in the front end and back end using *Image ordered* field. The order of images is define
What are the "front end and back end" - Storefront and Back Office?

2021-09-15 12:39 UTC, lenadoc commented on docs/marketplace/user/merchant-portal-user-guides/202108.0/products/concrete-products/managing-marketplace-concrete-products-image-sets.md
> +| Image ordered   | If you add several images to an image set, specify the order in which they are to be shown in the front end and back end using *Image ordered* field. The order of images is define
What are the "front end and back end" - Storefront and Back Office?

2021-09-15 12:39 UTC, lenadoc commented on docs/marketplace/user/merchant-portal-user-guides/202108.0/products/concrete-products/managing-marketplace-concrete-products-image-sets.md
> +- [Manage concrete product prices](docs/marketplace/user/merchant-portal-user-guides/{{ page.version }}/products/concrete-products/managing marketplace-concrete-product-prices.html)
broken link

2021-09-16 10:52 UTC, lenadoc approved these changes

2021-09-16 10:54 UTC, merged