CC-13273 Disaply Number in Zed documentation.
spryker/spryker-docs pull request #1205
Opened 2022-08-30 12:49 UTC by romanhavrylko

## PR Description

Epic: https://spryker.atlassian.net/browse/CC-13273

Ticket for IG: https://spryker.atlassian.net/browse/CC-13287

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2022-09-01 12:21 UTC, DmitryLymarenko commented
JS adjustments were made at Gui module
I didn't see frontend building is mentioned

2022-09-01 13:05 UTC, DmitryLymarenko submitted a review, later dismissed

2022-09-02 11:51 UTC, jeremyfourna requested changes
Fix small typos and structure

2022-09-02 11:51 UTC, jeremyfourna commented on _includes/pbc/all/install-features/202212.0/install-the-spryker-core-back-office-feature.md
> +
Remove the extra line between each point

2022-09-02 11:51 UTC, jeremyfourna commented on _includes/pbc/all/install-features/202212.0/install-the-spryker-core-back-office-feature.md
> +
Remove the extra line between each point

2022-09-02 11:51 UTC, jeremyfourna commented on _includes/pbc/all/install-features/202212.0/install-the-spryker-core-back-office-feature.md
> +
Remove the extra line between each point

2022-09-02 11:51 UTC, jeremyfourna commented on _includes/pbc/all/install-features/202212.0/install-the-spryker-core-back-office-feature.md
> +
Remove the extra line between each point

2022-09-02 11:51 UTC, jeremyfourna commented on docs/scos/dev/tutorials-and-howtos/howtos/feature-howtos/202212.0/howto-add-support-of-number-formatting-in-backoffice.md
> +{Overview}
Why the brackets are needed here?

2022-09-02 11:51 UTC, jeremyfourna commented on docs/scos/dev/tutorials-and-howtos/howtos/feature-howtos/202212.0/howto-add-support-of-number-formatting-in-backoffice.md
> +## {Step-by-step instructions}
Why the brackets are needed here?

2022-09-02 11:56 UTC, romanhavrylko commented on docs/scos/dev/tutorials-and-howtos/howtos/feature-howtos/202212.0/howto-add-support-of-number-formatting-in-backoffice.md
> +## {Step-by-step instructions}
Removed.

2022-09-02 11:56 UTC, romanhavrylko commented on docs/scos/dev/tutorials-and-howtos/howtos/feature-howtos/202212.0/howto-add-support-of-number-formatting-in-backoffice.md
> +{Overview}
Removed.

2022-09-02 13:24 UTC, jeremyfourna approved these changes
OK for me

2022-09-06 08:14 UTC, VadymSachenko approved these changes

2022-09-06 08:14 UTC, merged