Reviewing /docs/socs/dev/back-end-development/
spryker/spryker-docs pull request #1258
Opened 2022-09-23 12:19 UTC by VadymSachenko

## PR Description
Doing a review of the documents in /docs/socs/dev/back-end-development/

TBD

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2022-09-29 12:33 UTC, andriitserkovnyi approved these changes

2022-09-29 12:34 UTC, andriitserkovnyi requested changes
A small comment, yet an important one.

2022-09-29 14:21 UTC, VadymSachenko commented on docs/scos/dev/back-end-development/data-manipulation/create-an-order-management-system-spryker-commerce-os.md
> +You need to just built a new order process. To test it, do the following:
Fixed. Take a look again

2022-10-03 06:47 UTC, andriitserkovnyi approved these changes

2022-10-03 06:48 UTC, merged