Pbc/dam
spryker/spryker-docs pull request #1263
Opened 2022-09-27 13:24 UTC by andriitserkovnyi

## PR Description

Docs for the Digital asset management PBC

## Checklist
- [x] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2022-09-29 14:21 UTC, lenadoc submitted a review, later dismissed

2022-10-04 08:03 UTC, VadymSachenko requested changes

2022-10-04 08:03 UTC, VadymSachenko commented on docs/pbc/all/digital-asset-management/manage-in-the-back-office/manage-file-tree.md
> +* File List (for more details, see [Managing File List](/docs/pbc/all/digital-asset-management/manage-in-the-back-office/manage-file-list.html))
```suggestion
* File List (for more details, see [Manage file List](/docs/pbc/all/digital-asset-management/manage-in-the-back-office/manage-file-list.html))
```

2022-10-04 12:04 UTC, VadymSachenko approved these changes

2022-10-04 12:35 UTC, merged