Cart and checkout PBC edits
spryker/spryker-docs pull request #1325
Opened 2022-10-28 09:56 UTC by AlexSlawinski

A review of the cart and checkout PBC documentation.

## PR Description

TBD

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2022-10-28 15:41 UTC, lenadoc requested changes

2022-10-28 15:41 UTC, lenadoc commented on docs/pbc/all/cart-and-checkout/checkout-feature-overview/checkout-feature-overview.md
> +* Support promotional campaigns — for example, by offering free shipping for orders above a threshold.
I believe in the original version it used to be an em dash, at least on the live documentation page it looks more like em dash :) Please check here https://developers.google.com/style/dashes and consider if the original dash should be left

2022-10-28 15:41 UTC, lenadoc commented on docs/pbc/all/cart-and-checkout/cart-feature-overview/cart-notes-overview.md
> +*Cart Notes* let Shop administrators include the **Notes** field on the **Cart** page. Customers can add notes to a particular item or the whole cart. for example, they can add special instructions a
```suggestion
*Cart Notes* let Shop administrators include the **Notes** field on the **Cart** page. Customers can add notes to a particular item or the whole cart. For example, they can add special instructions about preparing and delivering an order.
```

2022-10-28 15:41 UTC, lenadoc commented on docs/pbc/all/cart-and-checkout/extend-and-customize/cart-module-reference-information.md
> +* *Item grouping*. `Cart` uses the item grouper to group items in the cart using a specially crafted group key, which is provided by the cart expander — for example, a list containing the same item c
Same here for the em dash. Please check if the original em dash should be left

2022-10-28 15:41 UTC, lenadoc commented on docs/pbc/all/cart-and-checkout/multiple-carts-feature-overview.md
> +Sometimes customers need more than one shopping cart — for example, one for daily purchases and the other one for monthly expenses. The *Multiple Carts* feature lets you create and manage multiple sh
Same here for the em dash

2022-10-28 15:41 UTC, lenadoc commented on docs/pbc/all/cart-and-checkout/persistent-cart-sharing-feature-overview.md
> +The cart can be shared with internal users — the users of the business unit, and external users—non-company users (friends, relatives, followers on social media). By accessing the provided URL, a use
Same here for the em dash

2022-10-31 08:26 UTC, AlexSlawinski commented
hi @lenadoc, committed the changes - let me know if there is anything else I can do to improve the documentation!

2022-11-02 14:52 UTC, lenadoc approved these changes

2022-11-03 04:09 UTC, merged