FRW-425 Refactored public documentation regarding GLUE infrastructure
spryker/spryker-docs pull request #1337
Opened 2022-11-02 12:53 UTC by dimitriyTsemma

## PR Description

Ticket: https://spryker.atlassian.net/browse/FRW-493

## Checklist
- [x] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2022-11-09 13:14 UTC, gechetspr requested changes

2022-11-09 13:14 UTC, gechetspr commented on docs/scos/dev/feature-integration-guides/202204.0/glue-api/decoupled-glue-infrastructure/glue-api-documentation-generation.md
> +        $contextExpanderCollection->addExpander(new StorefrontResourcesContextExpanderPlugin(), [static::GLUE_STOREFRONT_API_APPLICATION_NAME]);
do we have it documented somewhere what is the second param in addExpander method and why do we have it this way in the example?

2022-11-09 13:14 UTC, gechetspr commented on docs/scos/dev/glue-api-guides/202204.0/decoupled-glue-infrastructure/backend-and-storefront-api-module-differences.md
> + * @method \Spryker\Zed\CustomApiApplication\Persistence\CustomApiApplicationRepositoryInterface getRepository()
Pyz

2022-11-09 13:14 UTC, gechetspr commented on docs/scos/dev/glue-api-guides/202204.0/decoupled-glue-infrastructure/how-to-guides/how-to-create-or-change-a-convention.md
> +```
Mb we can add some paragraph with info about when we have no convention in place?

2022-11-10 12:30 UTC, gechetspr submitted a review, later dismissed

2022-11-18 13:02 UTC, AlexSlawinski requested changes

2022-11-18 13:27 UTC, dimitriyTsemma commented on docs/scos/dev/glue-api-guides/202204.0/decoupled-glue-infrastructure/how-to-guides/how-to-create-or-change-a-convention.md
> +To use newly created convention you must add it to the `GlueApplicationDependencyProvider` to the method `getConventionPlugins()`.
no, it means that 'you must add it to y, which is situated inside x'
Changed to 
To use the newly created convention, you must add it to the `GlueApplicationDependencyProvider::getConventionPlugins()`.

2022-11-18 14:05 UTC, AlexSlawinski approved these changes

2022-11-21 11:34 UTC, AlexSlawinski approved these changes

2022-11-21 12:29 UTC, AlexSlawinski approved these changes

2022-11-21 13:35 UTC, AlexSlawinski approved these changes

2022-11-21 14:11 UTC, merged