Review digital asset management
spryker/spryker-docs pull request #1383
Opened 2022-11-18 14:37 UTC by michelleegan11

## PR Description

Reviewed and made language, structural and content edits. Replaced two screenshots.

## Checklist
- [x ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2022-11-22 12:00 UTC, lenadoc requested changes

2022-11-22 14:42 UTC, michelleegan11 commented on docs/pbc/all/digital-asset-management/manage-in-the-back-office/manage-file-list.md
> -* If you only update the attributes, no new version is created.
Agreed. I re-added this information (and made a few related language changes).

2022-11-23 12:18 UTC, lenadoc approved these changes

2022-11-24 14:42 UTC, lenadoc approved these changes

2022-11-25 08:32 UTC, merged