CC-23709: Added update cart totals based on shipment selector IG.
spryker/spryker-docs pull request #1412
Opened 2022-11-29 15:57 UTC by sakharova-yuliia

## PR Description

Ticket:  https://spryker.atlassian.net/browse/CC-23709

2022-12-07 12:53 UTC, ilyakubanov requested changes
please create guides where use newly introduced includes

2022-12-07 12:53 UTC, ilyakubanov commented on _includes/pbc/all/install-features/202212.0/install-glue-api/install-the-cart-glue-api.md
> +| Glue API: Spryker Core | {{page.version}} | [Glue API: Spryker Core feature integration](/docs/scos/dev/feature-integration-guides/{{page.version}}/glue-api/glue-api-spryker-core-feature-integratio
```suggestion
| Glue API: Spryker Core | {{site.version}} | [Glue API: Spryker Core feature integration](/docs/scos/dev/feature-integration-guides/{{page.version}}/glue-api/glue-api-spryker-core-feature-integration.html) |
```
as in other places, please fix everywhere

2022-12-07 12:53 UTC, ilyakubanov commented on _includes/pbc/all/install-features/202212.0/install-glue-api/install-the-cart-glue-api.md
> +| GuestCartByRestCheckoutDataResourceRelationshipPlugin | Adds `guest-carts` resource as the relationship by `RestCheckoutDataTransfer.quote`. Applies only for guest customers. |               | Spry
must be in Checkout as we discussed

2022-12-07 12:53 UTC, ilyakubanov commented on _includes/pbc/all/install-features/202212.0/install-glue-api/install-the-checkout-glue-api.md
> +| Glue API: Spryker Core                 | 202204.0         | [Glue API: Spryker Core feature integration](/docs/scos/dev/feature-integration-guides/202204.0/glue-api/glue-api-spryker-core-feature-in
please fix to {{site.version}} everywhere

2022-12-09 11:42 UTC, ilyakubanov submitted a review, later dismissed

2022-12-13 10:26 UTC, VadymSachenko approved these changes

2022-12-13 11:44 UTC, VadymSachenko approved these changes

2022-12-13 11:44 UTC, merged