Update integrate-bazaarvoice.md
spryker/spryker-docs pull request #1421
Opened 2022-12-01 13:52 UTC by jeremyfourna

## PR Description

Add the trusted hosts' changes that ACP customers will need to do.

## Checklist
- [x] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2022-12-01 13:53 UTC, k4emic submitted a review, later dismissed

2022-12-02 11:37 UTC, VadymSachenko requested changes

2022-12-02 11:37 UTC, VadymSachenko commented on docs/pbc/all/ratings-reviews/third-party-integrations/integrate-bazaarvoice.md
> +## 1. Connect Bazaarvoice
Are we integrating or connecting it?

2022-12-02 11:37 UTC, VadymSachenko commented on docs/pbc/all/ratings-reviews/third-party-integrations/integrate-bazaarvoice.md
> +## 2. Whitelist Bazaarvoice Domain
```suggestion
## 2. Add Bazaarvoice domain to your allowlist
```

2022-12-02 11:37 UTC, VadymSachenko commented on docs/pbc/all/ratings-reviews/third-party-integrations/integrate-bazaarvoice.md
> +To enable your customers to leave reviews on your products, you must add Bazaarvoice domain inside your **Content Security Policy** whitelist. To do that please change your `deploy.yml` file or your
```suggestion
To enable your customers to leave reviews on your products, you must add the Bazaarvoice domain inside your **Content Security Policy** allowlist. To do that, change your `deploy.yml` file or your `config/Shared/config_default.php` file if changing the environment variable is not possible.
```

2022-12-02 11:37 UTC, VadymSachenko commented on docs/pbc/all/ratings-reviews/third-party-integrations/integrate-bazaarvoice.md
> +Changes required in the `deploy.yml` file.
```suggestion
In the `deploy.yml` file, introduce the required changes: 
```

2022-12-02 11:37 UTC, VadymSachenko commented on docs/pbc/all/ratings-reviews/third-party-integrations/integrate-bazaarvoice.md
> +Alternatively, you may whitelist the domain from the `config/Shared/config_default.php` file. If you updated the `deploy.yml` file, then this step can be ignored.
```suggestion
Alternatively, you may add the domain to the allowlist from the `config/Shared/config_default.php` file. If you updated the `deploy.yml` file, then this step can be ignored.
```

2022-12-02 15:13 UTC, jeremyfourna commented on docs/pbc/all/ratings-reviews/third-party-integrations/integrate-bazaarvoice.md
> +## 1. Connect Bazaarvoice
In ACP we are "Connecting" apps lol

2022-12-02 15:52 UTC, VadymSachenko approved these changes

2022-12-02 15:53 UTC, merged