Add landing page
spryker/spryker-docs pull request #1433
Opened 2022-12-06 15:40 UTC by michelleegan11

## PR Description

Added missing landing pages to SCOS developer guides

## Checklist
- [x ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2022-12-20 10:14 UTC, lenadoc requested changes

2022-12-20 13:06 UTC, michelleegan11 commented on docs/scos/dev/best-practices/search-best-practices/search-best-practices.md
> +[Personalization - dynamic pricing](/docs/scos/dev/best-practices/search-best-practices/personalization-dynamic-pricing.html)
I added bullets. Please just let me know if you need me to do anything else with this page

2022-12-20 13:07 UTC, michelleegan11 commented on docs/scos/dev/best-practices/state-machine-cookbook/state-machine-cookbook.md
> +This section explains state machine fundamentals then explains how to model a state machine.
```suggestion
This section explains state machine fundamentals and how to model a state machine. 
```

2022-12-20 13:08 UTC, michelleegan11 commented on docs/scos/dev/best-practices/state-machine-cookbook/state-machine-cookbook.md
> +This section explains state machine fundamentals then explains how to model a state machine.
done

2022-12-20 13:21 UTC, michelleegan11 commented on docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/glue-backend-api.md
> +---
done!

2022-12-21 13:14 UTC, lenadoc approved these changes

2022-12-21 15:05 UTC, merged