Discount Management edits
spryker/spryker-docs pull request #1437
Opened 2022-12-07 09:07 UTC by AlexSlawinski

review of discount management

## PR Description

TBD

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2022-12-07 10:57 UTC, VadymSachenko reviewed
@AlexSlawinski please check links I've shared with you and go through the documents again and make sure they follow Google style guide:
Make the following adjustments:
Details/information on => Details/information on
Enable someone to => let someone
Future tense => Present tense (where applicable)
below => following

When you're done, let me know and I'll check the PR again. Thank you for you effort and time!

2022-12-07 10:57 UTC, VadymSachenko commented on docs/pbc/all/discount-management/import-and-export-data/file-details-discount-store.csv.md
> +| discount_key | &check; | String |A `discount_key` must be included in the `discount.csv` file. |  |
`discount_key` is a parameter name, so we shouldn't use the article in this case. So, it should be whether `discount_key` or the `discount_key` parameter.
```suggestion
| discount_key | &check; | String |`discount_key` must be included in the `discount.csv` file. |  |
```

2022-12-07 10:57 UTC, VadymSachenko commented on docs/pbc/all/discount-management/import-and-export-data/file-details-discount-voucher.csv.md
> +| discount_key | &check; | String |A `discount_key` must exist in the `discounts.csv` file | The key identifier of the discount. |
same
```suggestion
| discount_key | &check; | String |`discount_key` must exist in the `discounts.csv` file | The key identifier of the discount. |
```

2022-12-07 10:57 UTC, VadymSachenko commented on docs/pbc/all/discount-management/manage-via-glue-api/manage-discounts-via-glue-api.md
> +The [Promotions](/docs/pbc/all/discount-management/discount-management.html) functionality enables sellers to provide a promotional item that the customers can add to their carts at a discounted pric
enable => let - see https://developers.google.com/style/word-list#enable
```suggestion
The [Promotions](/docs/pbc/all/discount-management/discount-management.html) functionality lets sellers provide a promotional item that the customers can add to their carts at a discounted price or even for free. To be eligible for promotions, the purchase must fulfill certain discount conditions—for example, the purchase amount exceeding a certain threshold.
```

2022-12-07 10:57 UTC, VadymSachenko requested changes
@AlexSlawinski please check links I've shared with you and go through the documents again and make sure they follow Google style guide:
Make the following adjustments:
Details/information on => Details/information on
Enable someone to => let someone
Future tense => Present tense (where applicable)
below => following

When you're done, let me know and I'll check the PR again. Thank you for you effort and time!

2022-12-12 08:53 UTC, AlexSlawinski commented on docs/pbc/all/discount-management/manage-via-glue-api/manage-discounts-via-glue-api.md
> +In your development, the Promotions API helps you enable customers to redeem the benefits provided by promotions and check the correct order amount with the discount included.
```suggestion
In your development, the Promotions API helps you to allow customers to redeem the benefits provided by promotions and check the correct order amount with the discount included.
```

2022-12-13 14:34 UTC, VadymSachenko approved these changes

2022-12-13 14:45 UTC, merged