Add frntend dev sub landing pages
spryker/spryker-docs pull request #1488
Opened 2023-01-02 12:31 UTC by michelleegan11

## PR Description

Added subsection landing pages to docs.spryker.com/docs/scos/dev/front-end-development/index.html

## Checklist
- [ X] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2023-01-10 12:07 UTC, VadymSachenko requested changes
@michelleegan11 see my comments please.
Also, you need to add these landing pages to the scos sidebar if you haven't done yet.

2023-01-10 13:45 UTC, michelleegan11 commented
> @michelleegan11 see my comments please. Also, you need to add these landing pages to the scos sidebar if you haven't done yet.

I just added them to the sidebar in this PR, thanks

2023-01-16 09:51 UTC, lenadoc approved these changes

2023-01-16 11:32 UTC, VadymSachenko approved these changes

2023-01-16 13:10 UTC, merged