SDK-1658: Add article about supported plugin registration ways
spryker/spryker-docs pull request #1493
Opened 2023-01-03 13:04 UTC by DmytroKlymanSpryker

## PR Description

Add article about supported plugin registration ways

Ticket: https://spryker.atlassian.net/browse/SDK-1658

## Checklist
- [x] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2023-01-09 10:17 UTC, AlexSlawinski requested changes

2023-01-09 10:17 UTC, AlexSlawinski commented on docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/supported-code-changes.md
> +<em>Code example 3.2.4</em>: Method returns associative array (with constants, parent method call and array merging)
```suggestion
<em>Code example 3.2.4</em>: Method returns with associative array (with constants, parent method call and array merging)
```

2023-01-09 10:17 UTC, AlexSlawinski commented on docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/supported-code-changes.md
> +Multidimensional arrays (up to 2 levels) are also supported here, but for its usage the wrapped function MUST be used.
```suggestion
Multidimensional arrays up to 2 levels are also supported here, but for its usage the wrapped function MUST be used.
```

2023-01-12 13:46 UTC, DmytroKlymanSpryker commented on docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/supported-code-changes.md
> +Manifests support plugins registration in the dependency provider and plugins registration in the configuration files. There are multiple ways how the plugins can be registered inside of the project.
I rephrased this sentence to avoid the repetition of the 'plugins registration' combination of words.

2023-01-13 09:44 UTC, AlexSlawinski approved these changes

2023-01-19 07:59 UTC, merged