Add landing pages to 202212 0
spryker/spryker-docs pull request #1510
Opened 2023-01-10 12:29 UTC by michelleegan11

## PR Description

add landing pages to 202212.0 version of docs

## Checklist
- [ x] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2023-01-10 13:01 UTC, VadymSachenko commented on docs/scos/dev/glue-api-guides/202212.0/managing-b2b-account/managing-b2b-account.md
> +description: Describes the endpoints used to manage a B2B account
```suggestion
description: This document describes the endpoints used to manage a B2B account
```

2023-01-10 13:05 UTC, VadymSachenko requested changes

2023-01-10 13:05 UTC, VadymSachenko commented on docs/scos/dev/glue-api-guides/202212.0/managing-b2b-account/managing-b2b-account.md
> +template: concept-topic-template
add the `last_updated` tag

2023-01-10 13:05 UTC, VadymSachenko commented on docs/scos/dev/glue-api-guides/202212.0/managing-products/managing-products.md
> +template: concept-topic-template
add the `last_updated` tag

2023-01-10 13:05 UTC, VadymSachenko commented on docs/scos/dev/glue-api-guides/202212.0/managing-products/managing-products.md
> +
```suggestion
```

2023-01-10 13:05 UTC, VadymSachenko commented on docs/scos/dev/glue-api-guides/202212.0/managing-products/managing-products.md
> +
```suggestion
```

2023-01-10 13:05 UTC, VadymSachenko commented on docs/scos/dev/glue-api-guides/202212.0/managing-products/managing-products.md
> +
```suggestion
```

2023-01-10 13:05 UTC, VadymSachenko commented on docs/scos/dev/glue-api-guides/202212.0/managing-products/managing-products.md
> +
```suggestion
```

2023-01-10 13:05 UTC, VadymSachenko commented on docs/scos/dev/glue-api-guides/202212.0/managing-products/managing-products.md
> +description: Describes the endpoints used to manage products
```suggestion
description: This document describes the endpoints used to manage products
```

2023-01-10 13:19 UTC, VadymSachenko commented
@michelleegan11 please add your pages to the scos sidebar if you haven't done it yet.

2023-01-10 13:50 UTC, michelleegan11 commented
> @michelleegan11 please add your pages to the scos sidebar if you haven't done it yet.

I've added them in this PR, thanks
https://github.com/spryker/spryker-docs/pull/1494/files

2023-01-11 11:03 UTC, VadymSachenko approved these changes

2023-01-11 12:54 UTC, merged