FRW-1241: Adjusted strict search documentation
spryker/spryker-docs pull request #1558
Opened 2023-01-23 17:29 UTC by olhalivitchuk

## PR Description

https://spryker.atlassian.net/browse/FRW-1241

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2023-01-23 17:45 UTC, asmarovydlo requested changes

2023-01-23 17:45 UTC, asmarovydlo commented on docs/scos/dev/back-end-development/zed-ui-tables/create-and-configure-zed-tables.md
>  ### Configure strict search
```suggestion
### Configure search by columns
```

Please update the documentation below, as we would have just added a search by columns, not a `strict search`.
Please make sure, that this paragraph only refers to the existing search for comparison reasons.

2023-01-23 17:45 UTC, asmarovydlo commented on docs/scos/dev/back-end-development/zed-ui-tables/create-and-configure-zed-tables.md
> +increased from 6400ms to 3900ms.
Is it query time, or the page load?

2023-01-23 17:45 UTC, asmarovydlo commented on docs/scos/dev/back-end-development/zed-ui-tables/create-and-configure-zed-tables.md
> +In order to solve the performance issues, a strict search mode has been introduced and can be used on all backoffice data tables which extend the `AbstractTable` class.
> In order to solve the performance issues


We've already mentioned performance improvements below. (Also, this is not the only reason why we need to search per column)

Please get rid of this message.

2023-01-23 17:57 UTC, olhalivitchuk commented on docs/scos/dev/back-end-development/zed-ui-tables/create-and-configure-zed-tables.md
> +increased from 6400ms to 3900ms.
Page load execution time

2023-01-23 18:01 UTC, asmarovydlo commented on docs/scos/dev/back-end-development/zed-ui-tables/create-and-configure-zed-tables.md
> +increased from 6400ms to 3900ms.
Please update to query execution time.

2023-01-23 18:37 UTC, asmarovydlo approved these changes

2023-01-24 08:27 UTC, AlexSlawinski commented on docs/scos/dev/back-end-development/zed-ui-tables/create-and-configure-zed-tables.md
> +Search by columns can be used on all backoffice data tables which extend the `AbstractTable` class.
```suggestion
Search by columns can be used on all Back Office data tables which extend the `AbstractTable` class.
```

2023-01-24 08:27 UTC, AlexSlawinski commented on docs/scos/dev/back-end-development/zed-ui-tables/create-and-configure-zed-tables.md
> +For example, getting the results using search by columns for tables with ~200k rows
```suggestion
For example, getting the results using search by columns for tables with ~200k rows improved speed from 0,031s to 0,003s. 

```

2023-01-24 08:27 UTC, AlexSlawinski commented on docs/scos/dev/back-end-development/zed-ui-tables/create-and-configure-zed-tables.md
> +increased from 0,031s to 0,003s.
```suggestion
```

2023-01-24 08:35 UTC, AlexSlawinski approved these changes

2023-01-24 09:01 UTC, merged