Publish cloud drafts
spryker/spryker-docs pull request #1562
Opened 2023-01-25 08:43 UTC by andriitserkovnyi

## PR Description

Move docs from drafts to public folders

## Checklist
- [x] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2023-01-25 13:30 UTC, hatemzidi-pro commented on docs/scos/dev/the-docker-sdk/202212.0/deploy-file/deploy-file-reference-1.0.md
> +### environment-configuration: secrets:
i'm not sure that this part must be published.

2023-01-25 13:30 UTC, hatemzidi-pro commented on docs/scos/dev/the-docker-sdk/202212.0/deploy-file/deploy-file-reference-1.0.md
> +### environment-configuration: params:
same ! it's not meant to be published

2023-01-26 14:19 UTC, hatemzidi-pro approved these changes
LGTM

2023-01-31 08:46 UTC, VadymSachenko requested changes
@andriitserkovnyi see my comments and suggestions

2023-01-31 08:46 UTC, VadymSachenko commented on docs/scos/dev/the-docker-sdk/202212.0/define-parameters-and-secrets.md
> +| bucket | Defines what the secret or parameter is used for. Acceptable value is `app`. In future, we will enable variables to be injected into other components. |
Predicting the future is not a good idea.
```suggestion
| bucket | Defines what the secret or parameter is used for. Acceptable value is `app`. |
```

2023-01-31 08:46 UTC, VadymSachenko commented on docs/scos/dev/the-docker-sdk/202212.0/deploy-file/deploy-file-reference-1.0.md
> +* `environment-configuration: secrets: grant:`—users' permissions. `limited` provides read while `public` provides read and write permissions. The default one is `limited`.
Starting a sentence with a variable name or value is not recommended. I would rephrase it as follows:
```suggestion
* `environment-configuration: secrets: grant:`—users' permissions. The `limited` permission provides read while `public` provides read and write permissions. The default one is `limited`.
```

2023-01-31 08:46 UTC, VadymSachenko commented on docs/scos/dev/the-docker-sdk/202212.0/deploy-file/deploy-file-reference-1.0.md
> +***
Same
```suggestion
```

2023-01-31 08:46 UTC, VadymSachenko commented on docs/cloud/dev/spryker-cloud-commerce-os/manage-maintenance-mode/enable-and-disable-maintenance-mode.md
> +    The deployment time depends on the application's complexity. Once the deployment is finished, Storefront and Back Office visitors will see the maintenance page. To get access to the frontend appl
```suggestion
    The deployment time depends on the application's complexity. Once the deployment is finished, Storefront and Back Office visitors can see the maintenance page. To get access to the frontend applications in maintenance mode, you can allowlist the needed IP addresses. For instructions, see [Configure access to applications in maintenance mode](/docs/cloud/dev/spryker-cloud-commerce-os/manage-maintenance-mode/configure-access-to-applications-in-maintenance-mode.html).
```

2023-02-06 16:06 UTC, merged