CC-16906: Added invalidation of the customer sessions and Glue tokens after an account deletion or changing a password.
spryker/spryker-docs pull request #1607
Opened 2023-02-09 15:25 UTC by michbeck

## PR Description

TBD

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2023-02-09 17:24 UTC, DmitryLymarenko requested changes

2023-02-09 17:24 UTC, DmitryLymarenko commented on _includes/pbc/all/install-features/202304.0/install-the-customer-account-management-feature.md
> +| CustomerValidationPage  | vendor/spryker-shop/customer-validation-page |
this module and related to it things should be moved to respective section about frontend

2023-02-09 17:24 UTC, DmitryLymarenko commented on _includes/pbc/all/install-features/202304.0/install-the-customer-account-management-feature.md
> +2. Register publish and synchronization queue:
it's more like `Add queue configuration` or something like this
please check similar guides referring this file

2023-02-09 17:24 UTC, DmitryLymarenko commented on _includes/pbc/all/install-features/202304.0/install-the-customer-account-management-feature.md
> +
I see `src/Pyz/Zed/Customer/Persistence/Propel/Schema/spy_customer.schema.xml` is adjusted at nonsplit PR but not mentioned

2023-02-09 17:26 UTC, DmitryLymarenko commented on _includes/pbc/all/install-features/202304.0/install-the-customer-account-management-feature.md
> +            new DeleteExpiredCustomerInvalidatedRecordsConsole(),
this plugin is missing at table with plugin descriptions

2023-02-09 17:27 UTC, DmitryLymarenko commented on _includes/pbc/all/install-features/202304.0/install-the-customer-account-management-feature.md
> +            new LogoutInvalidatedCustomerFilterControllerEventHandlerPlugin(),
the same

please recheck plugins and make sure they all are mentioned at respective tables

2023-02-13 15:24 UTC, DmitryLymarenko submitted a review, later dismissed

2023-02-13 16:07 UTC, KarinOf submitted a review, later dismissed

2023-02-14 15:31 UTC, VadymSachenko approved these changes

2023-02-15 12:25 UTC, merged