CC-25971: Update push notification integration guide
spryker/spryker-docs pull request #1615
Opened 2023-02-13 09:58 UTC by ievgen-malykhin

## PR Description

Update the integration guide for push notification.

## Checklist
- [X] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2023-02-13 13:39 UTC, abitskil approved these changes

2023-02-14 14:18 UTC, VadymSachenko requested changes

2023-02-14 14:40 UTC, VadymSachenko commented on _includes/pbc/all/install-features/202304.0/install-push-notification-feature.md
>  | PushNotificationWebPushPhpConstants::VAPID_PUBLIC_KEY  | Provides `VAPID` public key. Used for authentication to send push notifications.  | Spryker\Shared\PushNotificationWebPushPhp |
```suggestion
| PushNotificationWebPushPhpConstants::VAPID_PUBLIC_KEY  | Provides the `VAPID` public key. Used for authentication to send push notifications.  | Spryker\Shared\PushNotificationWebPushPhp |
```

2023-02-15 08:51 UTC, VadymSachenko approved these changes

2023-02-15 10:05 UTC, merged