SUPESC-606 Updated Availability Notification IG with stores to Yves host mapping configuration.
spryker/spryker-docs pull request #1629
Opened 2023-02-17 10:08 UTC by romanhavrylko

## PR Description

- Ticket: https://spryker.atlassian.net/browse/SUPESC-606

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2023-02-17 10:21 UTC, DmitryLymarenko commented on _includes/pbc/all/install-features/202304.0/install-the-availability-notification-feature.md
> +You can define stores to Yves hosts mapping. This allows generating correct URLs (e.g. unsubscription URL) for multi-store setup.
probably store sharing should be mentioned

2023-02-17 10:31 UTC, DmitryLymarenko submitted a review, later dismissed

2023-02-17 10:49 UTC, KarinOf submitted a review, later dismissed

2023-02-20 08:19 UTC, VadymSachenko commented on _includes/pbc/all/install-features/202304.0/install-the-availability-notification-feature.md
> +To verify that `AvailabilityNotificationAnonymizerPlugin` is working:
```suggestion
To verify that `AvailabilityNotificationAnonymizerPlugin` works:
```

2023-02-20 08:19 UTC, VadymSachenko commented on _includes/pbc/all/install-features/202304.0/install-the-availability-notification-feature.md
> +3. Check that the corresponding line is added to the `spy_availability_notification_subscription` table.</li><li>Delete this user.
rewrite the sentence without </li><li>
```suggestion
3. Check that the corresponding line is added to the `spy_availability_notification_subscription` table.</li><li>Delete this user.
```

2023-02-20 08:20 UTC, VadymSachenko commented on _includes/pbc/all/install-features/202304.0/install-the-availability-notification-feature.md
> +To verify that `AvailabilityNotificationSubscriptionCustomerTransferExpanderPlugin` is working:
```suggestion
To verify that `AvailabilityNotificationSubscriptionCustomerTransferExpanderPlugin` works:
```

2023-02-20 08:31 UTC, VadymSachenko commented on docs/pbc/all/warehouse-management-system/202304.0/install-and-upgrade/install-features/install-the-availability-notification-feature.md
> +last_updated: Jun 16, 2021
```suggestion
last_updated: Feb 17, 2023
```

2023-02-20 09:28 UTC, romanhavrylko commented on _includes/pbc/all/install-features/202304.0/install-the-availability-notification-feature.md
> +2. As a customer, subscribe to its availability notifications on Yves.
This is a part of the original IG and I guess it means Storefront.

2023-02-21 08:59 UTC, VadymSachenko commented on _includes/pbc/all/install-features/202304.0/install-the-availability-notification-feature.md
> +3. On the Storefront, go to account overview > *Newsletters*.
```suggestion
3. On the Storefront, go to account overview&nbsp;<span aria-label="and then">></span> **Newsletters**.
```

2023-02-21 09:00 UTC, VadymSachenko commented on _includes/pbc/all/install-features/202304.0/install-the-availability-notification-feature.md
> +To verify that `AvailabilityNotificationSubscriber` is working, follow these steps:
```suggestion
To verify that `AvailabilityNotificationSubscriber` works, follow these steps:
```

2023-02-21 09:01 UTC, VadymSachenko commented on _includes/pbc/all/install-features/202304.0/install-the-availability-notification-feature.md
> +To verify that `AvailabilityNotificationAnonymizerPlugin` works:
```suggestion
Verify that `AvailabilityNotificationAnonymizerPlugin` works:
```

2023-02-21 09:01 UTC, VadymSachenko commented on _includes/pbc/all/install-features/202304.0/install-the-availability-notification-feature.md
> +To verify that `AvailabilityNotificationSubscriptionCustomerTransferExpanderPlugin` works:
```suggestion
Verify that `AvailabilityNotificationSubscriptionCustomerTransferExpanderPlugin` works:
```

2023-02-21 09:16 UTC, VadymSachenko requested changes
See my comments please

2023-02-21 09:16 UTC, VadymSachenko commented on _includes/pbc/all/install-features/202304.0/install-the-availability-notification-feature.md
> +#### Listening to the availability_notification event
Rewrite the title. It should be a task-based heading and start with a bare infinitive. For example:
```suggestion
#### Configure listening to the availability_notification event
```

2023-02-21 09:16 UTC, VadymSachenko commented on _includes/pbc/all/install-features/202304.0/install-the-availability-notification-feature.md
> +#### Email handling
The same. Rephrase it. For example:
```suggestion
#### Configure email handling
```

2023-02-21 09:16 UTC, VadymSachenko commented on _includes/pbc/all/install-features/202304.0/install-the-availability-notification-feature.md
> +#### Customer behavior
the same. Rephrase it. For example:
```suggestion
#### Configure customer behavior
```

2023-02-21 09:23 UTC, VadymSachenko approved these changes

2023-02-21 13:27 UTC, merged