Updating BazaarVoice integrante and configure docs
spryker/spryker-docs pull request #1641
Opened 2023-02-22 16:49 UTC by brunoviana-spryker

## PR Description

Changing the Integrante and Configure pages for BazaarVoice adding information regarding feature that sends products reviews over sFTP.

## Checklist
- [x] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2023-02-23 08:00 UTC, jeremyfourna requested changes
Left some comments to fix.

2023-02-23 08:00 UTC, jeremyfourna commented on docs/pbc/all/ratings-reviews/202212.0/third-party-integrations/integrate-bazaarvoice.md
> +#### Update OMS schema (Marketplace only)
Why is it only for marketplace? This is normally something that all projects must do.

2023-02-23 12:37 UTC, jeremyfourna approved these changes

2023-03-01 19:47 UTC, lenadoc commented on docs/pbc/all/ratings-reviews/202212.0/third-party-integrations/configure-bazaarvoice.md
> +8. In **sFTP Settings** fill out BazaarVoice's SFTP credentials if you want to track whether the products that have more UGC have a better conversion rate than products without many ratings and revie
@jeremyfourna isn't there **Settings > Select Services** anymore? Where can I check the new Configuration page for Bazaarvoice?

2023-03-03 09:47 UTC, merged