docs: Getting started documentation
spryker/spryker-docs pull request #1747
Opened 2023-04-04 19:35 UTC by tobi-or-not-tobi

Provides a high-level understanding of Oryx. 
As soon as more documentation is added, we can link from here. 

closes [HRZ-2144](https://spryker.atlassian.net/browse/HRZ-2144)

2023-04-07 07:34 UTC, andriitserkovnyi commented on _drafts/oryx/getting-started.md
> +- **Component Driven** – Oryx is component centric and uses are based on web components
What is `uses` in this component?

2023-04-07 07:52 UTC, tobi-or-not-tobi commented on _drafts/oryx/getting-started.md
> +- **Component Driven** – Oryx is component centric and uses are based on web components
badly written, I've rephrased.

2023-04-12 11:35 UTC, jmartinspryker requested changes
Submitted changes to oryx overview statement

2023-04-12 14:52 UTC, jmartinspryker requested changes

2023-04-13 06:55 UTC, andriitserkovnyi commented on _drafts/oryx/getting-started-with-oryx.md
> +Oryx is a framework for building composable frontends, providing a rich library of components and a design system. The components integrate with Spryker APIs by default, providing a seamless experien
How about this?

```suggestion
Oryx is a framework that empowers developers to build composable frontends with ease. It provides a rich library of components and a design system, which let developers create modern and visually appealing user interfaces. The components integrate with Spryker APIs by default, providing a seamless experience for developers.
```

2023-04-13 06:57 UTC, tobi-or-not-tobi commented on _drafts/oryx/getting-started-with-oryx.md
> +Oryx is a framework for building composable frontends, providing a rich library of components and a design system. The components integrate with Spryker APIs by default, providing a seamless experien
what about:
> a rich library of components including a design system,

2023-04-13 07:19 UTC, andriitserkovnyi commented on _drafts/oryx/getting-started-with-oryx.md
> +Oryx is a framework for building composable frontends, providing a rich library of components and a design system. The components integrate with Spryker APIs by default, providing a seamless experien
Isn't it the other way around?

2023-04-13 08:16 UTC, tobi-or-not-tobi commented on _drafts/oryx/getting-started-with-oryx.md
> +Oryx is a framework for building composable frontends, providing a rich library of components and a design system. The components integrate with Spryker APIs by default, providing a seamless experien
no, there's a lot of components, and parts of it are design system components. 

For example, we have "domain" components (eg "add to cart") that are using design system components (eg a button).

2023-04-13 14:44 UTC, jmartinspryker approved these changes

2023-04-19 09:24 UTC, VadymSachenko commented on _drafts/oryx/getting-started-with-oryx.md
> +Oryx is a framework that empowers developers to build composable frontends with ease. It provides a rich library of components including a design system, which let developers create modern and visual
```suggestion
Oryx is a framework that empowers developers to build composable frontends with ease. It provides a rich library of components, including a design system, which lets developers create modern and visually appealing user interfaces. The components integrate with Spryker APIs by default, providing a seamless experience for developers.
```

2023-04-19 12:14 UTC, VadymSachenko approved these changes

2023-04-21 07:31 UTC, merged