Re-review of the four docs
spryker/spryker-docs pull request #1756
Opened 2023-04-06 12:26 UTC by AlexSlawinski

## PR Description

TBD

## Checklist
- [x] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2023-04-11 09:38 UTC, lenadoc commented on docs/scos/dev/guidelines/keeping-a-project-upgradable/supported-extension-scenarios/event-subscribers-registration.md
>  Manifests fully support the registration of event subscribers in the collection. Restrictions to the order of the plugins in collection are **not supported**. New plugin will be added to the end of t
use italic to dray attention to smth: https://developers.google.com/style/text-formatting

2023-04-13 05:15 UTC, AlexSlawinski commented on docs/scos/dev/guidelines/keeping-a-project-upgradable/supported-extension-scenarios/event-subscribers-registration.md
>  Manifests fully support the registration of event subscribers in the collection. Restrictions to the order of the plugins in collection are **not supported**. New plugin will be added to the end of t
```suggestion
Manifests fully support the registration of event subscribers in the collection. Restrictions to the order of the plugins in collection are *not supported*. New plugin will be added to the end of the collection.
```

2023-04-13 05:15 UTC, AlexSlawinski commented on docs/scos/dev/guidelines/keeping-a-project-upgradable/supported-extension-scenarios/modules-configuration.md
>  Manifest only add values to configuration files. Manifests **will not remove** values from project configuration.
```suggestion
Manifest only add values to configuration files. Manifests *will not remove* values from project configuration. 
```

2023-04-13 05:15 UTC, AlexSlawinski commented on docs/scos/dev/guidelines/keeping-a-project-upgradable/supported-extension-scenarios/modules-configuration.md
>  Multidimensional associative arrays are supported up to 2 levels, but for its usage the wrapped functions **must** be used:
```suggestion
Multidimensional associative arrays are supported up to 2 levels, but for its usage the wrapped functions *must* be used: 
```

2023-04-13 05:15 UTC, AlexSlawinski commented on docs/scos/dev/guidelines/keeping-a-project-upgradable/supported-extension-scenarios/modules-configuration.md
>  Multidimensional arrays (up to 2 levels) are also supported here, but to use them the wrapped function **must** be used.
```suggestion
Multidimensional arrays (up to 2 levels) are also supported here, but to use them the wrapped function *must* be used.
```

2023-04-13 05:15 UTC, AlexSlawinski commented on docs/scos/dev/guidelines/keeping-a-project-upgradable/supported-extension-scenarios/plugins-registration.md
> +Manifests have limited support of multidimensional array. Oonly arrays that are added through the key are supported. only multidimensional arrays with up to 2 levels of depth are supported. It means
```suggestion
Manifests have limited support of multidimensional array. Oonly arrays that are added through the key are supported. only multidimensional arrays with up to 2 levels of depth are supported. It means that structures like the following *will not be supported*: 
```

2023-04-13 05:15 UTC, AlexSlawinski commented on docs/scos/dev/guidelines/keeping-a-project-upgradable/supported-extension-scenarios/plugins-registration.md
> +Manifests fully support the possibility of adding plugins through container extension. Order of the plugins is **not supported** inside of the container extension. It means that before and after are
```suggestion
Manifests fully support the possibility of adding plugins through container extension. Order of the plugins is *not supported* inside of the container extension. It means that before and after are *not supported* in this case.
```

2023-04-13 05:22 UTC, AlexSlawinski commented on docs/scos/dev/guidelines/keeping-a-project-upgradable/supported-extension-scenarios/modules-configuration.md
> +[Manifests](/docs/scos/dev/guidelines/keeping-a-project-upgradable/keeping-a-project-upgradable.html#follow-the-upgradability-best-practices) support changes in a module's configuration files.
```suggestion
This document explains how manifests support changes in the configuration files of modules. [Manifests](/docs/scos/dev/guidelines/keeping-a-project-upgradable/keeping-a-project-upgradable.html#follow-the-upgradability-best-practices) support changes in a module's configuration files.
```

2023-04-13 05:27 UTC, AlexSlawinski commented on docs/scos/dev/guidelines/keeping-a-project-upgradable/supported-extension-scenarios/modules-configuration.md
> +There's a multitude of ways to view arrays as the return.
```suggestion
There's a multitude of ways to view arrays as the return. Manifests support the following array types:
```

2023-04-13 05:36 UTC, AlexSlawinski commented on docs/scos/dev/guidelines/keeping-a-project-upgradable/supported-extension-scenarios/plugins-registration.md
> +Manifests have limited support of multidimensional array. Oonly arrays that are added through the key are supported. only multidimensional arrays with up to 2 levels of depth are supported. It means
```suggestion
Manifests have limited support of multidimensional array. Only arrays that are added through the key are supported. only multidimensional arrays with up to 2 levels of depth are supported. It means that structures like the following *will not be supported*: 
```

2023-04-13 05:36 UTC, AlexSlawinski commented on docs/scos/dev/guidelines/keeping-a-project-upgradable/supported-extension-scenarios/plugins-registration.md
> +For ingle plugin registration with the wrap method call, use the following:
```suggestion
For single plugin registration with the wrap method call, use the following:
```

2023-04-13 05:37 UTC, AlexSlawinski commented on docs/scos/dev/guidelines/keeping-a-project-upgradable/supported-extension-scenarios/plugins-registration.md
> +Manifests support plugins registration in the dependency provider and plugins registration in the configuration files. There are multiple ways how plugins can be registered inside of the project.
I understand what to do above in fixing examples, but how should these ones be adjusted / fixed? There's no bullet point list in this document specifically

2023-04-13 11:58 UTC, lenadoc commented on docs/scos/dev/guidelines/keeping-a-project-upgradable/supported-extension-scenarios/plugins-registration.md
> +Manifests support plugins registration in the dependency provider and plugins registration in the configuration files. There are multiple ways how plugins can be registered inside of the project.
That means you should rephrase writing like "For plugin registration, do the following", as this is not quite correct. These are the examples and not quite how exactly you should act

2023-05-04 14:47 UTC, lenadoc requested changes

2023-05-04 14:47 UTC, lenadoc commented on docs/scos/dev/guidelines/keeping-a-project-upgradable/supported-extension-scenarios/event-subscribers-registration.md
> +Manifests fully support the registration of event subscribers in the collection. Restrictions to the order of the plugins in collection are *not supported*. New plugin will be added to the end of the
```suggestion
Manifests fully support the registration of event subscribers in the collection. Restrictions to the order of the plugins in collection are *not supported*. New plugin is added to the end of the collection.
```

2023-05-04 14:47 UTC, lenadoc commented on docs/scos/dev/guidelines/keeping-a-project-upgradable/supported-extension-scenarios/modules-configuration.md
> +This document explains how manifests support changes in the configuration files of modules. [Manifests](/docs/scos/dev/guidelines/keeping-a-project-upgradable/keeping-a-project-upgradable.html#follow
```suggestion
This document explains how manifests support changes in the configuration files of modules.
```

2023-05-04 14:47 UTC, lenadoc commented on docs/scos/dev/guidelines/keeping-a-project-upgradable/supported-extension-scenarios/modules-configuration.md
> +Manifest only add values to configuration files. Manifests *will not remove* values from project configuration.
```suggestion
Manifest only add values to configuration files. Manifests *don't remove* values from project configuration. 
```

Future tense should be avoided when possible https://developers.google.com/style/tense

2023-05-04 14:47 UTC, lenadoc commented on docs/scos/dev/guidelines/keeping-a-project-upgradable/supported-extension-scenarios/modules-configuration.md
> +There's a multitude of ways to view arrays as the return. Manifests support the following array types:
Please consider still leaving the title "Array as a return", as the sentence "There's a multitude of ways to view arrays as the return. Manifests support the following array types:" looks very torn away from the previous section

2023-05-04 14:47 UTC, lenadoc commented on docs/scos/dev/guidelines/keeping-a-project-upgradable/supported-extension-scenarios/modules-configuration.md
> +Multidimensional associative arrays are supported up to 2 levels, but for its usage the wrapped functions *must* be used:
```suggestion
Multidimensional associative arrays are supported up to two levels, but for its usage the wrapped functions *must* be used: 
```
https://developers.google.com/style/numbers#numbers-as-words

2023-05-04 14:47 UTC, lenadoc commented on docs/scos/dev/guidelines/keeping-a-project-upgradable/supported-extension-scenarios/modules-configuration.md
> +* multidimensional arrays
consider deleting this line

2023-05-04 14:47 UTC, lenadoc commented on docs/scos/dev/guidelines/keeping-a-project-upgradable/supported-extension-scenarios/modules-configuration.md
> +Multidimensional arrays (up to 2 levels) are also supported here, but to use them the wrapped function *must* be used.
```suggestion
multidimensional arrays of up to two levels are also supported, but to use them, you must use the wrapped function.
```

2023-05-04 14:47 UTC, lenadoc commented on docs/scos/dev/guidelines/keeping-a-project-upgradable/supported-extension-scenarios/plugins-registration.md
> +Restrictions on the order of the plugins can be done with special annotation keys ‘before' and ‘after’.
```suggestion
Restrictions on the order of the plugins can be done with special annotation keys `before` and `after`. 
```

2023-05-04 14:47 UTC, lenadoc commented on docs/scos/dev/guidelines/keeping-a-project-upgradable/supported-extension-scenarios/plugins-registration.md
>  If the plugin doesn’t contain any of these keys, it will be added to the end of the plugin stack.
```suggestion
If the plugin doesn’t contain any of these keys, it is added to the end of the plugin stack.
```

2023-05-04 14:47 UTC, lenadoc commented on docs/scos/dev/guidelines/keeping-a-project-upgradable/supported-extension-scenarios/plugins-registration.md
>  If the plugin contains the ‘after' key and defined plugins in ‘after’ parameter don’t exist on the project side, the plugin will be added to the end of the plugin stack.
```suggestion
If the plugin contains the `after` key and defined plugins in the `after` parameter don’t exist on the project side, the plugin is added to the end of the plugin stack.
```

2023-05-04 14:47 UTC, lenadoc commented on docs/scos/dev/guidelines/keeping-a-project-upgradable/supported-extension-scenarios/plugins-registration.md
>  If the plugin contains the ‘before' key and defined plugins in ‘before’ parameter don’t exist on the project side, the plugin will be added as the first plugin in plugin stack.
```suggestion
If the plugin contains the `before` key and defined plugins in the `before` parameter don’t exist on the project side, the plugin is added as the first plugin in plugin stack.
```

2023-05-04 14:47 UTC, lenadoc commented on docs/scos/dev/guidelines/keeping-a-project-upgradable/supported-extension-scenarios/plugins-registration.md
>  Manifests fully support multiple plugins registration in associative array. As a key you can use:
```suggestion
Manifests fully support multiple plugins registration in an associative array. As a key, you can use:
```

2023-05-04 14:47 UTC, lenadoc commented on docs/scos/dev/guidelines/keeping-a-project-upgradable/supported-extension-scenarios/plugins-registration.md
> +Manifests have limited support of multidimensional array. Only arrays that are added through the key are supported. only multidimensional arrays with up to 2 levels of depth are supported. It means t
```suggestion
Manifests have limited support of a multidimensional array. Only arrays that are added through the key are supported. Also, only multidimensional arrays with up to 2 levels of depth are supported. It means that structures like the following are *not supported*: 
```

2023-05-04 14:47 UTC, lenadoc commented on docs/scos/dev/guidelines/keeping-a-project-upgradable/supported-extension-scenarios/plugins-registration.md
>  Multidimensional associative arrays are supported inside of the array_merge() up to 2 levels, but for its usage the wrapped functions MUST be used.
```suggestion
Multidimensional associative arrays are supported inside of the `array_merge()` up to two levels, but to use them, you must use the wrapped functions.
```

2023-05-04 14:47 UTC, lenadoc commented on docs/scos/dev/guidelines/keeping-a-project-upgradable/supported-extension-scenarios/plugins-registration.md
>  * If the target dependency provider class doesn’t exist in the project, it will be created and all required methods will be created automatically as well.
Please replace the future tense with present in this whole section

2023-05-07 15:04 UTC, lenadoc commented on docs/scos/dev/guidelines/keeping-a-project-upgradable/supported-extension-scenarios/modules-configuration.md
> +Multidimensional associative arrays are supported up to two levels, but for its usage the wrapped functions *must* be used:
their usage?

2023-05-07 15:05 UTC, lenadoc approved these changes

2023-05-07 15:05 UTC, lenadoc submitted a review, later dismissed

2023-05-09 08:22 UTC, AlexSlawinski commented on docs/scos/dev/guidelines/keeping-a-project-upgradable/supported-extension-scenarios/modules-configuration.md
> +Multidimensional associative arrays are supported up to two levels, but for its usage the wrapped functions *must* be used:
```suggestion
Multidimensional associative arrays are supported up to two levels, but for their usage the wrapped functions *must* be used: 
```

2023-05-09 14:54 UTC, lenadoc approved these changes

2023-05-24 07:55 UTC, merged