EVM
spryker/spryker-docs pull request #1833
Opened 2023-05-05 14:00 UTC by andriitserkovnyi

## PR Description

Docs for the EVM feature

## Checklist
- [x] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2023-05-08 16:19 UTC, hatemzidi-pro reviewed
overall good for me.

2023-05-10 07:52 UTC, VadymSachenko requested changes

2023-05-10 07:52 UTC, VadymSachenko commented on docs/cloud/dev/spryker-cloud-commerce-os/add-variables.md
> +* /fashion_club_store/staging/config/common/limited/composer_pass
```suggestion
* `/fashion_club_store/staging/config/common/limited/composer_pass`
```

2023-05-10 07:52 UTC, VadymSachenko commented on docs/cloud/dev/spryker-cloud-commerce-os/add-variables.md
> +* /deans_jeans/prod/config/app/public/mail_host
```suggestion
* `/deans_jeans/prod/config/app/public/mail_host`
```

2023-05-10 07:52 UTC, VadymSachenko commented on docs/cloud/dev/spryker-cloud-commerce-os/add-variables.md
> +The following variables are arranged from lower to higher priority:
Shouldn't lines 51-73 be formatted as code font?

2023-05-10 07:52 UTC, VadymSachenko commented on docs/cloud/dev/spryker-cloud-commerce-os/add-variables.md
> +To make variables available in your Jenkins instance, we need to terraform your added or changed variables. To do this, create a [support case](https://docs.spryker.com/docs/scos/user/intro-to-spryke
```suggestion
To make variables available in your Jenkins instance, we need to terraform your added or changed variables. To do this, create a [support case](/docs/scos/user/intro-to-spryker/support/how-to-use-the-support-portal.html#plattform-change-requests).
```

2023-05-10 07:52 UTC, VadymSachenko commented on docs/cloud/dev/spryker-cloud-commerce-os/add-variables.md
> +1. In the AWS Management Console, go to **Services > Parameter Store**.
```suggestion
1. In the AWS Management Console, go to **Services&nbsp;<span aria-label="and then">></span> Parameter Store**.
```

2023-05-10 07:52 UTC, VadymSachenko commented on docs/cloud/dev/spryker-cloud-commerce-os/add-variables.md
> +4. Optional: Enter a **Description**.
According to google style guide, this should be rephrased to something like (see https://developers.google.com/style/ui-elements#refer-to-ui-elements):
```suggestion
4. Optional: For **Description**, enter the description of the variable.
```

2023-05-10 07:52 UTC, VadymSachenko commented on docs/cloud/dev/spryker-cloud-commerce-os/add-variables.md
> +5. Select a **Type** based on your requirements.
same: requires rephrasing

2023-05-10 07:52 UTC, VadymSachenko commented on docs/cloud/dev/spryker-cloud-commerce-os/add-variables.md
> +6. Enter a **Value**.
same: consider rephrasing

2023-05-10 07:52 UTC, VadymSachenko commented on docs/cloud/dev/spryker-cloud-commerce-os/add-variables.md
> +8. Go to **Services** > **CodePipeline**.
```suggestion
8. Go to **Services**&nbsp;<span aria-label="and then">></span> **CodePipeline**.
```

2023-05-10 07:52 UTC, VadymSachenko commented on docs/cloud/dev/spryker-cloud-commerce-os/add-variables.md
> +8. Go to **Services** > **CodePipeline**.
```suggestion
8. Go to **Services**&nbsp;<span aria-label="and then">></span> **CodePipeline**.
```

2023-05-10 07:52 UTC, VadymSachenko commented on docs/cloud/dev/spryker-cloud-commerce-os/add-variables.md
> +1. In the AWS Management Console, go to **Services > Parameter Store**.
```suggestion
1. In the AWS Management Console, go to **Services&nbsp;<span aria-label="and then">></span> Parameter Store**.
```

2023-05-10 07:52 UTC, VadymSachenko commented on docs/cloud/dev/spryker-cloud-commerce-os/add-variables.md
> +1. In the AWS Management Console, go to **Services > Parameter Store**.
```suggestion
1. In the AWS Management Console, go to **Services&nbsp;<span aria-label="and then">></span> Parameter Store**.
```

2023-05-10 07:52 UTC, VadymSachenko commented on docs/cloud/dev/spryker-cloud-commerce-os/add-variables.md
> +8. Go to **Services** > **CodePipeline**.
```suggestion
8. Go to **Services**&nbsp;<span aria-label="and then">></span> **CodePipeline**.
```

2023-05-10 07:52 UTC, VadymSachenko commented on docs/cloud/dev/spryker-cloud-commerce-os/add-variables.md
> +1. In the AWS Management Console, go to **Services > Parameter Store**.
```suggestion
1. In the AWS Management Console, go to **Services&nbsp;<span aria-label="and then">></span> Parameter Store**.
```

2023-05-10 07:52 UTC, VadymSachenko commented on docs/cloud/dev/spryker-cloud-commerce-os/add-variables.md
> +8. Go to **Services** > **CodePipeline**.
```suggestion
8. Go to **Services&nbsp;<span aria-label="and then">></span> CodePipeline**.
```

2023-05-10 07:52 UTC, VadymSachenko commented on docs/cloud/dev/spryker-cloud-commerce-os/add-variables.md
> +1. For any `type` and `bucket`, the priority is `public` > `limited` > `internal`.
consider adding `&nbsp;<span aria-label="and then">></span>`

2023-05-10 07:52 UTC, VadymSachenko commented on docs/cloud/dev/spryker-cloud-commerce-os/add-variables.md
> +2. Foy any `bucket`, the priority is `bucket` > `common`.
consider adding `&nbsp;<span aria-label="and then">></span>`

2023-05-10 07:52 UTC, VadymSachenko commented on docs/cloud/dev/spryker-cloud-commerce-os/add-variables.md
> +1. In the AWS Management Console, go to **Services > Parameter Store**.
```suggestion
1. In the AWS Management Console, go to **Services&nbsp;<span aria-label="and then">></span> Parameter Store**.
```

2023-05-10 07:52 UTC, VadymSachenko commented on docs/cloud/dev/spryker-cloud-commerce-os/add-variables.md
> +4. Optional: Enter a **Description**.
same: consider rephrasing

2023-05-10 07:52 UTC, VadymSachenko commented on docs/cloud/dev/spryker-cloud-commerce-os/add-variables.md
> +8. Go to **Services** > **CodePipeline**.
```suggestion
8. Go to **Services&nbsp;<span aria-label="and then">></span> CodePipeline**.
```

2023-05-10 07:52 UTC, VadymSachenko commented on docs/cloud/dev/spryker-cloud-commerce-os/add-variables.md
> +4. Optional: Enter a **Description**.
same: consider rephrasing

2023-05-10 07:52 UTC, VadymSachenko commented on docs/cloud/dev/spryker-cloud-commerce-os/add-variables.md
> +5. Select a **Type** based on your requirements.
same: consider rephrasing

2023-05-10 07:52 UTC, VadymSachenko commented on docs/cloud/dev/spryker-cloud-commerce-os/add-variables.md
> +6. Enter a **Value**.
same: consider rephrasing

2023-05-10 07:52 UTC, VadymSachenko commented on docs/cloud/dev/spryker-cloud-commerce-os/add-variables.md
> +8. Go to **Services** > **CodePipeline**.
```suggestion
8. Go to **Services&nbsp;<span aria-label="and then">></span> CodePipeline**.
```

2023-05-10 07:52 UTC, VadymSachenko commented on docs/cloud/dev/spryker-cloud-commerce-os/add-variables.md
> +6. Enter a **Value**.
same: consider rephrasing

2023-05-10 07:52 UTC, VadymSachenko commented on docs/cloud/dev/spryker-cloud-commerce-os/add-variables.md
> +4. Optional: Enter a **Description**.
same: consider rephrasing

2023-05-10 07:52 UTC, VadymSachenko commented on docs/cloud/dev/spryker-cloud-commerce-os/add-variables.md
> +6. Enter a **Value**.
same: consider rephrasing

2023-05-10 07:52 UTC, VadymSachenko commented on docs/cloud/dev/spryker-cloud-commerce-os/add-variables.md
> +6. Enter a **Value**.
same: consider rephrasing

2023-05-10 08:20 UTC, VadymSachenko submitted a review, later dismissed

2023-05-10 09:44 UTC, VadymSachenko approved these changes

2023-05-10 11:39 UTC, merged