Add data import documents
spryker/spryker-docs pull request #1865
Opened 2023-05-23 12:15 UTC by VadymSachenko

## PR Description
This PR adds new data import documents.
Jira task: https://spryker.atlassian.net/browse/CC-25233
TBD

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2023-05-23 12:15 UTC, VadymSachenko commented on _drafts/data-import/202309.0/file-details-shipment-method-store.csv.md
> +[TODO: verify dependencies and add missing ones; if no dependencies, remove the section]
Resolve TODO

2023-05-25 08:01 UTC, AsonUnique approved these changes

2023-05-25 09:39 UTC, VadymSachenko commented on docs/pbc/all/carrier-management/202304.0/base-shop/import-and-export-data/file-details-shipment-method-shipment-type.csv.md
> +[`shipment.csv`](/docs/pbc/all/carrier-management/{{page.version}}/base-shop/import-and-export-data/file-details-shipment.csv.html)
```suggestion
* [`shipment.csv`](/docs/pbc/all/carrier-management/{{page.version}}/base-shop/import-and-export-data/file-details-shipment.csv.html)
```

2023-05-25 09:39 UTC, VadymSachenko commented on docs/pbc/all/carrier-management/202304.0/base-shop/import-and-export-data/file-details-shipment-method-shipment-type.csv.md
> +[`shipment-type.csv`](/docs/pbc/all/carrier-management/{{page.version}}/base-shop/import-and-export-data/file-details-shipment-type.csv.html)
```suggestion
* [`shipment-type.csv`](/docs/pbc/all/carrier-management/{{page.version}}/base-shop/import-and-export-data/file-details-shipment-type.csv.html)
```

2023-05-30 07:42 UTC, andriispryker submitted a review, later dismissed
Approved.

2023-05-30 10:39 UTC, lenadoc requested changes

2023-05-30 10:39 UTC, lenadoc commented on docs/pbc/all/carrier-management/202304.0/base-shop/import-and-export-data/file-details-shipment-method-shipment-type.csv.md
> +description: This document describes the shipment_method_shipment_type.csv file to configure the Shipment information in your Spryker Demo Shop.
```suggestion
description: This document describes the shipment_method_shipment_type.csv file to configure the shipment information in your Spryker Demo Shop.
```

2023-05-30 10:39 UTC, lenadoc commented on docs/pbc/all/carrier-management/202304.0/base-shop/import-and-export-data/file-details-shipment-type-store.csv.md
> +description: This document describes the shipment_type_store.csv file to configure the Shipment information in your Spryker Demo Shop.
```suggestion
description: This document describes the shipment_type_store.csv file to configure the shipment information in your Spryker Demo Shop.
```

2023-05-30 10:39 UTC, lenadoc commented on docs/pbc/all/carrier-management/202304.0/base-shop/import-and-export-data/file-details-shipment-type.csv.md
> +description: This document describes the shipment_type.csv file to configure the Shipment information in your Spryker Demo Shop.
```suggestion
description: This document describes the shipment_type.csv file to configure the shipment information in your Spryker Demo Shop.
```

2023-05-30 10:57 UTC, lenadoc approved these changes

2023-06-01 12:03 UTC, lenadoc approved these changes

2023-06-01 14:02 UTC, merged