Install the Service Points feature
spryker/spryker-docs pull request #1906
Opened 2023-06-06 11:07 UTC by artem-png

## PR Description

Ticket: https://spryker.atlassian.net/browse/CC-24931

2023-06-07 13:25 UTC, kkicheglovspryker reviewed
You need to wait until https://github.com/spryker/spryker-docs/pull/1905 will be merged and resolve conflicts

2023-06-07 15:00 UTC, kkicheglovspryker submitted a review, later dismissed

2023-06-08 14:42 UTC, DmitryLymarenko requested changes

2023-06-08 14:42 UTC, DmitryLymarenko commented on _includes/pbc/all/install-features/202304.0/install-the-service-points-feature.md
> +service_key,product_offer_reference
needs to be updated according to columns order exchange

2023-06-08 14:42 UTC, DmitryLymarenko commented on _includes/pbc/all/install-features/202304.0/install-the-service-points-feature.md
> +2. To expand product offers with services, register the plugins:
it looks like paragraph `### 7)` starts from `2.`
where is `1.`?

2023-06-08 14:59 UTC, DmitryLymarenko approved these changes

2023-06-09 07:51 UTC, andriispryker approved these changes
Approved.

2023-06-19 09:43 UTC, VadymSachenko approved these changes

2023-06-19 10:52 UTC, merged