Docs style guide
spryker/spryker-docs pull request #1913
Opened 2023-06-09 07:38 UTC by andriitserkovnyi

## PR Description

Add guidance for style

## Checklist
- [x] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2023-06-09 09:05 UTC, lenadoc requested changes

2023-06-09 09:05 UTC, lenadoc commented on docs/scos/user/intro-to-spryker/contribute-to-the-documentation/spryker-documentation-style-guide/spryker-documentation-style-guide.md
> +Spryker is a rapidly evolving product, as well as its documentation. If it makes sense to not follow the guides, go for it. Consider if your approach is better only in your  particular case or for th
```suggestion
Spryker is a rapidly evolving product, as well as its documentation. If it makes sense to not follow the guides, go for it. Consider if your approach is better only in your particular case or for the entire documentation. Edit existing and add new guidance to this style guide.
```

2023-06-13 07:44 UTC, VadymSachenko commented on docs/scos/user/intro-to-spryker/contribute-to-the-documentation/spryker-documentation-style-guide/examples.md
> +| Guidance | Recommended | Not recommended |
We use upper case for table headers
```suggestion
| GUIDENCE | RECOMMENDED | NOT RECOMMENDED |
```

2023-06-13 07:45 UTC, VadymSachenko commented on docs/scos/user/intro-to-spryker/contribute-to-the-documentation/spryker-documentation-style-guide/spryker-documentation-style-guide.md
> +1. Spryker documentation style guide
Do you know where I can read this one?

2023-06-14 07:54 UTC, andriitserkovnyi commented on docs/scos/user/intro-to-spryker/contribute-to-the-documentation/spryker-documentation-style-guide/spryker-documentation-style-guide.md
> +1. Spryker documentation style guide
Here :)

2023-06-14 10:49 UTC, VadymSachenko approved these changes

2023-06-19 07:46 UTC, AlexSlawinski approved these changes

2023-06-19 08:32 UTC, AlexSlawinski approved these changes

2023-06-19 14:44 UTC, lenadoc approved these changes

2023-06-20 07:11 UTC, merged