Moving miscellaneous odcs
spryker/spryker-docs pull request #1932
Opened 2023-06-20 08:24 UTC by andriitserkovnyi

## PR Description

Moving the docs that are not part of any PBC, part 2

## Checklist
- [x] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2023-06-27 13:20 UTC, lenadoc requested changes

2023-06-27 13:20 UTC, lenadoc commented on _drafts/deprecated-after-pbc-migration/marketplace-infrastructure-requirements.md
please add a redirect from this page

2023-06-27 13:34 UTC, andriitserkovnyi commented on _drafts/deprecated-after-pbc-migration/marketplace-infrastructure-requirements.md
It's there: https://github.com/spryker/spryker-docs/pull/1932/files#diff-2c1d9c1e41e5fd65dddf7283821c62efff2e0b985e8fe8dd0469bcbf15fcc9c9

2023-06-29 08:45 UTC, lenadoc approved these changes

2023-06-29 08:45 UTC, merged