FRW-1610 Adjusted docs
spryker/spryker-docs pull request #1940
Opened 2023-06-22 11:21 UTC by dimitriyTsemma

Ticket: https://spryker.atlassian.net/browse/FRW-1613

2023-06-23 16:35 UTC, asmarovydlo requested changes

2023-06-23 16:35 UTC, asmarovydlo commented on _includes/pbc/all/install-features/202304.0/install-glue-api/install-the-dynamic-store-glue-api.md
> +            new StoresApplicationPlugin(),
Plugin name change requested in PR, please rename it here accordingly.

2023-06-23 16:35 UTC, asmarovydlo commented on _includes/pbc/all/install-features/202304.0/install-glue-api/install-the-dynamic-store-glue-api.md
> +            new StoresApplicationPlugin(),
Plugin name change requested in PR, please rename it here accordingly.

2023-06-23 16:35 UTC, asmarovydlo commented on _includes/pbc/all/install-features/202304.0/install-glue-api/install-the-dynamic-store-glue-api.md
> +| StoreHttpHeaderApplicationPlugin | Gets store name from the Request parameter or Request header used for Glue Application. If both defined Request parameter has more priority. - | None | Spryker\Gl
Please add a warning that `StoresRestApi` is deprecated, and we need to use `StoresApi` instead.

2023-06-26 10:31 UTC, asmarovydlo requested changes

2023-06-26 10:31 UTC, asmarovydlo commented on _includes/pbc/all/install-features/202304.0/install-glue-api/install-the-dynamic-store-glue-api.md
> +use Spryker\Glue\StoresBackendApi\Plugin\Application\StoreApplicationPlugin;
Please fix namespaces, to match the code in the PR after refactoring. (Same for SAPI)

2023-06-29 08:48 UTC, AlexSlawinski commented on _includes/pbc/all/install-features/202304.0/install-glue-api/install-the-dynamic-store-glue-api.md
> +| StoreHttpHeaderApplicationPlugin | Gets store name from the Request parameter or Request header used for Glue Application. If both defined Request parameter has more priority. - | None | Spryker\Gl
```suggestion
| StoreHttpHeaderApplicationPlugin | Gets the name of the store from the Request parameter or the Request header used for the Glue Application. If both are defined, the Request parameter has more priority. - | None | Spryker\Glue\StoresRestApi\Plugin\Application             |
```

2023-06-29 08:48 UTC, AlexSlawinski commented on _includes/pbc/all/install-features/202304.0/install-glue-api/install-the-dynamic-store-glue-api.md
> +| StoreApplicationPlugin | Gets store name from the Request parameter or Request header used for Storefront API. If both defined Request parameter has more priority. -   | None | Spryker\Glue\StoresA
```suggestion
| StoreApplicationPlugin | Gets the name of the store from the Request parameter or the Request header used for the Storefront API. If both are defined, the Request parameter has more priority. -   | None | Spryker\Glue\StoresApi\Plugin\GlueStorefrontApiApplication                 |
```

2023-06-29 08:48 UTC, AlexSlawinski commented on _includes/pbc/all/install-features/202304.0/install-glue-api/install-the-dynamic-store-glue-api.md
> +| StoreApplicationPlugin | Gets store name from the Request parameter or Request header used for Storefront API. If both defined Request parameter has more priority. -   | None | Spryker\Glue\StoresB
```suggestion
| StoreApplicationPlugin |  Gets the name of the store from the Request parameter or the Request header used for the Storefront API. If both are defined, the Request parameter has more priority. -   | None | Spryker\Glue\StoresBackendApi\Plugin\GlueBackendApiApplication          |
```

2023-06-29 08:48 UTC, AlexSlawinski commented on _includes/pbc/all/install-features/202304.0/install-glue-api/install-the-dynamic-store-glue-api.md
> +If everything is set up correctly, a request to `https://glue.mysprykershop.com` with the header `[{"key":"Accept-Language","value":"de_DE"},{"key":"Store","value":"DE"}]` or `https://glue.mysprykers
```suggestion
If everything is set up correctly, a request to `https://glue.mysprykershop.com` with the header `[{"key":"Accept-Language","value":"de_DE"},{"key":"Store","value":"DE"}]` or `https://glue.mysprykershop.com?_store=DE`  with the header `[{"key":"Accept-Language","value":"de_DE"}]` should result in a response without any errors and contain the `content-language` header set to **de_DE**.
```

2023-06-29 08:48 UTC, AlexSlawinski commented on _includes/pbc/all/install-features/202304.0/install-glue-api/install-the-dynamic-store-glue-api.md
> +If everything is set up correctly, a request to `https://glue-backend.mysprykershop.com` with the header `[{"key":"Accept-Language","value":"de_DE"},{"key":"Store","value":"DE"}]` or `https://glue.my
```suggestion
If everything is set up correctly, a request to `https://glue-backend.mysprykershop.com` with the header `[{"key":"Accept-Language","value":"de_DE"},{"key":"Store","value":"DE"}]` or `https://glue.mysprykershop.com?_store=DE`  with the header `[{"key":"Accept-Language","value":"de_DE"}]` should result in a response without any errors and contain the `content-language` header set to **de_DE**.
```

2023-06-29 08:48 UTC, AlexSlawinski commented on _includes/pbc/all/install-features/202304.0/install-glue-api/install-the-dynamic-store-glue-api.md
> +An example for testing with Store header:
```suggestion
An example for testing with a Store header: 
```

2023-06-29 08:48 UTC, AlexSlawinski commented on _includes/pbc/all/install-features/202304.0/install-glue-api/install-the-dynamic-store-glue-api.md
> +An example for testing with Store Request parameter:
```suggestion
An example for testing with a Store Request parameter:
```

2023-06-29 08:48 UTC, AlexSlawinski commented on _includes/pbc/all/install-features/202304.0/install-glue-api/install-the-dynamic-store-glue-api.md
> +If everything is set up correctly, a request to `https://glue-storefront.mysprykershop.com` with the header `[{"key":"Accept-Language","value":"de_DE"},{"key":"Store","value":"DE"}]` or `https://glue
```suggestion
If everything is set up correctly, a request to `https://glue-storefront.mysprykershop.com` with the header `[{"key":"Accept-Language","value":"de_DE"},{"key":"Store","value":"DE"}]` or `https://glue.mysprykershop.com?_store=DE`  with the header `[{"key":"Accept-Language","value":"de_DE"}]` should result in a response without any errors and contain the `content-language` header set to **de_DE**.
```

2023-06-29 09:14 UTC, merged