[WIP] FRW-1893: Dynamic Data Exchange API
spryker/spryker-docs pull request #1944
Opened 2023-06-22 16:10 UTC by olhalivitchuk

## PR Description

https://spryker.atlassian.net/browse/FRW-1893

- Introduced Integration Guide for Dynamic Data Exchange API.
- TODO: How-to set the configurations.
- TODO: How-to send requests and operate with the data. 

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2023-06-30 15:27 UTC, asmarovydlo requested changes

2023-06-30 15:27 UTC, asmarovydlo commented on docs/scos/dev/glue-api-guides/202304.0/dynamic-data-exchange-api/how-to-guides/how-to-send-request-in-dynamic-data-exchange-api.md
> +]
This is not the way how it should work.
All the readable fields should be returned in the response.
If the field is `isCreatable=false`, but it is provided in the request => 400 error should be returned, with a descriptive message.

2023-06-30 15:27 UTC, asmarovydlo commented on docs/scos/dev/glue-api-guides/202304.0/dynamic-data-exchange-api/how-to-guides/how-to-send-request-in-dynamic-data-exchange-api.md
> +However, if any of the fields are configured as `isEditable: false` it won't be updated.
If any of those fields are not editable, but we are trying to edit them, we should receive 400 response with a descriptive message.
Please verify the implementation, and update the documentation.

2023-06-30 15:27 UTC, asmarovydlo commented on docs/scos/dev/glue-api-guides/202304.0/dynamic-data-exchange-api/how-to-guides/how-to-send-request-in-dynamic-data-exchange-api.md
> +For example, modifying the ID of the entity or providing duplicate values for unique columns, etc will result in an error.
Please see the comment above, it should not result in an error.

2023-07-03 14:32 UTC, asmarovydlo requested changes

2023-07-03 14:32 UTC, asmarovydlo commented on docs/scos/dev/glue-api-guides/202304.0/dynamic-data-api/how-to-guides/how-to-configure-dynamic-data-api.md
> +}
https://github.com/spryker/spryker-docs/pull/1944#discussion_r1247915549 is not fixed.
The identifier field should also be defined in the `fields` array.

2023-07-03 14:32 UTC, asmarovydlo commented on docs/scos/dev/feature-integration-guides/202304.0/glue-api/dynamic-data-api/dynamic-data-api-integration.md
> +    ...
```suggestion
```

2023-07-03 14:32 UTC, asmarovydlo commented on docs/scos/dev/glue-api-guides/202304.0/dynamic-data-api/how-to-guides/how-to-configure-dynamic-data-api.md
> +string type instead.
1. It is applicable not only to identifiers but to any bigint columns.
2. It is not JSON related limitation, see https://www.w3schools.com/php/php_numbers.asp#:~:text=PHP%20Integers&text=An%20integer%20data%20type%20is,9223372036854775807%20in%2064%20bit%20systems. for 32b systems.

2023-07-03 14:32 UTC, asmarovydlo commented on docs/scos/dev/glue-api-guides/202304.0/dynamic-data-api/how-to-guides/how-to-send-request-in-dynamic-data-api.md
> +However, if any of the fields are configured as `isCreatable: false` it won't be created.
It is not always true: if it is `isCreatable: false`, but not required, the row will be created.

2023-07-03 14:32 UTC, asmarovydlo commented on docs/scos/dev/feature-integration-guides/202304.0/glue-api/dynamic-data-api/dynamic-data-api-integration.md
> +dynamic_entity.validation.required_data_is_missing_or_forbidden,"Einige erforderliche Daten fehlen oder die bereitgestellten Daten können nicht geändert werden. Bitte überprüfen Sie die Anfrage und v
Customers should be able based on the response modify(fix) the data they send, and make the request one more time.
This message is entirely unclear. Please fix it here, and in the implementation.

2023-07-05 17:42 UTC, asmarovydlo approved these changes

2023-07-07 08:04 UTC, AlexSlawinski commented on docs/scos/dev/glue-api-guides/202304.0/dynamic-data-api/how-to-guides/how-to-send-request-in-dynamic-data-api.md
> +Note, by default, API `GET` request returns up to 20 records.
```suggestion
Note, by default the API `GET` request returns up to 20 records.
```

2023-07-07 08:04 UTC, AlexSlawinski commented on docs/scos/dev/glue-api-guides/202304.0/dynamic-data-api/how-to-guides/how-to-send-request-in-dynamic-data-api.md
> +The response payload includes all the specified fields from the request body, along with the id of the newly created entity.
```suggestion
The response payload includes all the specified fields from the request body, along with the ID of the newly created entity.
```

2023-07-07 08:04 UTC, AlexSlawinski commented on docs/scos/dev/glue-api-guides/202304.0/dynamic-data-api/how-to-guides/how-to-send-request-in-dynamic-data-api.md
> +If the `id_country` is not provided you will get the following response:
```suggestion
If `id_country` is not provided you will get the following response:
```

2023-07-07 08:04 UTC, AlexSlawinski commented on docs/scos/dev/glue-api-guides/202304.0/dynamic-data-api/how-to-guides/how-to-send-request-in-dynamic-data-api.md
> +If the `id_country` is not found you will get the following response:
```suggestion
If `id_country` is not found you will get the following response:
```

2023-07-07 11:18 UTC, AlexSlawinski approved these changes

2023-07-17 08:19 UTC, AlexSlawinski approved these changes

2023-07-17 08:19 UTC, merged