Install the Service Points feature
spryker/spryker-docs pull request #1964
Opened 2023-07-04 10:33 UTC by romanhavrylko

Epic: https://spryker.atlassian.net/browse/CC-26569
Ticket: https://spryker.atlassian.net/browse/CC-28588

2023-07-05 12:35 UTC, DmitryLymarenko commented on _includes/pbc/all/install-features/202304.0/install-the-service-points-feature.md
> +| ProductOfferServicePointStorage    | vendor/spryker/product-offer-service-point-storage     |
this module is mapped to another feature
see https://release.spryker.com/features/view/145

2023-07-05 15:06 UTC, DmitryLymarenko submitted a review, later dismissed

2023-07-05 15:46 UTC, philinecao approved these changes

2023-07-06 10:01 UTC, VadymSachenko requested changes

2023-07-06 10:59 UTC, VadymSachenko commented on _includes/pbc/all/install-features/202304.0/install-the-product-offer-service-points-feature.md
> +| Product Offer  | {{site.version}} | [Product Offer feature integration](/docs/pbc/all/offer-management/{{site.version}}/marketplace/install-and-upgrade/install-features/install-the-marketplace-prod
```suggestion
| Product Offer  | {{site.version}} | [Product Offer feature integration](/docs/pbc/all/offer-management/{{page.version}}/marketplace/install-and-upgrade/install-features/install-the-marketplace-product-offer-feature.html) |
```

2023-07-06 11:09 UTC, VadymSachenko commented on _includes/pbc/all/install-features/202304.0/marketplace/install-the-marketplace-product-offer-service-points-feature.md
> +| Marketplace Product Offer    | {{page.version}} | [Marketplace Product Offer feature integration](spryker-docs/docs/pbc/all/offer-management/{{page.version}}/marketplace/install-and-upgrade/marketp
```suggestion
| Marketplace Product Offer    | {{page.version}} | [Marketplace Product Offer feature integration](/docs/pbc/all/offer-management/{{page.version}}/marketplace/install-and-upgrade/marketplace-product-offer-feature-integration.html) |
```

2023-07-06 11:10 UTC, VadymSachenko commented on _includes/pbc/all/install-features/202304.0/marketplace/install-the-marketplace-product-offer-service-points-feature.md
> +| Product Offer Service Points | {{page.version}} | [Product Offer Service Points feature integration](/docs/scos/dev/feature-integration-guides/{{page.version}}/install-the-product-offer-service-poi
```suggestion
| Product Offer + Service Points | {{page.version}} | [Install Product Offer + Service Points feature](/docs/scos/dev/feature-integration-guides/{{page.version}}/install-the-product-offer-service-points-feature.html)                            |
```

2023-07-06 11:21 UTC, VadymSachenko commented on _includes/pbc/all/install-features/202304.0/install-the-product-offer-service-points-feature.md
> +</details>
```suggestion
```

2023-07-06 11:21 UTC, VadymSachenko approved these changes

2023-07-10 12:49 UTC, merged