docs: Colors in Oryx
spryker/spryker-docs pull request #1985
Opened 2023-07-10 06:34 UTC by tobi-or-not-tobi

Documentation on colors in Oryx application.

2023-07-10 07:17 UTC, tolerants requested changes

2023-07-10 07:17 UTC, tolerants commented on docs/scos/dev/front-end-development/202212.0/oryx/styling/colors.md
> +The color palette contains all the colors provided by the [Radix color system](https://www.radix-ui.com/docs/colors/overview/installation), an open source colors system. Additionally, a "Spryker gree
Not sure installation is the best link to put here, maybe it's better to change this link to usage - https://www.radix-ui.com/docs/colors/overview/usage?

2023-07-10 07:17 UTC, tolerants commented on docs/scos/dev/front-end-development/202212.0/oryx/styling/colors.md
> +The color palette contains all the colors provided by the [Radix color system](https://www.radix-ui.com/docs/colors/overview/installation), an open source colors system. Additionally, a "Spryker gree
> Additionally, a "Spryker green" and "Spryker gray" is added.

Probably it's worth to add a small not why we added them.

2023-07-10 10:13 UTC, tolerants approved these changes

2023-07-11 12:47 UTC, VadymSachenko requested changes

2023-07-11 12:47 UTC, VadymSachenko commented on docs/scos/dev/front-end-development/202212.0/oryx/styling/colors.md
> +Creating fully accessible colors is not an easy task to do, which is why we've added a 3rd party open source library: [Radix](https://www.radix-ui.com/docs/colors/palette-composition/scales). Radix c
```suggestion
Creating fully accessible colors is not easy. Therefore, we added a 3rd party open-source library: [Radix](https://www.radix-ui.com/docs/colors/palette-composition/scales). Radix contains a wide range of colors and neutrals that can be configured in Oryx.
```

2023-07-11 12:47 UTC, VadymSachenko commented on docs/scos/dev/front-end-development/202212.0/oryx/styling/colors.md
> +Color contrast is an important accessibility feature. When colors do not have enough contrast, users with limited sight might not be able to use the experience to its full extend.
```suggestion
Color contrast is an important accessibility feature. When colors do not have enough contrast, users with limited sight might not be able to use the experience to its full extent.
```

2023-07-11 12:47 UTC, VadymSachenko commented on docs/scos/dev/front-end-development/202212.0/oryx/styling/colors.md
> +Colors can be provided for both light and dark mode. Dark mode is another important feature for accessibility and is supported by all colors in the color palette. Oryx applications can automatically
```suggestion
Colors can be provided for both light and dark modes. The dark mode is another important feature for accessibility and is supported by all colors in the color palette. Oryx applications can automatically adapt to the device mode as well, but there's also a `ColorModeSelectorComponent` that can be used to let the user manage the color mode manually.
```

2023-07-11 12:47 UTC, VadymSachenko commented on docs/scos/dev/front-end-development/202212.0/oryx/styling/colors.md
> +| Type      | Description
Table titles are always uppercase
```suggestion
| TYPE      | DESCRIPTION                                                                                                                                                                                                                                     |
```

2023-07-11 12:47 UTC, VadymSachenko commented on docs/scos/dev/front-end-development/202212.0/oryx/styling/colors.md
> +| Neutral   | Also known as "grays". The neutrals are used for the layout, for example as a divider color or background color. The Radix color system provides different neutrals that pair nicely with
```suggestion
| Neutral   | Also known as "grays". The neutrals are used for the layout—for example, as a divider color or background color. The Radix color system provides different neutrals that pair nicely with the color of choice, also known as "natural pairing". |
```

2023-07-11 12:47 UTC, VadymSachenko commented on docs/scos/dev/front-end-development/202212.0/oryx/styling/colors.md
> +| Success   | The success color is one of the `AlertType` color that is used in components that are driven by `AlertType` (e.g. Notification).
```suggestion
| Success   | The success color is one of the `AlertType` colors that is used in components that are driven by `AlertType`—for example, notification.                                                                                                                |
```

2023-07-11 12:47 UTC, VadymSachenko commented on docs/scos/dev/front-end-development/202212.0/oryx/styling/colors.md
> +The steps count from 0 - 12. In light mode, the steps goes from light to dark; the higher the number, the darker the color. In dark mode, this is reversed.
```suggestion
The steps count from 0-12. In light mode, the steps go from light to dark; the higher the number, the darker the color. In dark mode, this is reversed.
```

2023-07-11 12:47 UTC, VadymSachenko commented on docs/scos/dev/front-end-development/202212.0/oryx/styling/colors.md
> +The Radix color system provide 15 color scales that are designed with a white foreground text and 5 bright scales for black foreground text. The foreground color is provided by step 0. For the bright
```suggestion
The Radix color system provides 15 color scales that are designed with a white foreground text and 5 bright scales for black foreground text. The foreground color is provided by step 0. For the bright colors, this color is black, while for the other colors, this is white. In dark mode, this is obviously reversed.
```

2023-07-11 12:47 UTC, VadymSachenko commented on docs/scos/dev/front-end-development/202212.0/oryx/styling/colors.md
> +The color values can be of any supported color in the web platform, such as named colors ('red', 'blue', etc), hex color, hcl, rba, etc. Oryx does not interfere with the provided colors, but use them
```suggestion
The color values can be of any supported color in the web platform, such as named colors ('red' or 'blue'), hex color, hcl, or rba. Oryx doesn't interfere with the provided colors but uses them as-is.
```

2023-07-11 12:47 UTC, VadymSachenko commented on docs/scos/dev/front-end-development/202212.0/oryx/styling/colors.md
> +## Custom the colors
We don't need the section if it goes without a description.
```suggestion
```

2023-07-11 12:47 UTC, VadymSachenko commented on docs/scos/dev/front-end-development/202212.0/oryx/styling/colors.md
> +### Configure a color from the color palette
Because we remove the parent section, this one turns parent.
```suggestion
## Configure a color from the color palette
```

2023-07-11 12:47 UTC, VadymSachenko commented on docs/scos/dev/front-end-development/202212.0/oryx/styling/colors.md
> +### Configure custom colors
Because we remove the parent section, this one turns parent.
```suggestion
## Configure custom colors
```

2023-07-11 12:47 UTC, VadymSachenko commented on docs/scos/dev/front-end-development/202212.0/oryx/styling/colors.md
> +Providing both the light and dark mode is optional (but recommended), and will only be used if you do support both light and dark mode.
```suggestion
{% info_block infoBox "Note" %}

Providing both the light and dark mode is optional (but recommended), and will only be used if you do support both light and dark mode.

{% endinfo_block %}
```

2023-07-11 12:47 UTC, VadymSachenko commented on docs/scos/dev/front-end-development/202212.0/oryx/styling/colors.md
> +Each color type and its values is provided as a design token. Design tokens are provided as CSS variables to the root of the application. The color design tokens follow a consistent naming pattern, s
```suggestion
Each color type and its values are provided as a [design token. Design tokens are provided as CSS variables to the root of the application. The color design tokens follow a consistent naming pattern to improve the integration into your components:
```

2023-07-11 12:47 UTC, VadymSachenko commented on docs/scos/dev/front-end-development/202212.0/oryx/styling/colors.md
> +For example, when you like to create a solid button with an accessible foreground text color, you could do the following:
```suggestion
For example, if you create a solid button with an accessible foreground text color, you can do the following:
```

2023-07-11 12:47 UTC, VadymSachenko commented on docs/scos/dev/front-end-development/202212.0/oryx/styling/colors.md
> +This would work consistently with all colors. The buttons will have a white foreground color on a colorful background, unless the background color is bright; in that case, the foreground color will b
```suggestion
This example works consistently with all colors. The buttons have a white foreground color on a colorful background unless the background color is bright. In that case, the foreground color becomes black.
```

2023-07-11 12:48 UTC, VadymSachenko commented on docs/scos/dev/front-end-development/202212.0/oryx/styling/colors.md
> +There are 8 semantic color types used in Oryx components.
```suggestion
There are eight semantic color types used in Oryx components.
```

2023-07-13 12:01 UTC, VadymSachenko approved these changes

2023-07-13 12:45 UTC, merged