Bo 2273/volume prices for product offers
spryker/spryker-docs pull request #205
Opened 2021-08-06 12:35 UTC by andriitserkovnyi

## PR Description

https://spryker.atlassian.net/browse/BO-2273

- Added a feature overview and a feature walkthrough
- Updated the BO UG for product offers

## Checklist
- [x] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2021-08-10 09:27 UTC, AdvaBD requested changes

2021-08-10 09:27 UTC, AdvaBD commented on docs/marketplace/user/features/202108.0/marketplace-merchant-portal-product-offer-management-feature-overview.md
> +| Merchnat SKU | Unique identifier of the merchants' offer. |
Unique identifier of the merchants' offer is Offer Reference, the Merchant SKU is when the Merchant is using a different SKU in his/her system than the one used in the marketplace for this product

2021-08-13 14:24 UTC, lenadoc requested changes

2021-08-13 14:24 UTC, lenadoc commented on docs/marketplace/user/merchant-portal-user-guides/202108.0/offers/managing-product-offers.md
>  3. In the drawer, fill the necessary fields and click **Create**.
Consider adding information from this PR: https://github.com/spryker/spryker.github.io/pull/211/files Specifically, the info from lines 20-30 (no need to include the detailed info about the fields that you have in the reference information section of course). "Fill the necessary fields" is not a very helpful step, and there is no information about such fields as for example "Always in stock" or "Offer status". Consider adding them in the reference information or here

2021-08-13 14:24 UTC, lenadoc commented on docs/marketplace/user/merchant-portal-user-guides/202108.0/offers/managing-product-offers.md
> +On the *Create Offer* page, you see the list of product you can create an offer for. You can filter, sort and search the products.
```suggestion
On the *Create Offer* page, you see the list of products you can create an offer for. You can filter, sort and search the products.
```

2021-08-13 14:24 UTC, lenadoc commented on docs/marketplace/user/merchant-portal-user-guides/202108.0/offers/managing-product-offers.md
> +
Please specify the field names where you can filter offers by existing and visibility. It's not obvious, as the fields for filtering are called just "offers" and "status"

2021-08-18 08:39 UTC, lenadoc approved these changes

2021-08-20 17:17 UTC, AdvaBD approved these changes

2021-08-25 08:38 UTC, merged