docs: document creating pages in Oryx
spryker/spryker-docs pull request #2051
Opened 2023-08-01 06:16 UTC by tobi-or-not-tobi

2023-08-01 13:09 UTC, tolerants requested changes

2023-08-01 13:09 UTC, tolerants commented on docs/scos/dev/front-end-development/202212.0/oryx/building-pages/oryx-pages.md
> +- skip parts of the data, e.g. `#home-page.oryx-product-title`
Not sure I get this point. What exactly we are skipping here?

2023-08-01 13:09 UTC, tolerants commented on docs/scos/dev/front-end-development/202212.0/oryx/building-pages/oryx-pages.md
> +When you do not provide a merge `type`, the selected component is replaced by default. Alternative types can be configured in the `merge.type` field.
Maybe let's add an example?

2023-08-21 13:21 UTC, tolerants submitted a review, later dismissed

2023-08-21 14:27 UTC, andriitserkovnyi commented on docs/scos/dev/front-end-development/202212.0/oryx/building-pages/oryx-pages.md
> +Pages in Oryx are represented as [compositions](/docs/scos/dev/front-end-development/{{page.version}}/oryx/building-pages/oryx-compositions.html), which are collections of components organized in a s
Shall we replace `concern` with `responsibility`?

2023-08-22 07:28 UTC, andriitserkovnyi commented on docs/scos/dev/front-end-development/202212.0/oryx/building-pages/oryx-pages.md
> +## Non-data-driven approach
I feel like there must be a word for it. Hardcoded? model-driven? qualitative? subjective?

2023-08-23 07:21 UTC, andriitserkovnyi commented on docs/scos/dev/front-end-development/202212.0/oryx/building-pages/oryx-pages.md
> +When you do not provide a merge `type`, the selected component is replaced by default. Alternative types can be configured in the `merge.type` field.
And what is the default way to replace a selected component?

2023-08-23 08:03 UTC, supproduction commented on docs/scos/dev/front-end-development/202212.0/oryx/building-pages/oryx-pages.md
> +| `prepend`           | Adds the content before the first component of the composition components. If the selected component is not a composition, the custom component is not merged. |
Should we also mention about `remove` and possibility of using `refs`?

2023-08-23 12:14 UTC, tolerants commented on docs/scos/dev/front-end-development/202212.0/oryx/building-pages/oryx-pages.md
> +| `patch`             | Patches the selected component with the given component. This includes both the component options and content. The data is deep merged, expect for arrays.     |
```suggestion
| `patch`             | Patches the selected component with the given component. This includes both the component options and content. The data is deep merged, except for arrays.     |
| `remove`             | Removed selected component.    |
```

2023-08-23 12:15 UTC, tolerants commented on docs/scos/dev/front-end-development/202212.0/oryx/building-pages/oryx-pages.md
> +| `patch`             | Patches the selected component with the given component. This includes both the component options and content. The data is deep merged, expect for arrays.     |
There was a typo. `expect` => `except`

2023-08-28 15:12 UTC, tolerants submitted a review, later dismissed

2023-09-05 09:01 UTC, andriitserkovnyi approved these changes

2023-09-05 09:01 UTC, merged