MP-4510: add doc
spryker/spryker-docs pull request #206
Opened 2021-08-06 13:27 UTC by supproduction

## PR Description

TBD

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2021-09-17 16:54 UTC, gund requested changes

2021-09-17 16:54 UTC, gund commented on docs/marketplace/dev/front-end/web-components.md
> +The full cycle of the new module creation and registration it as a web component you can see in the [following document](/docs/marketplace/dev/front-end/how-to-create-a-new-module-with-application.ht
Please provide here a short snippet example how to register a component as a webcomponent.
Also please mention that all web components will get a prefix to their selectors by default and show how to customise it as an example.

2021-10-01 07:32 UTC, FRITS-Kh requested changes

2021-10-01 07:32 UTC, FRITS-Kh commented on docs/marketplace/dev/front-end/web-components.md
> +You can see the example of registration angular components as web components below:
```suggestion
You can see the example of registration Angular components as web components below:
```

2021-10-01 07:57 UTC, FRITS-Kh approved these changes

2021-10-04 16:49 UTC, gibmirmilch approved these changes

2021-10-04 16:49 UTC, merged