Install the shipment feature
spryker/spryker-docs pull request #2116
Opened 2023-08-24 10:11 UTC by artem-png

2023-08-24 10:33 UTC, abitskil commented on _includes/pbc/all/install-features/202400.0/install-the-shipment-feature.md
> +```
Let's add the following verification: 
{% info_block warningBox "Verification" %}
Make sure that after completing the reordering process, the address selection step functions correctly and that the appropriate address type is selected "single address".
{% info_block warningBox "Verification" %}

2023-08-24 11:03 UTC, abitskil submitted a review, later dismissed

2023-08-24 12:25 UTC, philinecao submitted a review, later dismissed

2023-08-28 07:26 UTC, VadymSachenko requested changes

2023-08-28 07:26 UTC, VadymSachenko commented on _includes/pbc/all/install-features/202400.0/install-the-shipment-feature.md
> +| ShipmentTypeCheckoutPageStepEnginePreRenderPlugin            | Expands `Quote.items.shipment` transfer with `shipmentTypeUuid` taken from `Quote.items.shipmentType.uuid`. |               | SprykerS
```suggestion
| ShipmentTypeCheckoutPageStepEnginePreRenderPlugin            | Expands the `Quote.items.shipment` transfer with `shipmentTypeUuid` taken from `Quote.items.shipmentType.uuid`. |               | SprykerShop\Yves\ShipmentTypeWidget\Plugin\CheckoutPage    |
```

2023-08-28 07:26 UTC, VadymSachenko commented on _includes/pbc/all/install-features/202400.0/install-the-shipment-feature.md
> +Make sure that after completing the reordering process, the address selection step functions correctly and the address type is selected as "single address".
```suggestion
Make sure that after completing the reordering process, the address selection step functions correctly, and the address type is selected as "single address".
```

2023-08-28 07:41 UTC, VadymSachenko approved these changes

2023-08-28 08:28 UTC, merged