fix: align package documentation with latest changes
spryker/spryker-docs pull request #2119
Opened 2023-08-28 13:04 UTC by tobi-or-not-tobi

Before 1.0 we've improved the package layers slightly to prevent cycle dependencies in the layered package architecture.

2023-08-28 13:09 UTC, tolerants requested changes

2023-08-28 13:09 UTC, tolerants commented on docs/scos/dev/front-end-development/202307.0/oryx/oryx-packages.md
> +| [Presets](https://www.npmjs.com/package/@spryker-oryx/oryx-presets.html) | `@spryker-oryx/oryx-presets`                                    |
```suggestion
| [Presets](https://www.npmjs.com/package/@spryker-oryx/presets) | `@spryker-oryx/oryx-presets`                                    |
```

2023-08-28 13:09 UTC, tolerants commented on docs/scos/dev/front-end-development/202307.0/oryx/oryx-packages.md
> +| [Application](https://www.npmjs.com/package/@spryker-oryx/application)   | `@spryker-oryx/oryx-application-orchestration/oryx-application` |
```suggestion
| [Application](https://www.npmjs.com/package/@spryker-oryx/application)   | `@spryker-oryx/application` |
```

2023-08-28 15:08 UTC, tolerants submitted a review, later dismissed

2023-08-31 07:29 UTC, andriitserkovnyi submitted a review, later dismissed

2023-08-31 08:11 UTC, andriitserkovnyi approved these changes

2023-08-31 08:11 UTC, merged