FRW-5858 Adjusted docs about download schema
spryker/spryker-docs pull request #2147
Opened 2023-09-06 12:27 UTC by geega

## PR Description

TBD

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2023-09-06 12:27 UTC, geega commented on docs/scos/dev/glue-api-guides/202307.0/data-exchange-api/how-to-guides/how-to-configure-data-exchange-api.md
> +[PASTE SCREENSHOT HERE]
<img width="1440" alt="download-btn" src="https://github.com/spryker/spryker-docs/assets/1426310/61b6b5bb-215d-4577-9e0c-fe8b60d8688a">

2023-09-06 12:28 UTC, geega commented on docs/scos/dev/glue-api-guides/202307.0/data-exchange-api/how-to-guides/how-to-configure-data-exchange-api.md
> +[PASTE SCREENSHOT HERE]
![Uploading Screenshot 2023-09-06 at 15.17.41.png…]()

2023-09-06 12:28 UTC, geega commented on docs/scos/dev/glue-api-guides/202307.0/data-exchange-api/how-to-guides/how-to-configure-data-exchange-api.md
> +[PASTE SCREENSHOT HERE]
<img width="1440" alt="Screenshot 2023-09-06 at 15 13 03" src="https://github.com/spryker/spryker-docs/assets/1426310/6301e29b-d093-49c2-9385-f2b8d571de5e">

2023-09-06 12:29 UTC, geega commented on docs/scos/dev/glue-api-guides/202307.0/data-exchange-api/how-to-guides/how-to-configure-data-exchange-api.md
> +[PASTE SCREENSHOT HERE]
<img width="1440" alt="Screenshot 2023-09-06 at 15 17 41" src="https://github.com/spryker/spryker-docs/assets/1426310/a8272e81-9de1-4339-86bf-7c459762790c">

2023-09-06 12:29 UTC, geega commented on docs/scos/dev/glue-api-guides/202307.0/data-exchange-api/how-to-guides/how-to-configure-data-exchange-api.md
> +[PASTE SCREENSHOT HERE]
<img width="1440" alt="Screenshot 2023-09-06 at 15 10 51" src="https://github.com/spryker/spryker-docs/assets/1426310/58b963f3-324e-41e3-9ff6-75aca8ecbea6">

2023-09-06 12:58 UTC, asmarovydlo requested changes
1. Please mention somewhere that documentation generation might be in progress, and the button will appear whenever the documentation generation is finished.
2. Why the screenshots added just as a comment? Will TW upload the images?

2023-09-07 08:41 UTC, geega commented
@asmarovydlo 

1. Added text about button. 
2. Yes. I don't know where to download the pictures. I see that this is an s3 bucket, but I don't have access to it. So I did like on PR for basic branch

2023-09-12 13:19 UTC, geega commented
@asmarovydlo  
I added screenshots `docs/scos/dev/drafts-dev`
@lenadoc helped me with it. 
https://spryker.atlassian.net/wiki/spaces/DOCS/pages/3554246794/Contributing+to+docs+for+Spryker+developers


> Currently, only technical writers can add images to documentation. If you need to insert an image to your doc, add it [here](https://github.com/spryker/spryker-docs/tree/master/docs/scos/dev/drafts-dev). The technical writer who will review your PR will move the image to the proper storage.

2023-09-12 13:27 UTC, asmarovydlo requested changes

2023-09-12 13:27 UTC, asmarovydlo commented on notes.md
> +# Notes
Where did those file changes come from? They are not related to the current documentation

2023-09-12 13:27 UTC, asmarovydlo commented on docs/scos/dev/glue-api-guides/202307.0/data-exchange-api/how-to-guides/how-to-configure-data-exchange-api.md
> +```
This is no longer the case, this functionality is removed. Please align with Dmitry Tsemma, and remove those lines and screenshot.

2023-09-12 16:00 UTC, asmarovydlo submitted a review, later dismissed

2023-10-06 11:50 UTC, asmarovydlo approved these changes

2023-10-06 11:51 UTC, asmarovydlo commented
> The base branch was changed.
It is OK, @lenadoc could you please make TW review, and if all is good - merge?

2023-10-11 11:54 UTC, merged