Akeneo PIM app configuration in Alumio
spryker/spryker-docs pull request #2296
Opened 2023-11-02 18:28 UTC by lenadoc

## PR Description

TBD

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2023-11-07 10:14 UTC, evgeny-popovv approved these changes

2023-11-09 21:15 UTC, monicabrassilva requested changes

2023-11-10 00:01 UTC, monicabrassilva requested changes

2023-11-10 00:01 UTC, monicabrassilva commented on docs/pbc/all/data-exchange/202311.0/spryker-middleware-powered-by-alumio/integration-apps/akeneo-pim-integration-app/configure-the-akeneo-pim-integration-app/5-create-tasks-and-import-products-from-akeneo-to-sccos.md
> +## Check the product in the Back Office
```suggestion
## Check the product in the SCCOS Back Office
```

2023-11-10 00:01 UTC, monicabrassilva commented on docs/pbc/all/data-exchange/202311.0/spryker-middleware-powered-by-alumio/integration-apps/akeneo-pim-integration-app/configure-the-akeneo-pim-integration-app/5-create-tasks-and-import-products-from-akeneo-to-sccos.md
> +To check the imported product in the Back Office, go to **Catalog -> Products** and check if the product appeared on the list.
```suggestion
To check the imported product in the SCCOS Back Office, go to **Catalog -> Products** and check if the product appeared on the list.
```

2023-11-10 12:27 UTC, merged