FRW-6285 provided release note
spryker/spryker-docs pull request #2384
Opened 2023-12-07 20:33 UTC by dimitriyTsemma

## PR Description

TBD

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2023-12-08 09:39 UTC, gechetspr requested changes
One comment. The rest looks good.
Question: what were changed for customers? Is it worth to mention?

2023-12-08 09:39 UTC, gechetspr commented on docs/scos/user/intro-to-spryker/releases/release-notes/security-release-notes-202312.1.md
> +Backend API access tokens are not validated. An attacker is able to request as many access tokens as he likes. Each requested token is valid and not expired.
`Backend API access tokens are not validated` sounds to scary IMO :)
I would rephrase it to smth like `Glue Backend API has no expiration validation for token` or smth like this

2023-12-11 08:24 UTC, dimitriyTsemma commented
> One comment. The rest looks good. Question: what were changed for customers? Is it worth to mention?

comment fixed, regarding changes for customers: we mentioned these changes in the Introduced changes section: 
"The token becomes invalid if it has not been used for a while."

2023-12-12 08:36 UTC, gechetspr approved these changes

2023-12-13 15:09 UTC, ppechlivanis-spryker commented
Hi all! Thank you for preparing the security release notes for this issue.

I plan to open a new PR and include security release notes for all issues that were fixed in Q4. So we can possible close this one and not merge it. A new PR that will include these changes will open shortly.

2023-12-15 10:15 UTC, ppechlivanis-spryker commented
I have created a new PR that includes all vulnerabilities that were fixed in Q4 (including this one as well). relevant PR:
https://github.com/spryker/spryker-docs/pull/2398

As such we can close this one and merge the new one that I created.

2025-01-22 09:33 UTC, closed without merging