MP-5129 Table Feature Selectable
spryker/spryker-docs pull request #240
Opened 2021-08-26 15:12 UTC by danilmoro3

Ticket: https://spryker.atlassian.net/browse/MP-5129

2021-09-14 10:18 UTC, gund requested changes

2021-09-14 10:18 UTC, gund commented on docs/marketplace/dev/front-end/table-design/table-feature-extension/table-feature-selectable.md
> +export class RootModule {}
Please move this to a separate section called "Feature Registration" above "Interfaces" section and change the import to the package name not relative import.

2021-09-14 10:18 UTC, gund commented on docs/marketplace/dev/front-end/table-design/table-feature-extension/table-feature-selectable.md
> +See an example below, how to use the Selectable feature.
```suggestion
When rows selection changes feature emits an event with all selected rows and other features can use that to do something with them (for example Batch Actions Feature will display applicable actions for selected rows).

See an example below, how to use the Selectable feature.
```

2021-09-29 12:59 UTC, FRITS-Kh requested changes

2021-09-29 12:59 UTC, FRITS-Kh commented on docs/marketplace/dev/front-end/table-design/table-features/table-feature-selectable.md
> +See an example below, how to use the Selectable feature.
```suggestion
(for ex. [Batch Actions Feature](/docs/marketplace/dev/front-end/table-design/table-features/table-feature-batch-actions.html) will display applicable actions for selected rows).

See an example below, how to use the Selectable feature.
```

2021-09-29 13:06 UTC, FRITS-Kh approved these changes

2021-09-30 15:38 UTC, merged