MP-5130 Table Feature Row actions
spryker/spryker-docs pull request #242
Opened 2021-08-27 11:34 UTC by danilmoro3

Ticket: https://spryker.atlassian.net/browse/MP-5130

2021-09-14 10:30 UTC, gund requested changes

2021-09-14 10:30 UTC, gund commented on docs/marketplace/dev/front-end/table-design/table-feature-extension/table-feature-row-actions.md
> +export class RootModule {}
Please move this to a separate section called "Feature Registration" above "Interfaces" section and change the import to the package name not relative import.

2021-09-14 10:30 UTC, gund commented on docs/marketplace/dev/front-end/table-design/table-feature-extension/table-feature-row-actions.md
> +Also this feature allows triggering actions via row click.
Please also add a link to actions doc.

```suggestion
Table Feature Row Actions is a feature of the Table Component that renders dropdown 
menu that contains actions applicable to the table row and on click triggers an Action which must be registered. 
Also this feature allows triggering actions via row click.
By default all actions will be available on every row but if needed they can be filtered using array of action IDs specified on each row in the data using path configured by `availableActionsPath`.
```

2021-09-14 10:30 UTC, gund commented on docs/marketplace/dev/front-end/table-design/table-feature-extension/table-feature-row-actions.md
> +    availableActionsPath: ['edit'],
```suggestion
    availableActionsPath: ['path.to.actions'],
```

2021-09-14 10:30 UTC, gund commented on docs/marketplace/dev/front-end/table-design/table-feature-extension/table-feature-row-actions.md
> +`availableActionsPath` - an array with available actions in the dropdown menu (by `id`).
```suggestion
`availableActionsPath` - path to an array with available action IDs in the table data row (supports nested objects using dot notation for ex. `prop.nestedProp`)
```

2021-09-14 10:30 UTC, gund commented on docs/marketplace/dev/front-end/table-design/table-feature-extension/table-feature-row-actions.md
> +      { id: 'delete', title: 'Delete' },
```suggestion
      { id: 'edit', title: 'Edit', type: 'edit-action' },
      { id: 'delete', title: 'Delete', type: 'delete-action' },
```

2021-09-14 10:30 UTC, gund commented on docs/marketplace/dev/front-end/table-design/table-feature-extension/table-feature-row-actions.md
> +`actions` - an array with actions that will be displayed in the dropdown menu.
```suggestion
`actions` - an array with actions that will be displayed in the dropdown menu and their type of registered Action.
```

2021-09-29 13:45 UTC, FRITS-Kh requested changes

2021-09-29 13:45 UTC, FRITS-Kh commented on docs/marketplace/dev/front-end/table-design/table-features/table-feature-row-actions.md
> +    availableActionsPath: ['path.to.actions'],
```suggestion
    availableActionsPath: 'path.to.actions',
```

2021-09-29 13:46 UTC, FRITS-Kh submitted a review, later dismissed

2021-10-01 12:01 UTC, gibmirmilch approved these changes

2021-10-01 12:01 UTC, merged