ACP-383: adjusted PBCs docs
spryker/spryker-docs pull request #2427
Opened 2024-01-08 14:59 UTC by oleksander-kiiashko

Task: https://spryker.atlassian.net/browse/ACP-383

2024-01-11 08:07 UTC, mharacewiat approved these changes

2024-01-16 14:50 UTC, evgeniy-it commented on docs/acp/user/app-composition-platform-installation.md
> +- BEFORE [202211.0](/docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202211.0/release-notes-202211.0.md) it's complicated and needs an assessment by devs/SA.
to remove

2024-01-19 07:21 UTC, evgeniy-it submitted a review, later dismissed

2024-01-25 08:53 UTC, lenadoc requested changes

2024-01-26 07:21 UTC, pushokwhite commented on docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/payone/integration-in-the-back-office/integrate-payone.md
> +Main process not only combines and operates sub-processes, its main goal to build everything around the only reserved=”true” state named invoiced;
That definitely makes no sense for the customers, replacing with the same one we have in Stripe documentation.

2024-01-26 07:23 UTC, pushokwhite commented on docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/payone/integration-in-the-back-office/integrate-payone.md
> +### Template changes in `CheckoutPage`
True, adding `optional` prefix.

2024-01-26 08:24 UTC, stereomon submitted a review, later dismissed
LGTM

2024-01-26 12:07 UTC, evgeniy-it approved these changes
LGTM

2024-01-26 15:00 UTC, merged