MP-5131 Table Feature Batch actions
spryker/spryker-docs pull request #243
Opened 2021-08-27 14:09 UTC by danilmoro3

Ticket: https://spryker.atlassian.net/browse/MP-5131

2021-09-29 14:13 UTC, FRITS-Kh requested changes

2021-09-29 14:13 UTC, FRITS-Kh commented on docs/marketplace/dev/front-end/table-design/table-features/table-feature-batch-actions.md
> +presenting the user with actions they can take.
```suggestion
As soon as at least one row is selected in the table, the batch action bar with allowed actions will appear at the top of the table.
```

2021-09-29 14:13 UTC, FRITS-Kh commented on docs/marketplace/dev/front-end/table-design/table-features/table-feature-batch-actions.md
> +See an example below, how to use the Batch Actions feature.
```suggestion
To escape the `batch action mode`, it is necessary to unselect the table rows.

See an example below, how to use the Batch Actions feature.
```

2021-09-29 14:14 UTC, FRITS-Kh requested changes

2021-09-29 14:14 UTC, FRITS-Kh commented on docs/marketplace/dev/front-end/table-design/table-features/table-feature-batch-actions.md
> +    availableActionsPath: ['path.to.actions'],
```suggestion
    availableActionsPath: 'path.to.actions',
```

2021-09-29 14:48 UTC, FRITS-Kh approved these changes

2021-10-01 12:40 UTC, gibmirmilch approved these changes

2021-10-01 12:40 UTC, merged