ACP-773: Stripe documentation mvp
spryker/spryker-docs pull request #2440
Opened 2024-01-11 10:37 UTC by danielsantos-spryker

## PR Description

TBD

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2024-01-11 14:12 UTC, matweew requested changes

2024-01-11 16:18 UTC, matweew submitted a review, later dismissed
From technical point of view it's good.

2024-01-12 09:23 UTC, stereomon approved these changes

2024-01-16 10:01 UTC, lenadoc requested changes

2024-01-16 10:17 UTC, danielsantos-spryker commented on docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/stripe/configure-stripe.md
> +- Make sure you have a Stripe connected account to Spryker platform, if you are unsure how to do it, please contact Spryker support.
- Make sure your project is ACP-enabled. See [App Composition Platform installation](/docs/acp/user/app-composition-platform-installation.html) for details.

This part might not be needed, you wouldn't be able to configure without install first and to install your project would have to be ACP-enabled

2024-01-16 10:18 UTC, danielsantos-spryker commented on docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/stripe/configure-stripe.md
> +- Make sure you have a Stripe connected account to Spryker platform, if you are unsure how to do it, please contact Spryker support.
- Make sure you have a Stripe connected account to Spryker platform, if you are unsure how to do it, please contact Spryker support.

For configuration you will need an account ID from Stripe

2024-01-16 10:20 UTC, danielsantos-spryker commented on docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/stripe/configure-stripe.md
> +5. Enter your *Shop Name*. This name will be displayed on **Payment** page as a merchant label for whom to pay:
![Screenshot 2024-01-16 at 10 19 44](https://github.com/spryker/spryker-docs/assets/117193368/7d8eb26e-0b0e-4a7c-ab5e-6968ca5ee22a)

Please check

2024-01-17 10:16 UTC, merged