MP-5133 Table Feature Sync State
spryker/spryker-docs pull request #252
Opened 2021-08-31 09:19 UTC by danilmoro3

Ticket: https://spryker.atlassian.net/browse/MP-5133

2021-09-30 14:26 UTC, FRITS-Kh requested changes

2021-09-30 14:26 UTC, FRITS-Kh commented on docs/marketplace/dev/front-end/table-design/table-features/table-feature-sync-state.md
> +syncing the state of the table with browser URL (like pagination, filters, sorting, etc.).
```suggestion
synchronizing the table state with the browser URL (like pagination, filters, sorting, etc.).
```

2021-09-30 14:26 UTC, FRITS-Kh commented on docs/marketplace/dev/front-end/table-design/table-features/table-feature-sync-state.md
> +Table Feature Sync State is a feature of the Table Component that allows
```suggestion
Table Feature Sync State is a feature of the Table Component that provides 
```

2021-09-30 15:26 UTC, FRITS-Kh submitted a review, later dismissed

2021-10-01 13:34 UTC, gibmirmilch approved these changes

2021-10-01 13:35 UTC, merged