FRW-8409
spryker/spryker-docs pull request #2746
Opened 2024-07-26 13:34 UTC by geega

## PR Description

TBD

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2024-07-29 15:56 UTC, asmarovydlo requested changes

2024-07-29 15:56 UTC, asmarovydlo commented on docs/pbc/all/data-exchange/202404.0/tutorials-and-howtos/how-to-configure-dex.md
> +title: How to configure Data Exchange API endpoints for import or export data.
Everything except `Validation constrains` are already part of this existing documentation https://docs.spryker.com/docs/pbc/all/data-exchange/202404.0/configure-data-exchange-api.html#create-and-configure-a-data-exchange-api-endpoint

1. Why do we need all these example configurations for discounts, vouchers, etc.?
2. If the answer to the first question is that it is just a generic how-to page, please create a separate how-to page `Configure Data Exchange API validation`, and get rid of this one.

2024-07-31 17:04 UTC, asmarovydlo requested changes

2024-08-05 15:15 UTC, dimitriyTsemma commented on _includes/pbc/all/install-features/202404.0/install-the-data-exchange-api.md
> +        "tableName": "spy_tax_rate",
we have this relation inside Country

2024-08-05 16:09 UTC, asmarovydlo commented on docs/pbc/all/data-exchange/202404.0/tutorials-and-howtos/how-to-create-custom-post-plugin.md
> +        $responseTransfer = $this->getFacade()->createSubTestEntity($dynamicEntityPostEditRequestTransfer->getRawDynamicEntities()->getArrayCopy());
If we call some facade method, it should exist. I would recommend to just add some basic functionality to the plugin, instead of using facade method.

2024-08-05 16:10 UTC, asmarovydlo commented on docs/pbc/all/data-exchange/202404.0/tutorials-and-howtos/how-to-create-custom-post-plugin.md
> +use Propel\Runtime\Collection\Collection;
Not used.

2024-08-05 16:11 UTC, asmarovydlo commented on docs/pbc/all/data-exchange/202404.0/tutorials-and-howtos/how-to-create-custom-post-plugin.md
> +For example, we will create a plugin that will call a facade method after data import for a specific entity, it's an abstract example, and you can implement your logic. If you need to implement a plu
[Note] If we'll remove facade method call from the plugin, this text should be adjusted as well.

2024-08-05 16:12 UTC, asmarovydlo commented on docs/pbc/all/data-exchange/202404.0/tutorials-and-howtos/how-to-create-custom-post-plugin.md
> +Methods `postCreate` and `postUpdate` should return `DynamicEntityPostEditResponseTransfer` object, you can add some errors in this transfer object if needed. `DynamicEntityPostEditRequestTransfer` o
We have example only for PostCreate plugin, why `postUpdate` also mentioned?

2024-08-05 16:12 UTC, asmarovydlo commented on _includes/pbc/all/install-features/202404.0/install-the-data-exchange-api.md
> +At the moment Data Exchange API does not support child relations configuration. If you need to configure child relations, you can do it manually in the database or adjust the configuration in file `s
```suggestion
At the moment Data Exchange API does not support child relations configuration from the Backoffice. If you need to configure child relations, you can do it manually in the database or adjust the configuration in file `src/Pyz/Zed/DynamicEntity/data/installer/configuration.json` for import.
```

2024-08-05 16:13 UTC, asmarovydlo commented on docs/pbc/all/data-exchange/202404.0/tutorials-and-howtos/how-to-create-custom-post-plugin.md
> +title: How to create a custom post plugin for Data Exchange API
```suggestion
title: How to create a custom post create/update plugin for Data Exchange API
```

2024-08-05 16:14 UTC, asmarovydlo commented on docs/pbc/all/data-exchange/202404.0/tutorials-and-howtos/how-to-create-custom-post-plugin.md
> +description: This document describes how to create custom post plugins for the Data Exchange API.
```suggestion
description: This document describes how to create custom post create/update plugins for the Data Exchange API.
```

2024-08-05 16:14 UTC, asmarovydlo commented on docs/pbc/all/data-exchange/202404.0/tutorials-and-howtos/how-to-create-custom-post-plugin.md
> +            new CustomDynamicEntityPostCreatePlugin(),
Please add verification step.

2024-08-06 09:36 UTC, asmarovydlo requested changes

2024-08-06 09:36 UTC, asmarovydlo commented on docs/pbc/all/data-exchange/202404.0/tutorials-and-howtos/how-to-create-custom-post-plugin.md
> +        $responseTransfer = $this->getSubTestCreator()->createSubTestEntity($dynamicEntityPostEditRequestTransfer->getRawDynamicEntities()->getArrayCopy());
Not fixed https://github.com/spryker/spryker-docs/pull/2746#discussion_r1704351596
We should not use any classes that does not exist, please get rid of it and provide some code sample instead.

2024-08-06 09:36 UTC, asmarovydlo commented on docs/pbc/all/data-exchange/202404.0/tutorials-and-howtos/how-to-create-custom-post-plugin.md
> +Make sure the new created data has been in the database table.
Please use exact details, what table i should check, e.t.c

2024-08-06 13:40 UTC, asmarovydlo approved these changes

2024-08-06 13:51 UTC, andriitserkovnyi commented on _includes/pbc/all/install-features/202404.0/install-the-data-exchange-api.md
>  ##### Structure:
What's this structure?

2024-08-07 08:05 UTC, andriitserkovnyi commented on docs/pbc/all/data-exchange/202404.0/tutorials-and-howtos/how-to-create-custom-post-plugin.md
> +After data updates we may implement the `Spryker\Zed\DynamicEntityExtension\Dependency\Plugin\DynamicEntityPostUpdatePluginInterface` interface.
What are you trying to explain by this?

2024-08-07 12:11 UTC, merged