MP-5146 Actions Drawer
spryker/spryker-docs pull request #278
Opened 2021-09-02 15:00 UTC by danilmoro3

Ticket: https://spryker.atlassian.net/browse/MP-5146

2021-09-16 14:12 UTC, FRITS-Kh requested changes

2021-09-16 14:12 UTC, FRITS-Kh commented on docs/marketplace/dev/front-end/ui-components-library/actions/actions-drawer.md
> +    DrawerActionModule.withComponents({
Please provide `component registration` section with describing the component registration.
And remove this from interfaces.

2021-09-24 10:46 UTC, supproduction requested changes

2021-09-24 10:46 UTC, supproduction commented on docs/marketplace/dev/front-end/ui-components-library/actions/actions-drawer.md
> +There is an easy way to open drawer with `ng-template`. All you need it's just create a template and call
```suggestion
Another way to open drawer with `ng-template`. You need create a template and call 
```

2021-09-24 10:46 UTC, supproduction commented on docs/marketplace/dev/front-end/ui-components-library/actions/actions-drawer.md
> +@ViewChild(‘contentTpl’) contentTpl?: TemplateRef<any>;
```suggestion
import {  DrawerTemplateContext } from '@spryker/drawer';

@ViewChild(‘contentTpl’) contentTpl?: TemplateRef<DrawerTemplateContext>;
```

2021-09-24 12:12 UTC, supproduction submitted a review, later dismissed

2021-09-24 12:26 UTC, FRITS-Kh requested changes

2021-09-24 12:26 UTC, FRITS-Kh commented on docs/marketplace/dev/front-end/ui-components-library/actions/actions-drawer.md
> +Actions Drawer is an Angular Service that opens component/template in the Drawer.
```suggestion
Actions Drawer is an Angular Service that opens the Drawer with a component/template.
```

2021-09-24 12:26 UTC, FRITS-Kh commented on docs/marketplace/dev/front-end/ui-components-library/actions/actions-drawer.md
> +of it and throw it as `template` config prop to the `handleAction` method.
```suggestion
Another way to open the Drawer with `ng-template`. You need to create a template, get the reference of it and throw it as `template` config prop to the `handleAction` method.
```

2021-09-24 12:26 UTC, FRITS-Kh commented on docs/marketplace/dev/front-end/ui-components-library/actions/actions-drawer.md
> +`DrawerRef.openTemplate` will be called and drawer will be open with `contentTpl` template.
```suggestion
`DrawerRef.openTemplate` will be called and the Drawer will be open with `contentTpl` template.
```

2021-09-24 12:26 UTC, FRITS-Kh commented on docs/marketplace/dev/front-end/ui-components-library/actions/actions-drawer.md
> +Also, it's possible to create and register a custom component that will be rendered inside the drawer.
```suggestion
Any existing Angular component can be registered and used within the Drawer.
Also, it's possible to create and register a custom component that will be rendered inside the Drawer.
```

2021-09-24 12:31 UTC, FRITS-Kh approved these changes

2021-09-27 12:23 UTC, gibmirmilch approved these changes

2021-09-27 12:23 UTC, merged