FRW-1633 Updated PostgreSql version.
spryker/spryker-docs pull request #2810
Opened 2024-09-17 13:17 UTC by asmarovydlo

## PR Description

https://spryker.atlassian.net/browse/FRW-1633

2024-09-17 13:26 UTC, kraal-spryker submitted a review, later dismissed

2024-09-23 15:20 UTC, gechetspr requested changes

2024-09-23 15:20 UTC, gechetspr commented on docs/dg/dev/system-requirements/202307.0/system-requirements.md
> +| Databases                               | Depending on the project, one of the databases: MariaDB >= 10.4—preferred, PostgreSQL >=16-preferred, or MySQL >=5.7.
I would not use preferred here as we prefer that users use MariaDB

2024-10-02 08:20 UTC, gechetspr submitted a review, later dismissed

2024-10-21 07:57 UTC, merged