MP-5150 Actions Refresh Table
spryker/spryker-docs pull request #282
Opened 2021-09-03 10:59 UTC by danilmoro3

Ticket: https://spryker.atlassian.net/browse/MP-5150

2021-09-17 07:15 UTC, FRITS-Kh requested changes

2021-09-17 07:15 UTC, FRITS-Kh commented on docs/marketplace/dev/front-end/ui-components-library/actions/actions-refresh-table.md
> +`tableId` - an `id` of the table that will be refreshed via `Table Locator Service`.
Please add a link to the `Table Locator Service` doc.
Please will provide the doc if it isn't in the story list.

2021-09-23 11:51 UTC, FRITS-Kh approved these changes

2021-09-23 12:52 UTC, gibmirmilch approved these changes

2021-09-23 12:52 UTC, merged