MP-5139 Datasource Inline
spryker/spryker-docs pull request #284
Opened 2021-09-03 14:22 UTC by danilmoro3

Ticket: https://spryker.atlassian.net/browse/MP-5139

2021-09-24 12:52 UTC, FRITS-Kh requested changes

2021-09-24 12:52 UTC, FRITS-Kh commented on _data/sidebars/marketplace_dev_sidebar.yml
> +                - title: "Datasource Inline"
```suggestion
                - title: "Inline"
```

2021-09-24 12:52 UTC, FRITS-Kh commented on docs/marketplace/dev/front-end/ui-components-library/datasources/datasource-inline.md
> +`data` - a datasource data (usually coming from back-end).
```suggestion
`data` - a datasource data.  
```

2021-09-27 10:53 UTC, FRITS-Kh submitted a review, later dismissed

2021-09-27 12:30 UTC, gibmirmilch approved these changes

2021-09-27 12:31 UTC, merged