MP-5141 Datasource Inline Table
spryker/spryker-docs pull request #286
Opened 2021-09-03 16:16 UTC by danilmoro3

Ticket: https://spryker.atlassian.net/browse/MP-5141

2021-09-24 13:09 UTC, FRITS-Kh requested changes

2021-09-24 13:09 UTC, FRITS-Kh commented on docs/marketplace/dev/front-end/ui-components-library/datasources/datasource-inline-table.md
> +export interface TableDatasourceInlineConfig extends DatasourceConfig {
```suggestion
export interface DataTransformerFilterConfig {
  type: string;
  propNames: string | string[];
}

export interface TableDatasourceInlineConfig extends DatasourceConfig {
```

2021-09-27 10:55 UTC, FRITS-Kh approved these changes

2021-09-27 13:40 UTC, gibmirmilch approved these changes

2021-09-27 13:40 UTC, merged