Added overview of OTEL
spryker/spryker-docs pull request #2964
Opened 2024-12-06 13:54 UTC by gechetspr

## PR Description
Add a meaningful description here that will let us know what you want to fix with this PR or what functionality you want to add.

## Steps before you submit a PR
- Please add tests for the code you add if it's possible.
- Please check out our contribution guide: https://docs.spryker.com/docs/dg/dev/code-contribution-guide.html
- Add a `contribution-license-agreement.txt` file with the following content:
`I hereby agree to Spryker\'s Contribution License Agreement in https://github.com/spryker/spryker-docs/blob/HASH_OF_COMMIT_YOU_ARE_BASING_YOUR_BRANCH_FROM_MASTER_BRANCH/CONTRIBUTING.md.`

This is a mandatory step to make sure you are aware of the license agreement and agree to it. `HASH_OF_COMMIT_YOU_ARE_BASING_YOUR_BRANCH_FROM_MASTER_BRANCH` is a hash of the commit you are basing your branch from the master branch. You can take it from commits list of master branch before you submit a PR.

## Checklist
- [x] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2024-12-06 14:41 UTC, asmarovydlo commented on docs/dg/dev/backend-development/opentelemetry/overview.md
> +Wire new console command into your install script. It allows it to be executed on every deploy and generated filed during it.
Please check this part `and generated filed during it.`

2024-12-06 14:41 UTC, asmarovydlo commented on docs/dg/dev/backend-development/opentelemetry/overview.md
> +`\Spryker\Zed\Opentelemetry\OpentelemetryConfig::getCriticalClassNamePatterns` - some of the spans can be marked as critical in order to give them more priority on sampling. You can define what class
This is core level classes, i would provide example how it can be changed.

2024-12-08 19:35 UTC, eduard-melnytskyi requested changes
It collects traces and send it to your monitoring system after.

2025-01-07 13:08 UTC, profuel commented on docs/dg/dev/backend-development/opentelemetry/overview.md
> +Spryker provides [spryker/opentelemetry](https://packagist.org/packages/spryker/opentelemetry) package that covers essential parts. It includes the entry point for instrumentation, plugin that you ca
```suggestion
Spryker provides [spryker/opentelemetry](https://packagist.org/packages/spryker/opentelemetry) package that covers essential parts. It includes the entry point for instrumentation, plugin that you can wire in your monitoring service and a console command that allows you to generate [hooks](https://opentelemetry.io/docs/zero-code/php/#how-it-works) for project's code, which will create spans automatically. Also it includes instrumentation of Propel, Redis, ElasticSearch and RabbitMQ calls.
```

2025-01-07 13:08 UTC, profuel commented on docs/dg/dev/backend-development/opentelemetry/overview.md
> +title: Opentelemetry overview
```suggestion
title: OpenTelemetry overview
```
I see different writings in the document, please align.

2025-01-07 13:08 UTC, profuel commented on docs/dg/dev/backend-development/opentelemetry/overview.md
> +After install you can wire a Monitoring plugin from a `spryker/opentelemtry` module to get all listed features.
```suggestion
After installation you can wire a Monitoring plugin from a `spryker/opentelemtry` module to enable all listed above features.
```

2025-01-07 13:08 UTC, profuel commented on docs/dg/dev/backend-development/opentelemetry/overview.md
> +After that you can call method from Monitoring service and they will be translated to OpenTelemetry action. Be advised that some of the methods are not covered due to the fact that those things have
```suggestion
After that you can call methods from Monitoring service and they will be translated to OpenTelemetry action. Be advised that some of the methods are empty due to the fact that those things have no direct implementation in Opentelemetry, like `\Spryker\Service\Opentelemetry\Plugin\OpentelemetryMonitoringExtensionPlugin::markStartTransaction()` as transaction will start anyway.
```

2025-01-07 13:08 UTC, profuel commented on docs/dg/dev/backend-development/opentelemetry/overview.md
> +Provided console command used to generate hooks automatically for classes that you want to be covered with spans.
```suggestion
Console command *OpentelemetryGeneratorConsole*  is used to generate hooks automatically for classes that you want to be covered with spans.
```

2025-01-07 13:08 UTC, profuel commented on docs/dg/dev/backend-development/opentelemetry/overview.md
> +Wire new console command into your install script. It allows it to be executed on every deploy and generated filed during it.
```suggestion
You have to wire this console command into your install script, so it's executed on every deployment.
Please make sure that this command is located after all code modifications and generation.
```

2025-01-07 13:08 UTC, profuel commented on docs/dg/dev/backend-development/opentelemetry/overview.md
> +Skip some traces. You may not want to get a full trace for all of your transactions. You can define a probability of detailed trace overview by setting a probability via `OTEL_TRACE_PROBABILITY` env
I miss explanation of the NON-INSTRUMENTED classes, that are restricted in the main Spryker module.
For example, Container calls, - \Spryker\Zed\Opentelemetry\OpentelemetryConfig::getExcludedDirs
I already faced issues that some spans are missing.

2025-01-13 10:34 UTC, profuel commented on docs/dg/dev/backend-development/opentelemetry/overview.md
> +Skip some traces. You may not want to get a full trace for all of your transactions. You can define a probability of detailed trace overview by setting a probability via `OTEL_TRACE_PROBABILITY` env
Please include the possible values for each setting, i.e. 
OTEL_TRACE_PROBABILITY = integer 1...100

2025-01-15 10:17 UTC, profuel commented on docs/dg/dev/backend-development/opentelemetry/overview.md
> +`\Spryker\Zed\Opentelemetry\OpentelemetryConfig::areOnlyPublicMethodsInstrumented()` - OOTB we cover with hooks only public methods (except Controller classes), but you can change that with this conf
```suggestion
`\Spryker\Zed\Opentelemetry\OpentelemetryConfig::areOnlyPublicMethodsInstrumented()` - OOTB we cover with hooks  public methods of all classes and all methods of Controller classes, but you can change that with this configuration method.
```

btw, I'm not sure that private methods could be hooked in.

2025-01-15 10:17 UTC, profuel commented on docs/dg/dev/backend-development/opentelemetry/overview.md
> +Hooks processing require you to have a few PHP extensions in place. Spryker prepares our PHP images, so you need to install nothing, but just enable it in your deploy file
```suggestion
Hooks processing requires you to have a few PHP extensions in place. Spryker has prepared a new PHP image, so you need to install nothing, but just enable it in your deploy file
```

2025-01-15 10:17 UTC, profuel commented on docs/dg/dev/backend-development/opentelemetry/overview.md
> +    tag: spryker/php:8.3
```suggestion
    tag: spryker/php:8.3-alpine3.20-otel
```

2025-01-15 10:17 UTC, profuel commented on docs/dg/dev/backend-development/opentelemetry/overview.md
> +Be advised that `blackfire` extension can have a conflict with a `opentelemetry` one, so make sure that you are not using both in the same time.
what about NewRelic?

2025-01-15 10:17 UTC, profuel commented on docs/dg/dev/backend-development/opentelemetry/overview.md
> +`OTEL_BSP_MIN_SPAN_DURATION_THRESHOLD` - this is value that is used in `Closing span sampling` for critical and regular spans. OOTB the value is `20`. This value will be used as nanosecond.
I don't see a natural language description of this parameter.
```suggestion
`OTEL_BSP_MIN_SPAN_DURATION_THRESHOLD` - this is value that is used in `Closing span sampling` for critical and regular spans. OOTB the value is `20`. This value will be used as nanosecond.
```

2025-01-15 13:05 UTC, helen-laktionova commented on docs/dg/dev/backend-development/opentelemetry/overview.md
> +---
We need to add data about New Relic + OTEL

2025-01-16 14:06 UTC, gechetspr commented on docs/dg/dev/backend-development/opentelemetry/overview.md
> +---
What do you mean?

2025-01-16 14:17 UTC, profuel commented on docs/dg/dev/backend-development/opentelemetry/overview.md
> +---
`It's impossible to have NewRelic and OTel enabled on one environment.`

2025-01-16 14:45 UTC, gechetspr commented on docs/dg/dev/backend-development/opentelemetry/overview.md
> +`OTEL_BSP_MAX_EXPORT_BATCH_SIZE` - define a spans batch size that should be sent to an exporter. Default value `512`.
Exporter is a part of application and collector is a thing that you have in your own container that exporter send data to

2025-01-17 10:34 UTC, gechetspr commented on docs/dg/dev/backend-development/opentelemetry/overview.md
> +Skip some traces. You may not want to get a full trace for all of your transactions. You can define a probability of detailed trace overview by setting a probability via `OTEL_TRACE_PROBABILITY` env
updated

2025-01-17 10:34 UTC, gechetspr commented on docs/dg/dev/backend-development/opentelemetry/overview.md
> +Skip some traces. You may not want to get a full trace for all of your transactions. You can define a probability of detailed trace overview by setting a probability via `OTEL_TRACE_PROBABILITY` env
added more explanation for those methods

2025-01-17 10:35 UTC, gechetspr commented on docs/dg/dev/backend-development/opentelemetry/overview.md
> +    public function getCriticalClassNamePatterns(): array
updated description, but the answer is no. Currently those are just strings, but you are right. We will update the method that is using it eventually to use also patterns

2025-01-17 10:44 UTC, gechetspr commented on docs/dg/dev/backend-development/opentelemetry/overview.md
> +`OTEL_TRACES_SAMPLER_ARG` - this is a probability for `Opening span sampling` and is used for the regular spans. Default value is `0.3`.
tried to add more explanation to sampling "chapter"

2025-01-20 14:56 UTC, profuel commented on docs/dg/dev/backend-development/opentelemetry/overview.md
> +You are definitely want to track all possible errors during the execution. OOTB OpenTelemetry integration will catch all exceptions that were thrown during span execution. But there are possibility t
```suggestion
You are definitely want to track all possible errors during the execution. OOTB OpenTelemetry integration will catch all exceptions that were thrown during span execution. But there is a possibility that error is lost if part of your code was not covered with hooks, or spans were sampled out, or trace was marked as not detailed.
```

2025-01-20 14:57 UTC, profuel commented on docs/dg/dev/backend-development/opentelemetry/overview.md
> +You are definitely want to track all possible errors during the execution. OOTB OpenTelemetry integration will catch all exceptions that were thrown during span execution. But there are possibility t
@gechetspr is it possible to have a configuration that makes sure that ALL exceptions are attached to the root span, no matter what.

2025-01-27 13:52 UTC, profuel commented on docs/dg/dev/backend-development/opentelemetry/overview.md
> +Spryker is a big application, so you definitely doesn't want to prepare all hooks manually. Console command *OpentelemetryGeneratorConsole*  is used to generate those hooks automatically for classes
```suggestion
Spryker is a big application, so you definitely don't want to create all hooks manually. Console command  class *OpentelemetryGeneratorConsole*  is used to generate those hooks automatically for classes that you want to cover with spans.
```

2025-01-27 13:58 UTC, profuel commented on docs/dg/dev/backend-development/opentelemetry/overview.md
> +You have to wire this console command into your install script, so it's executed on every deployment.
```suggestion
You have to wire this console command into your install script, so it's executed on every deployment during base container image build. We recommend placing it as the last one in the section **build**.
```

2025-01-27 13:58 UTC, profuel commented on docs/dg/dev/backend-development/opentelemetry/overview.md
> +
```suggestion

Please get yourself familiar with the predefined configuration of this module in the vendor folder. Based on our research, some Core classes are excluded from instrumentation.
```

2025-01-27 13:58 UTC, profuel commented on docs/dg/dev/backend-development/opentelemetry/overview.md
> +### Enable PHP extension
```suggestion
### Enable PHP extensions
```

2025-01-27 13:58 UTC, profuel commented on docs/dg/dev/backend-development/opentelemetry/overview.md
> +Hooks processing requires you to have a few PHP extensions in place. Spryker has prepared a new PHP image, so you need to install nothing, but just enable it in your deploy file.
```suggestion
Hooks processing requires you to have a few PHP extensions in place. Spryker has prepared a new PHP image, so you need to install nothing, just enable them in your deploy file.
```

2025-01-27 13:58 UTC, profuel commented on docs/dg/dev/backend-development/opentelemetry/overview.md
> +Be advised that `blackfire` extension can have a conflict with a `opentelemetry` one, so make sure that you are not using both in the same time. We also would not recommend to run it together with a
Let's be more helpful here.
Blackfire can have conflicts - how is this visible if still both are enabled?
Is there an option how to add a switcher?

2025-01-27 15:23 UTC, profuel commented on docs/dg/dev/backend-development/opentelemetry/overview.md
> +Spryker allows to integrate different monitoring tools like NewRelic into the SCCOS. But usually those tools are vendor locked and allows to work only with limited amount of backends or have not so m
I don't know where, but let's add a mention, similar to the following
```
OTel is a paid service and requires additional contract with Spryker, please talk to our Sales Team.
```

2025-02-07 16:06 UTC, merged