MP-4508: UI-Components doc
spryker/spryker-docs pull request #321
Opened 2021-09-09 13:44 UTC by supproduction

## PR Description

TBD

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2021-09-17 16:51 UTC, gund requested changes

2021-09-17 16:51 UTC, gund commented on docs/marketplace/dev/front-end/ui-components-library/index.md
> +UI Angular Components lib has `Angular 9`, `rxjs`, `ng-zorro-antd 9` under the hood.
```suggestion
UI Angular Components is built using Angular 9, rxjs and Ant Design under the hood.
```

2021-09-30 15:51 UTC, FRITS-Kh requested changes

2021-09-30 15:51 UTC, FRITS-Kh commented on docs/marketplace/dev/front-end/ui-components-library/index.md
> +- @spryker/datasource.inline ([npm](https://www.npmjs.com/package/@spryker/datasource.inline), [story](https://spy-storybook.web.app/?path=/story/datasourceinline--primary))
```suggestion
- @spryker/datasource ([npm](https://www.npmjs.com/package/@spryker/datasource))
- @spryker/datasource.http ([npm](https://www.npmjs.com/package/@spryker/datasource.http))
- @spryker/datasource.inline ([npm](https://www.npmjs.com/package/@spryker/datasource.inline), [story](https://spy-storybook.web.app/?path=/story/datasourceinline--primary))
```

2021-09-30 15:51 UTC, FRITS-Kh commented on docs/marketplace/dev/front-end/ui-components-library/index.md
> +- @spryker/headline ([npm](https://www.npmjs.com/package/@spryker/headline), [story](https://spy-storybook.web.app/?path=/story/htmlrenderercomponent--with-static-html))
```suggestion
- @spryker/headline ([npm](https://www.npmjs.com/package/@spryker/headline), [story](https://spy-storybook.web.app/?path=/story/headlinecomponent--primary))
- @spryker/html-renderer ([npm](https://www.npmjs.com/package/@spryker/html-renderer), [story](https://spy-storybook.web.app/?path=/story/htmlrenderercomponent--with-static-html))
```

2021-09-30 16:08 UTC, FRITS-Kh submitted a review, later dismissed

2021-10-01 09:56 UTC, gibmirmilch approved these changes

2021-10-01 09:56 UTC, merged