CC-14560 Discount Priority IG
spryker/spryker-docs pull request #615
Opened 2021-12-06 13:45 UTC by AsonUnique

- Epic link: https://spryker.atlassian.net/browse/CC-14560

2021-12-06 13:56 UTC, DmitryLymarenko requested changes

2021-12-06 13:56 UTC, DmitryLymarenko commented on docs/scos/dev/feature-integration-guides/202200.0/promotions-and-discounts-feature-integration.md
> +The following feature integration guide expects the basic feature to be in place.
```suggestion
The following sub-feature integration guide expects the basic feature to be in place.
```

2021-12-06 13:56 UTC, DmitryLymarenko commented on docs/scos/dev/feature-integration-guides/202200.0/promotions-and-discounts-feature-integration.md
> +The current sub-feature integration guide adds discount prioritization functionality..
```suggestion
The current sub-feature integration guide adds discount prioritization functionality.
```

2021-12-06 13:56 UTC, DmitryLymarenko commented on docs/scos/dev/feature-integration-guides/202200.0/promotions-and-discounts-feature-integration.md
> +composer require spryker-feature/promotions-discounts {{page.version}} --update-with-dependencies
we should use splitted modules at this command since this doc is different from regular IGs

2021-12-06 13:56 UTC, DmitryLymarenko commented on docs/scos/dev/feature-integration-guides/202200.0/promotions-and-discounts-feature-integration.md
> +## Install feature core
```suggestion
## Install sub-feature core
```

2021-12-06 13:56 UTC, DmitryLymarenko commented on docs/scos/dev/feature-integration-guides/202200.0/promotions-and-discounts-feature-integration.md
> +## Install feature core
please check spelling everyewhere
Discount priorities is not a `feature`

2021-12-06 14:20 UTC, DmitryLymarenko commented on docs/scos/dev/feature-integration-guides/202200.0/promotions-and-discounts-feature-integration.md
> +## Install feature core
in this case we need opposite case
`sub-feature` and `prioritization` cases should be removed

2022-01-14 15:38 UTC, DmitryLymarenko commented on docs/scos/dev/feature-integration-guides/202200.0/promotions-and-discounts-feature-integration.md
> +| Discount  | vendor/spryker/discount  |
I assume bigger amount of modules installed

2022-01-14 16:05 UTC, DmitryLymarenko commented on docs/scos/dev/feature-integration-guides/202200.0/promotions-and-discounts-feature-integration.md
> +| Discount  | vendor/spryker/discount  |
discussed

2022-01-14 16:05 UTC, DmitryLymarenko submitted a review, later dismissed

2022-01-17 11:22 UTC, JacquieRooney approved these changes

2022-01-25 13:27 UTC, VadymSachenko reviewed
Approved from my side

2022-01-25 13:27 UTC, VadymSachenko approved these changes

2022-01-26 10:56 UTC, merged