New products added
spryker/spryker-docs pull request #639
Opened 2021-12-14 15:07 UTC by gibmirmilch

## PR Description

TBD

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2021-12-15 07:29 UTC, andriitserkovnyi approved these changes

2021-12-15 13:36 UTC, lenadoc approved these changes

2022-02-03 14:45 UTC, lenadoc requested changes

2022-02-03 14:45 UTC, lenadoc commented on docs/fes/dev/front-end-enablement-service.md
> +It's main objectives are:
```suggestion
Its main objectives are:
```

2022-02-03 14:45 UTC, lenadoc commented on docs/fes/dev/front-end-enablement-service.md
> +* To connect your SCCOS environments to the Launchpad. When creating a frontend, you can see the list of your environments, locales and currencies.
```suggestion
* To connect your SCCOS environments to the Launchpad. When creating a frontend, you can see the list of your environments, locales, and currencies.
```

2022-02-03 14:45 UTC, lenadoc commented on docs/fes/dev/front-end-enablement-service.md
> +Developers can switch the application between multiple repositories. For example, a developer points a frontend to a development server while testing. After testing, they point it to a production env
```suggestion
Developers can switch the application between multiple repositories. For example, a developer points a frontend to a development server while testing. After testing, they point it to a production environment, and the frontend goes live without having to test it in this environment.
```

2022-02-03 14:45 UTC, lenadoc commented on docs/fes/dev/front-end-enablement-service.md
> +Any project running on PaaS and with up-to-date APIs can use FeS for their frontends.
```suggestion
Any project running on PaaS and with up-to-date APIs can use FeS for its frontends.
```

2022-02-03 14:45 UTC, lenadoc commented on docs/fes/dev/launchpad-guides/launching-storefronts.md
> +
```suggestion
```

2022-02-03 14:45 UTC, lenadoc commented on docs/fes/dev/launchpad-guides/launching-storefronts.md
> +
```suggestion
```

2022-02-03 14:45 UTC, lenadoc commented on docs/fes/dev/launchpad-guides/launching-storefronts.md
> +
```suggestion
```

2022-02-03 14:45 UTC, lenadoc commented on docs/fes/dev/launchpad-guides/launching-storefronts.md
> +
```suggestion
```

2022-02-03 14:45 UTC, lenadoc commented on docs/fes/dev/launchpad-guides/launching-storefronts.md
> +  In future, you'll be able to create other types of applications. For now, let's stick with the Storefront.
```suggestion
  In the future, you'll be able to create other types of applications. For now, let's stick with the Storefront.
```

2022-02-03 14:45 UTC, lenadoc commented on docs/fes/dev/launchpad-guides/launching-storefronts.md
> +  This opens the the pane of the application.
```suggestion
  This opens the pane of the application.
```

2022-02-03 14:45 UTC, lenadoc commented on docs/fes/dev/launchpad-guides/editing-the-configuration-of-applications.md
> +
```suggestion
```

2022-02-03 14:45 UTC, lenadoc commented on docs/fes/dev/launchpad-guides/editing-the-configuration-of-applications.md
> +| BASE DIRECTORY | The directory from which a deployment is started. By default, the root directory of the repository is used. |
```suggestion
| BASE DIRECTORY | The directory from which deployment is started. By default, the root directory of the repository is used. |
```

2022-02-03 14:57 UTC, merged