Faas 1114/building front ends
spryker/spryker-docs pull request #641
Opened 2021-12-15 09:01 UTC by andriitserkovnyi

## PR Description

Building front ends tutorial

## Checklist
- [x] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2021-12-29 09:03 UTC, tobi-or-not-tobi requested changes

2021-12-29 09:03 UTC, tobi-or-not-tobi commented on docs/cloud/dev/spryker-cloud-commerce-os/front-end-enablement-service/front-end-enablement-service-guides/launching-storefronts.md
> +2. Select one or more **LOCALES** to be available in this Storefront.
we also need to select the default locale

2021-12-29 09:03 UTC, tobi-or-not-tobi commented on docs/cloud/dev/spryker-cloud-commerce-os/front-end-enablement-service/front-end-enablement-service-guides/launching-storefronts.md
> +3. Select one or more **CURRENCIES** to be available in this Storefront.
we also need to select the default currency

2021-12-29 09:03 UTC, tobi-or-not-tobi commented on docs/cloud/dev/spryker-cloud-commerce-os/front-end-enablement-service/front-end-enablement-service-guides/launching-storefronts.md
> +## Publishing the Storefront
Is it publishing? I thought it was named "install"

2021-12-29 09:03 UTC, tobi-or-not-tobi commented on docs/cloud/dev/spryker-cloud-commerce-os/front-end-enablement-service/front-end-enablement-service.md
> +FeS is designed to be used by developers and content managers.
FES

2021-12-29 09:03 UTC, tobi-or-not-tobi commented on docs/cloud/dev/spryker-cloud-commerce-os/front-end-enablement-service/front-end-enablement-service.md
> +FeS is designed to be used by developers and content managers.
@alistairSpryker I think "content managers" is not the right user name for now. We could start this docs with developers for now.

2021-12-29 12:59 UTC, andriitserkovnyi commented on docs/cloud/dev/spryker-cloud-commerce-os/front-end-enablement-service/front-end-enablement-service-guides/launching-storefronts.md
> +Using the login details provided by your FeS account owner, log into the [Launchpad](https://launchpad.spryker.com).
@alistairSpryker Please confirm the final version

2021-12-29 13:02 UTC, andriitserkovnyi commented on docs/cloud/dev/spryker-cloud-commerce-os/front-end-enablement-service/front-end-enablement-service-guides/launching-storefronts.md
> +  *Code Repository provider*, *Hosting provider*, and *Commerce provider* sections appear.
Are we putting them in this order in 1.0 release?

2021-12-29 13:03 UTC, andriitserkovnyi commented on docs/cloud/dev/spryker-cloud-commerce-os/front-end-enablement-service/front-end-enablement-service-guides/launching-storefronts.md
> +We recommend mapping branches to Storefronts as follows:
TBD with @alistairSpryker

2021-12-29 13:04 UTC, andriitserkovnyi commented on docs/cloud/dev/spryker-cloud-commerce-os/front-end-enablement-service/front-end-enablement-service-guides/launching-storefronts.md
> +  This is the command used to deploy the application. Specify it if you want to customize the build. The default command is `npm run build`.
Where will the files be placed then? Logically, many people will think about it. That's why we need to clarify it here.

2021-12-29 13:04 UTC, andriitserkovnyi commented on docs/cloud/dev/spryker-cloud-commerce-os/front-end-enablement-service/front-end-enablement-service-guides/launching-storefronts.md
> +   The deploy-ready HTML files and assets generated by the build are placed into this folder. The default folder is `/build`.
Where will the files be placed then? Logically, many people will think about it. That's why we need to clarify it here.

2022-02-03 14:36 UTC, andriitserkovnyi commented
will be merged in another PR

2022-02-03 14:36 UTC, closed without merging