CC-14562: Add categories to discount query parameters.
spryker/spryker-docs pull request #665
Opened 2022-01-06 08:23 UTC by dmiseev

## PR Description

- Epic: https://spryker.atlassian.net/browse/CC-14562

- Ticket for IG: https://spryker.atlassian.net/browse/CC-14583

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2022-01-07 10:29 UTC, JacquieRooney commented on docs/scos/dev/feature-integration-guides/202200.0/category-management-promotions-and-discounts-feature-integration.md
> +description: This guide provides step-by-step instructions on integrating Category Management + Promotions & Discounts feature into a Spryker-based project.
```suggestion
description: This guide provides step-by-step instructions on integrating into a Spryker-based project the new feature: Addition of a "Category" parameter to calculation and conditions queries in discounts.
```

2022-01-07 10:30 UTC, JacquieRooney commented on docs/scos/dev/feature-integration-guides/202200.0/category-management-promotions-and-discounts-feature-integration.md
> +2. Add a product with the defined category to cart.
```suggestion
2. Add a product assigned to the defined category to cart.
```

2022-01-07 10:32 UTC, JacquieRooney requested changes
Just a few changes requested around the phrasing. I can't comment on the correctness of the integration instructions, but generally this looks good.

2022-01-10 09:12 UTC, DmitryLymarenko commented on docs/scos/dev/feature-integration-guides/202200.0/category-management-promotions-and-discounts-feature-integration.md
> +description: his guide provides step-by-step instructions on integrating into a Spryker-based project the new feature: Addition of a "Category" parameter to calculation and conditions queries in disc
```suggestion
description: This guide provides step-by-step instructions on integrating into a Spryker-based project the new feature: Addition of a "Category" parameter to calculation and conditions queries in discounts.
```

2022-01-10 09:12 UTC, DmitryLymarenko commented on docs/scos/dev/feature-integration-guides/202200.0/category-management-promotions-and-discounts-feature-integration.md
> +### 1) Set up behavior
transfers section is missing

2022-01-10 09:12 UTC, DmitryLymarenko commented on docs/scos/dev/feature-integration-guides/202200.0/category-management-promotions-and-discounts-feature-integration.md
> +### 1) Set up behavior
the same for frontend section 
CSS was adjusted

2022-01-10 12:11 UTC, DmitryLymarenko submitted a review, later dismissed

2022-01-10 12:28 UTC, JacquieRooney submitted a review, later dismissed

2022-01-11 10:52 UTC, VadymSachenko commented on docs/scos/dev/feature-integration-guides/202200.0/category-management-promotions-and-discounts-feature-integration.md
> +| Spryker Core | {{page.version}} | [Spryker Сore feature integration](/docs/scos/dev/feature-integration-guides/{{page.version}}/spryker-core-feature-integration.html) |
@dmiseev check the links I added to the feature integration guides and say if they are correct or I should replace them.
[Promotions & Discounts feature integration](https://docs.spryker.com/docs/scos/dev/feature-integration-guides/202108.0/promotions-and-discounts-feature-integration.html)
[Category Management feature integration](https://docs.spryker.com/docs/scos/dev/feature-integration-guides/202108.0/category-management-feature-integration.html)
[Spryker Сore feature integration](https://docs.spryker.com/docs/scos/dev/feature-integration-guides/202108.0/spryker-core-feature-integration.html)

2022-01-11 11:12 UTC, dmiseev commented on docs/scos/dev/feature-integration-guides/202200.0/category-management-promotions-and-discounts-feature-integration.md
> +| Spryker Core | {{page.version}} | [Spryker Сore feature integration](/docs/scos/dev/feature-integration-guides/{{page.version}}/spryker-core-feature-integration.html) |
They are correct

2022-01-11 13:17 UTC, VadymSachenko approved these changes

2022-01-11 13:17 UTC, merged