CC-14555 Discount valid from/to supports time definition IG
spryker/spryker-docs pull request #684
Opened 2022-01-17 08:43 UTC by AsonUnique

Jira ticket: https://spryker.atlassian.net/browse/CC-14555

2022-01-17 10:52 UTC, DmitryLymarenko reviewed
there are js/css/translations added at https://github.com/spryker/spryker/pull/8914/files


please mention them as well

2022-01-18 12:59 UTC, DmitryLymarenko commented on docs/scos/dev/feature-integration-guides/202200.0/promotions-and-discounts-feature-integration.md
> +### 4) Set up behavior
It looks more like `Build Zed UI frontend` than `behavior`

2022-01-18 12:59 UTC, DmitryLymarenko commented on docs/scos/dev/feature-integration-guides/202200.0/promotions-and-discounts-feature-integration.md
> +Make sure that you can see a datetime picker dropdown when you click on **Valid From** and **Valid To** discount form fields.
It's probably worth to specify details (where to find it, on which page)

2022-01-18 16:09 UTC, DmitryLymarenko approved these changes

2022-01-19 10:08 UTC, JacquieRooney requested changes
Just some small adjustments to wording.

2022-01-19 10:08 UTC, JacquieRooney commented on docs/scos/dev/feature-integration-guides/202200.0/promotions-and-discounts-feature-integration.md
> +4. Make sure that **Valid From** and **Valid To** discount form fields can accept selected date and time.
```suggestion
4. Make sure that **Valid From** and **Valid To** discount form fields can accept selected date and time, using keystroke entry for times not falling on the hour.
```

2022-01-19 14:41 UTC, JacquieRooney submitted a review, later dismissed

2022-01-24 15:34 UTC, VadymSachenko commented on docs/scos/dev/feature-integration-guides/202200.0/promotions-and-discounts-feature-integration.md
> +4. Make sure **Valid From** and **Valid To** discount form fields can accept the selected date and time, using keystroke entry for times not falling on the hour.
What do you mean by "using keystroke entry for times not falling on the hour"?

2022-01-25 10:09 UTC, JacquieRooney commented on docs/scos/dev/feature-integration-guides/202200.0/promotions-and-discounts-feature-integration.md
> +4. Make sure **Valid From** and **Valid To** fields can accept the selected date and time, using keystroke entry for times not falling on the hour.
With the date/time picker, you can only click on a time that is on the hour, for example 13:00. If you want to specify a time like 13:45, you would need to type it in. I wanted to make it clear that it was possible to select a time that wasn't exactly on the hour, hence this phrase. Feel free to adjust for clarity.

2022-01-26 13:33 UTC, VadymSachenko approved these changes
Approved from my side

2022-01-27 09:57 UTC, merged