CC-14555 Add IG for BAPI and BAPI Merchant Relationships.
spryker/spryker-docs pull request #693
Opened 2022-01-18 12:46 UTC by AsonUnique

[## PR Description

TBD

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md
](https://spryker.atlassian.net/browse/GLUE-11191)

2022-01-18 13:19 UTC, DmitryLymarenko submitted a review, later dismissed

2022-01-18 17:18 UTC, JacquieRooney requested changes
Just changed all instances of back end/ Back end to backend/Backend, since it's one word (consistent with the rest of documentation.

2022-01-18 17:18 UTC, JacquieRooney commented on docs/scos/dev/feature-integration-guides/202200.0/back-end-api-for-merchant-relationships-integration-guide.md
> +title: Back End API for Merchant Relationships feature integration
```suggestion
title: Backend API for Merchant Relationships feature integration
```

2022-01-18 17:18 UTC, JacquieRooney commented on docs/scos/dev/feature-integration-guides/202200.0/back-end-api-for-merchant-relationships-integration-guide.md
> +description: Integrate the Back End API for Merchant Relationships into your project
```suggestion
description: Integrate the Backend API for Merchant Relationships into your project
```

2022-01-18 17:18 UTC, JacquieRooney commented on docs/scos/dev/feature-integration-guides/202200.0/back-end-api-for-merchant-relationships-integration-guide.md
> +# Back End API for Merchant Relationships feature integration
```suggestion
# Backend API for Merchant Relationships feature integration
```

2022-01-18 17:18 UTC, JacquieRooney commented on docs/scos/dev/feature-integration-guides/202200.0/back-end-api-for-merchant-relationships-integration-guide.md
> +Follow the steps below to install the {Back End API for Merchant Relationships feature core.
```suggestion
Follow the steps below to install the {Backend API for Merchant Relationships feature core.
```

2022-01-18 17:18 UTC, JacquieRooney commented on docs/scos/dev/feature-integration-guides/202200.0/back-end-api-for-merchant-relationships-integration-guide.md
> +| Back End API                      | {{page.version}}  | [Back End API feature integration](/docs/scos/dev/feature-integration-guides/{{page.version}}/back-end-api-feature-integration.html)
```suggestion
| Backend API                      | {{page.version}}  | [Backend API feature integration](/docs/scos/dev/feature-integration-guides/{{page.version}}/back-end-api-feature-integration.html)                                                                         |
```

2022-01-18 17:18 UTC, JacquieRooney commented on docs/scos/dev/feature-integration-guides/202200.0/back-end-api-for-merchant-relationships-integration-guide.md
> +| Back End API                      | {{page.version}}  | [Back End API feature integration](/docs/scos/dev/feature-integration-guides/{{page.version}}/back-end-api-feature-integration.html)
I think the URL should also be backend-api-feature-integration (instead of back-end), but I don't know where that URL came from/if we can change it.

2022-01-18 17:18 UTC, JacquieRooney commented on docs/scos/dev/feature-integration-guides/202200.0/back-end-api-integration-guide.md
> +title: Back End API feature integration
```suggestion
title: Backend API feature integration
```

2022-01-18 17:18 UTC, JacquieRooney commented on docs/scos/dev/feature-integration-guides/202200.0/back-end-api-integration-guide.md
> +description: Integrate the Back End API into your project
```suggestion
description: Integrate the Backend API into your project
```

2022-01-18 17:18 UTC, JacquieRooney commented on docs/scos/dev/feature-integration-guides/202200.0/back-end-api-integration-guide.md
> +# Back End API feature integration
```suggestion
# Backend API feature integration
```

2022-01-18 17:18 UTC, JacquieRooney commented on docs/scos/dev/feature-integration-guides/202200.0/back-end-api-integration-guide.md
> +This document describes how to integrate the [Back End API]({link to a respective feature overview}) into a Spryker project.
```suggestion
This document describes how to integrate the [Backend API]({link to a respective feature overview}) into a Spryker project.
```

2022-01-18 17:18 UTC, JacquieRooney commented on docs/scos/dev/feature-integration-guides/202200.0/back-end-api-integration-guide.md
> +Follow the steps below to install the Back End API feature core.
```suggestion
Follow the steps below to install the Backend API feature core.
```

2022-01-18 17:18 UTC, JacquieRooney commented on docs/scos/dev/feature-integration-guides/202200.0/back-end-api-integration-guide.md
> +| ApiConfig::isApiEnabled()          | Enables Back End API.                                                                  | Spryker\Zed\Api    |
```suggestion
| ApiConfig::isApiEnabled()          | Enables Backend API.                                                                  | Spryker\Zed\Api    |
```

2022-01-18 17:18 UTC, JacquieRooney commented on docs/scos/dev/feature-integration-guides/202200.0/back-end-api-integration-guide.md
> +Make sure that Back End API is enabled by accessing any back end API resource.
```suggestion
Make sure that Backend API is enabled by accessing any backend API resource. 
```

2022-01-18 17:18 UTC, JacquieRooney commented on docs/scos/dev/feature-integration-guides/202200.0/back-end-api-integration-guide.md
> +Make sure, that back end API is extended with request parameters and stacktrace when `ApiConstants::ENABLE_API_DEBUG` is set to `true`.
```suggestion
Make sure that Backend API is extended with request parameters and stacktrace when `ApiConstants::ENABLE_API_DEBUG` is set to `true`.
```

2022-01-18 17:18 UTC, JacquieRooney commented on docs/scos/dev/feature-integration-guides/202200.0/back-end-api-integration-guide.md
> +| ApiRouterPlugin                                   | Provides `Router` which handles Back End API calls.                                                                          |               | Sp
```suggestion
| ApiRouterPlugin                                   | Provides `Router` which handles Backend API calls.                                                                          |               | Spryker\Zed\Api\Communication\Plugin\Router                 |
```

2022-01-18 17:18 UTC, JacquieRooney commented on docs/scos/dev/feature-integration-guides/202200.0/back-end-api-integration-guide.md
> +Create a new entry point for Back End API Application:
```suggestion
Create a new entry point for the Backend API application:
```

2022-01-19 09:22 UTC, JacquieRooney approved these changes

2022-01-25 13:29 UTC, VadymSachenko approved these changes
Approved from my side

2022-01-25 14:07 UTC, merged