[TE-10628] сreate a doc on how external users can contribute to docs
spryker/spryker-docs pull request #725
Opened 2022-01-31 11:46 UTC by VadymSachenko

## PR Description

Jira tiket: https://spryker.atlassian.net/browse/TE-10628

TBD

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2022-02-01 12:19 UTC, lenadoc requested changes

2022-02-01 12:19 UTC, lenadoc commented on docs/scos/user/intro-to-spryker/contributing-to-documentation/contributing-to-spryker-documentation.md
> +This instruction explains how to contribute to the [Spryker documentation](https://docs.spryker.com/) by creating pull requests on GitHub.
```suggestion
This instruction explains how to contribute to the [Spryker documentation](https://docs.spryker.com/) by creating [pull requests](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests) on GitHub.
```

2022-02-01 12:19 UTC, lenadoc commented on docs/scos/user/intro-to-spryker/contributing-to-documentation/contributing-to-spryker-documentation.md
> +6. Click **Propose changes**. This takes you to the **Comparing changes** page.
```suggestion
6. Click **Propose changes**. 
   This takes you to the **Comparing changes** page.
```

2022-02-01 12:19 UTC, lenadoc commented on docs/scos/user/intro-to-spryker/contributing-to-documentation/contributing-to-spryker-documentation.md
> +9. (Optional) To rename your pull request, delete the autopopulated title and enter a new one.
https://developers.google.com/style/procedures?hl=en#optional-steps

```suggestion
9. Optional: To rename your pull request, delete the autopopulated title and enter a new one.
```

2022-02-01 12:19 UTC, lenadoc commented on docs/scos/user/intro-to-spryker/contributing-to-documentation/contributing-to-spryker-documentation.md
> +10. (Optional) On the **Write** tab, in the **## PR Description** section, add an extended description of your pull request.
```suggestion
10. Optional: On the **Write** tab, in the **## PR Description** section, add an extended description of your pull request.
```

2022-02-01 12:19 UTC, lenadoc commented on docs/scos/user/intro-to-spryker/contributing-to-documentation/contributing-to-spryker-documentation.md
> +Congratulations! Your pull request has been created. Now, it can be picked up by the technical writing team for review and merge.
```suggestion
Congratulations! Your pull request has been created. Now, it will be picked up by the Spryker docs team for review and merge.
```

2022-02-01 12:21 UTC, lenadoc commented
@VadymSachenko Please also create the instructions on how to report issues via GitHub

2022-02-03 10:44 UTC, VadymSachenko reviewed
changes applied

2022-02-03 11:58 UTC, lenadoc commented on docs/scos/user/intro-to-spryker/contributing-to-documentation/contributing-to-spryker-documentation.md
> +If you want to create an issue on GitHub, see [Creating an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue) in the official GitHub documentation.
```suggestion
You can report an issue with the Spryker documentation via GitHub. For details on how to do that, see [Creating an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue) in the official GitHub documentation.
```

2022-02-03 11:59 UTC, lenadoc approved these changes

2022-02-03 12:21 UTC, lenadoc approved these changes

2022-02-03 13:34 UTC, merged