Managing custom prices for big amount of products
spryker/spryker-docs pull request #735
Opened 2022-02-03 09:17 UTC by lenadoc

## PR Description

TBD

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2022-02-08 08:44 UTC, jeremyfourna requested changes

2022-02-08 08:44 UTC, jeremyfourna commented on _data/sidebars/scos_dev_sidebar.yml
> +          - title: 'HowTo: Manage merchant custom prices for products via data import'
We should not label it as Merchant custom prices but more "HowTo: Manage business unit specific prices via data import"

2022-02-08 08:44 UTC, jeremyfourna commented on docs/scos/dev/tutorials-and-howtos/howtos/feature-howtos/data-imports/how-to-manage-merchant-custom-prices-for-products-via-data-import.md
> +title: 'HowTo: Manage merchant custom prices for products via data import'
Same comment as the file above ☝️

2022-02-08 08:44 UTC, jeremyfourna commented on docs/scos/dev/tutorials-and-howtos/howtos/feature-howtos/data-imports/how-to-manage-merchant-custom-prices-for-products-via-data-import.md
> +You can apply the approaches described in this article only if your project follows the B2B model, as the [merchant custom prices](https://docs.spryker.com/docs/scos/user/features/{{site.version}}/me
About

> Also, keep in mind that these approaches don't work for the Marketplace product offers.

We should also add a `warningBox` to say that it is not compatible with Marketplace at the moment

2022-02-08 08:44 UTC, jeremyfourna commented on docs/scos/dev/tutorials-and-howtos/howtos/feature-howtos/data-imports/how-to-manage-merchant-custom-prices-for-products-via-data-import.md
> +Let's assume you have a [default price](https://docs.spryker.com/docs/scos/user/features/202108.0/scheduled-prices-feature-overview.html#price-types) for products, and you have merchants for whom you
Should we not put `{{site.version}}` for the `../202108.0/..` in the URL? If yes, this must be corrected in all URL below

2022-02-08 08:44 UTC, jeremyfourna commented on docs/scos/dev/tutorials-and-howtos/howtos/feature-howtos/data-imports/how-to-manage-merchant-custom-prices-for-products-via-data-import.md
> +- Create a custom script that would automatically adjust merchant-specific prices upon the default price change.
As a side note, we could build a relatively small script that will do that until we cover this problem properly in the Product.
We could have this script under "Spryker Utils" lol

2022-02-09 09:08 UTC, jeremyfourna commented on _data/sidebars/scos_dev_sidebar.yml
> +          - title: HowTo - Manage business unit-specific prices via data import
Do we have `-` between `business unit-specific prices` or we just need a space there?

2022-02-09 09:10 UTC, jeremyfourna approved these changes
I just left a small comment about a `- instead` of a space otherwise it is all good

2022-02-09 12:04 UTC, VadymSachenko approved these changes
Approved. 
Please consider the added comments

2022-02-09 12:04 UTC, VadymSachenko commented on docs/scos/dev/tutorials-and-howtos/howtos/feature-howtos/data-imports/how-to-manage-business-unit-specific-prices-via-data-import.md
> +This approach is optimal for big amount of data. However, its main drawback is in the fact that you need some development effort and that the script runs and processes data outside of the Spryker pla
```suggestion
This approach is optimal for big amount of data. However, its main drawback is that you need some development effort and that the script runs and processes data outside of the Spryker platform.
```

2022-02-11 10:32 UTC, merged