MP-3957: add offer and merchant product to shopping list
spryker/spryker-docs pull request #796
Opened 2022-02-22 11:17 UTC by ilantipov

## PR Description

Ticket: https://spryker.atlassian.net/browse/MP-3957

2022-04-11 17:08 UTC, asmarovydlo requested changes

2022-05-04 14:02 UTC, asmarovydlo requested changes

2022-05-06 13:10 UTC, asmarovydlo approved these changes
Thanks for the detailed verification steps, technically they look good 👍 
But please check the outcome, after TW will update them with proper grammar (for future reference).

2022-05-09 08:00 UTC, jeremyfourna requested changes
Please make sure next time to use Grammarly to check for mistakes and quick improvements.

2022-05-12 06:57 UTC, ilantipov commented on docs/marketplace/dev/feature-integration-guides/202200.0/marketplace-shopping-lists-feature-integration.md
> +composer require spryker-feature/marketplace-shopping-lists:"202204.0" --update-with-dependencies
Yes. The feature is named in plural https://release.spryker.com/features/view/131 Should I still change it to singular where you noticed?

2022-05-12 12:22 UTC, jeremyfourna submitted a review, later dismissed

2022-05-16 16:00 UTC, merged