mp-6072: shopping list api
spryker/spryker-docs pull request #797
Opened 2022-02-22 11:18 UTC by ilantipov

## PR Description

Ticket: https://spryker.atlassian.net/browse/MP-6072
## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2022-04-11 17:09 UTC, asmarovydlo requested changes

2022-04-11 17:09 UTC, asmarovydlo commented on docs/marketplace/dev/feature-integration-guides/202108.0/glue/marketplace-shopping-list-feature-integration.md
> +| TODO ADD CORRECT LINKS Merchant Portal - Marketplace Add Product Offer And Merchant Product To Shopping List feature integration| | [Merchant Portal - Marketplace Add Product Offer And Merchant Pro
Please add correct links

2022-04-28 16:14 UTC, ilantipov commented on docs/marketplace/dev/feature-integration-guides/202108.0/glue/marketplace-shopping-list-feature-integration.md
> +---
It is actually https://github.com/spryker/spryker-docs/pull/797/files

2022-05-04 08:55 UTC, asmarovydlo commented on docs/marketplace/dev/feature-integration-guides/202108.0/glue/marketplace-shopping-list-feature-integration.md
> +---
202200.0 != 202204.0

2022-05-04 11:38 UTC, asmarovydlo approved these changes

2022-05-04 13:44 UTC, VadymSachenko commented on _data/sidebars/marketplace_dev_sidebar.yml
> +              - title: "Glue API: Marketplace Shopping Lists feature integration"
this will be added after the release. Now we don't need to add this guide to the sidebar 
```suggestion

```

2022-05-06 08:09 UTC, VadymSachenko commented on docs/marketplace/dev/feature-integration-guides/202200.0/glue/marketplace-shopping-lists-feature-integration.md
> +1. Make sure that merchant and offer references are present by sending the `POST` request to https://glue.mysprykershop.com/shopping-lists/{shoppingListReference}/shopping-list-items`
```suggestion
1. Make sure that merchant and offer references are present by sending the `POST` request to `https://glue.mysprykershop.com/shopping-lists/{shoppingListReference}/shopping-list-items`
```

2022-05-06 08:11 UTC, VadymSachenko commented on docs/marketplace/dev/feature-integration-guides/202200.0/glue/marketplace-shopping-lists-feature-integration.md
> +description: This document describes how to integrate the Shopping lists feature into a Spryker project.
```suggestion
description: This document describes how to integrate the Shopping Lists feature API into a Spryker project.
```

2022-05-06 08:12 UTC, VadymSachenko commented on docs/marketplace/dev/feature-integration-guides/202200.0/glue/marketplace-shopping-lists-feature-integration.md
> +This document describes how to integrate the Marketplace Shopping Lists feature into a Spryker
```suggestion
This document describes how to integrate the Marketplace Shopping Lists feature API into a Spryker
```

2022-05-06 09:29 UTC, VadymSachenko commented on docs/marketplace/dev/feature-integration-guides/202200.0/glue/marketplace-shopping-lists-feature-integration.md
> +| Marketplace Shopping Lists | {{page.version}} | [Marketplace Shopping Lists feature integration](/docs/marketplace/dev/feature-integration-guides/{{page.version}}/merchant-portal-marketplace-shoppi
Fix the link. We do not have such a guide.

2022-05-11 10:56 UTC, VadymSachenko commented
This PR can be merged after this one https://github.com/spryker/spryker-docs/pull/796

2022-05-17 11:27 UTC, gibmirmilch approved these changes

2022-05-17 11:27 UTC, merged