Add Offer and Merchant Product to Shopping List (Marketplace Shopping List)
spryker/spryker-docs pull request #798
Opened 2022-02-22 12:30 UTC by gibmirmilch

## PR Description

https://spryker.atlassian.net/browse/MP-3957

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2022-05-16 08:13 UTC, AdvaBD submitted a review, later dismissed

2022-05-18 07:45 UTC, lenadoc requested changes

2022-05-18 07:45 UTC, lenadoc commented on docs/marketplace/user/features/202204.0/marketplace-shopping-list-feature-overview.md
> +| **Offer** Stock is 0 and never out of stock flag is FALSE.   | The shopping list item is marked as *not available*, there is no possibility to add it to cart, however the price and merchant informa
```suggestion
| **Offer** Stock is 0 and *never out of stock* flag is FALSE.   | The shopping list item is marked as *not available*, it is impossible to add it to cart, however the price and merchant information is displayed. |
```

2022-05-18 07:45 UTC, lenadoc commented on docs/marketplace/user/features/202204.0/marketplace-shopping-list-feature-overview.md
> +| Merchant Status is *Inactive*. The  **product** was added to the shopping list. | The shopping list item is marked as *not available*, there is no possibility to add it to cart, the *Sold by* hint
```suggestion
| Merchant Status is *Inactive*. The  **product** was added to the shopping list. | The shopping list item is marked as *not available*, it is impossible to add it to cart, the *Sold by* hint is not displayed, however the customer can still see the price. If the merchant is active again, the shopping list item gets the *Sold by* hint back with the actual merchant information. |
```

2022-05-18 07:45 UTC, lenadoc commented on docs/marketplace/user/features/202204.0/marketplace-shopping-list-feature-overview.md
> +| Merchant Status is *Inactive*. The **offer** was added to the shopping list. | The shopping list item is marked as *not available*, there is no possibility to add it to cart, the *Sold by* hint is
```suggestion
| Merchant Status is *Inactive*. The **offer** was added to the shopping list. | The shopping list item is marked as *not available*, it is impossible to add it to cart, the *Sold by* hint is not displayed, however the customer can still see the price. If the merchant is active again, the shopping list item gets the *Sold by* hint back with the actual merchant information. |
```

2022-05-18 07:45 UTC, lenadoc commented on docs/marketplace/user/features/202204.0/marketplace-shopping-list-feature-overview.md
> +| The **Offer** is **not** approved.                           | The shopping list item is marked as *not available*, there is no possibility to add it to cart, the *Sold by* hint is not displayed, h
```suggestion
| The **Offer** is **not** approved.                           | The shopping list item is marked as *not available*, it is impossible to add it to cart, the *Sold by* hint is not displayed, however the customer can still see the price. |
```

2022-05-18 07:45 UTC, lenadoc commented on docs/marketplace/user/features/202204.0/marketplace-shopping-list-feature-overview.md
> +| The **Product** status is *Deactivated*.                     | The shopping list item is marked as *not available*, there is no possibility to add it to cart, the *Sold by* hint and the price are n
```suggestion
| The **Product** status is *Deactivated*.                     | The shopping list item is marked as *not available*, it is impossible to add it to cart, the *Sold by* hint and the price are not displayed, |
```

2022-05-18 07:45 UTC, lenadoc commented on docs/marketplace/user/features/202204.0/marketplace-shopping-list-feature-overview.md
> +| The **Offer** Status is *Inactive*.                          | The shopping list item is marked as *not available*, there is no possibility to add it to cart, the *Sold by* hint is not displayed, t
```suggestion
| The **Offer** Status is *Inactive*.                          | The shopping list item is marked as *not available*, it is impossible to add it to cart, the *Sold by* hint is not displayed, the price (taken from the concrete product) is displayed. |
```

2022-05-18 07:45 UTC, lenadoc commented on docs/marketplace/user/features/202204.0/marketplace-shopping-list-feature-overview.md
> +| **Product** is not in the current store.                     | The shopping list item is marked as *not available*, there is no possibility to add it to cart, the *Sold by* hint is not displayed, h
```suggestion
| **Product** is not in the current store.                     | The shopping list item is marked as *not available*, it is impossible to add it to cart, the *Sold by* hint is not displayed, however the customer can still see the price. |
```

2022-05-18 07:45 UTC, lenadoc commented on docs/marketplace/user/features/202204.0/marketplace-shopping-list-feature-overview.md
> +| **Offer** is not in the current store.                       | The *Sold by* hint is not displayed. The shopping list item is switched to the normal product without stock, so the shopping list item
```suggestion
| **Offer** is not in the current store.                       | The *Sold by* hint is not displayed. The shopping list item is switched to the normal product without stock, so the shopping list item is marked as *not available*, it is impossible to add it to cart, the price is displayed. |
```

2022-05-18 07:45 UTC, lenadoc commented on docs/marketplace/user/features/202204.0/marketplace-shopping-list-feature-overview.md
> +| **Product** validity date does not include the current date. | The shopping list item is marked as *not available*, there is no possibility to add it to cart, the *Sold by* hint and price are not d
```suggestion
| **Product** validity date does not include the current date. | The shopping list item is marked as *not available*, it is impossible to add it to cart, the *Sold by* hint and price are not displayed. |
```

2022-05-18 07:45 UTC, lenadoc commented on docs/marketplace/user/features/202204.0/marketplace-shopping-list-feature-overview.md
> +| **Offer** validity date does not include the current date.   | The *Sold by* hint is not displayed. The shopping list item is switched to the normal product without stock, so the shopping list item
```suggestion
| **Offer** validity date does not include the current date.   | The *Sold by* hint is not displayed. The shopping list item is switched to the normal product without stock, so the shopping list item is marked as *not available*, it is impossible to add it to cart, the price is displayed. |
```

2022-05-18 07:45 UTC, lenadoc commented on docs/marketplace/user/features/202204.0/marketplace-shopping-list-feature-overview.md
> +Regardless of whether the shopping list is shared with full or read access, the Merchant information is displayed to a user in the same way it is displayed to the shopping list owner.
```suggestion
Regardless of whether the shopping list is shared with full or read access, the merchant information is displayed to a user in the same way it is displayed to the shopping list owner.
```

2022-05-18 07:45 UTC, lenadoc commented on docs/marketplace/user/features/202204.0/marketplace-shopping-list-feature-overview.md
> +*Print Shopping List* feature does not contain any merchant-related information.
```suggestion
The *Print Shopping List* functionality does not contain any merchant-related information.
```

2022-05-18 09:44 UTC, lenadoc approved these changes

2022-05-18 10:08 UTC, merged