Ac 1334/adding new products to the docs
spryker/spryker-docs pull request #807
Opened 2022-03-03 16:34 UTC by andriitserkovnyi

## PR Description

TBD

## Checklist
- [x] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2022-03-03 18:05 UTC, lenadoc requested changes

2022-03-03 18:05 UTC, lenadoc commented on docs/scos/user/intro-to-spryker/contributing-to-documentation/adding-product-sections-to-the-documentation.md
> +5. In `_config.yml`, in the `algolia: indices:` section, add indexes for products per role. For example:
```suggestion
5. In [_config.yml](https://github.com/spryker/spryker-docs/blob/master/_config.yml), in the `algolia: indices:` section, add indexes for products per role. For example:
```

2022-03-03 18:05 UTC, lenadoc commented on docs/scos/user/intro-to-spryker/contributing-to-documentation/adding-product-sections-to-the-documentation.md
> +
```suggestion
```

2022-03-03 18:05 UTC, lenadoc commented on docs/scos/user/intro-to-spryker/contributing-to-documentation/adding-product-sections-to-the-documentation.md
> +
```suggestion
```

2022-03-03 18:05 UTC, lenadoc commented on docs/scos/user/intro-to-spryker/contributing-to-documentation/adding-product-sections-to-the-documentation.md
> +
```suggestion
```

2022-03-03 18:05 UTC, lenadoc commented on docs/scos/user/intro-to-spryker/contributing-to-documentation/adding-product-sections-to-the-documentation.md
> +
```suggestion
```

2022-03-03 18:05 UTC, lenadoc commented on docs/scos/user/intro-to-spryker/contributing-to-documentation/adding-product-sections-to-the-documentation.md
> +
```suggestion
```

2022-03-03 18:05 UTC, lenadoc commented on docs/scos/user/intro-to-spryker/contributing-to-documentation/adding-product-sections-to-the-documentation.md
> +
```suggestion
```

2022-03-03 18:05 UTC, lenadoc commented on docs/scos/user/intro-to-spryker/contributing-to-documentation/adding-product-sections-to-the-documentation.md
> +
```suggestion
```

2022-03-03 18:05 UTC, lenadoc commented on docs/scos/user/intro-to-spryker/contributing-to-documentation/adding-product-sections-to-the-documentation.md
> +
```suggestion
```

2022-03-03 18:05 UTC, lenadoc commented on docs/scos/user/intro-to-spryker/contributing-to-documentation/adding-product-sections-to-the-documentation.md
> +
```suggestion
```

2022-03-10 09:43 UTC, VadymSachenko approved these changes

2022-03-10 09:44 UTC, lenadoc approved these changes

2022-03-10 09:45 UTC, merged