MP-6052: MerchantProductOfferStorage refactoring TD : ProductOffer and Merchant context leakage.
spryker/spryker-docs pull request #810
Opened 2022-03-07 14:25 UTC by dmiseev

## PR Description

- Ticket for IG: https://spryker.atlassian.net/browse/MP-6052
- Epic: https://spryker.atlassian.net/browse/MP-5770 

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2022-03-07 15:50 UTC, DmitryLymarenko approved these changes

2022-03-10 17:20 UTC, AdvaBD approved these changes

2022-03-10 17:20 UTC, AdvaBD submitted a review, later dismissed

2022-03-15 10:06 UTC, VadymSachenko requested changes

2022-03-15 10:11 UTC, dmiseev commented on docs/marketplace/dev/feature-integration-guides/202200.0/marketplace-merchant-feature-integration.md
> +```php
src/Pyz/Zed/Queue/QueueDependencyProvider.php

2022-03-15 10:11 UTC, dmiseev commented on docs/marketplace/dev/feature-integration-guides/202200.0/marketplace-merchant-feature-integration.md
> +```php
src/Pyz/Zed/Synchronization/SynchronizationDependencyProvider.php

2022-03-15 10:13 UTC, dmiseev commented on docs/marketplace/dev/feature-integration-guides/202200.0/marketplace-merchant-feature-integration.md
> +```php
src/Pyz/Client/MerchantSearch/MerchantSearchDependencyProvider.php

2022-03-15 10:48 UTC, VadymSachenko approved these changes

2022-03-15 13:09 UTC, VadymSachenko approved these changes

2022-03-22 16:36 UTC, merged