MP-3934: Product Approval Process + Merchant Context [migration guides].
spryker/spryker-docs pull request #816
Opened 2022-03-11 09:30 UTC by dmiseev

## PR Description

- Ticket for IG: https://spryker.atlassian.net/browse/MP-6049
- Epic: https://spryker.atlassian.net/browse/MP-3934

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2022-03-11 10:05 UTC, DmitryLymarenko approved these changes
don't we need to mention transfers generation?

2022-03-11 11:53 UTC, DmitryLymarenko approved these changes

2022-03-18 11:03 UTC, AdvaBD requested changes

2022-03-18 11:03 UTC, AdvaBD commented on docs/marketplace/dev/module-migration-guides/migration-guide-productmerchantportalgui.md
> +In this new version of the **ProductMerchantPortalGui** module, we have added support product approval feature. You can find more details about the changes on the [ProductMerchantPortalGui module](ht
You can find more details about the changes on the [ProductMerchantPortalGui release](https://github.com/spryker/product-merchant-portal-gui/releases) page.

2022-03-18 13:11 UTC, DmitryLymarenko approved these changes

2022-03-18 13:25 UTC, AdvaBD submitted a review, later dismissed

2022-03-21 13:44 UTC, VadymSachenko approved these changes

2022-03-21 13:44 UTC, merged