Update query-container.md
spryker/spryker-docs pull request #873
Opened 2022-04-20 11:07 UTC by helen-laktionova

Add an info block with soft deprecation

## PR Description

TBD

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2022-04-20 11:12 UTC, dereuromark approved these changes

2022-04-20 11:22 UTC, gerner-spryker approved these changes

2022-04-21 18:11 UTC, PhilinTv commented on docs/scos/dev/back-end-development/zed/persistence-layer/query-container/query-container.md
> +Query containers are soft deprecated.
```suggestion
Query containers MUST NOT be used to cross module boundaries, as it increases modules coupling. However, they can be used behind Repository and Entity managers as query aggregations.
```

2022-04-21 18:12 UTC, PhilinTv commented on docs/scos/dev/back-end-development/zed/persistence-layer/query-container/query-container.md
> +{% info_block infoBox "Soft deprecation" %}
```suggestion
{% info_block infoBox "When to use Query Containers" %}
```

2022-04-21 18:13 UTC, PhilinTv commented on docs/scos/dev/back-end-development/zed/persistence-layer/query-container/query-container.md
> +It is recommended to use [Repository](/docs/scos/dev/back-end-development/zed/persistence-layer/repository.html) and [Entity Manager](/docs/scos/dev/back-end-development/zed/persistence-layer/entity-
```suggestion
```

2022-04-21 18:16 UTC, PhilinTv commented on docs/scos/dev/back-end-development/zed/persistence-layer/query-container/query-container.md
> +
```suggestion
Previously Query Containers were used to cross-module borders (via Dependency Providers), which led to higher module coupling and leaking of persistence layer from one domain object to another and therefore higher maintenance efforts and lower code reusability. This usage has been deprecated and is not recommended in project development.
```

2022-04-21 18:16 UTC, PhilinTv requested changes
--

2022-04-22 08:00 UTC, merged