MP-6215 Overriding CSS variables
spryker/spryker-docs pull request #969
Opened 2022-05-30 14:35 UTC by danilmoro3

Ticket: https://spryker.atlassian.net/browse/MP-6215

2022-05-31 10:45 UTC, FRITS-Kh requested changes

2022-05-31 10:45 UTC, FRITS-Kh commented on docs/marketplace/dev/front-end/extending-the-project/index.md
> +Variables can be overridden in any `.less` file in your project related to place where it's used.
It can be overridden in a CSS file as well.

2022-05-31 10:45 UTC, FRITS-Kh commented on docs/marketplace/dev/front-end/extending-the-project/index.md
> +The file must have an `@import` of the root variables, that placed in the `ui-conponents` library. For example:
Why do we need an import?

2022-05-31 10:45 UTC, FRITS-Kh commented on docs/marketplace/dev/front-end/extending-the-project/index.md
> +}
Can't imagine value of the usage.

2022-06-01 12:13 UTC, FRITS-Kh commented on docs/marketplace/dev/front-end/extending-the-project/index.md
> +Variables can be overridden in any `.less`/`.css` file in your project related to place where it's used.
```suggestion
CSS variables can be overridden in any `.less`/`.css` file related to the Marketplace at the project level.
```

2022-06-01 12:22 UTC, FRITS-Kh commented on docs/marketplace/dev/front-end/extending-the-project/index.md
> +Special case, will be overridden only inside component:
```suggestion
Partial override will change a variable for a some scope (for example inside a component):
```

2022-06-01 12:24 UTC, FRITS-Kh commented on docs/marketplace/dev/front-end/extending-the-project/index.md
> +- Overridden variable on the project level
```suggestion
- Overridden variable at the project level
```

2022-06-01 12:36 UTC, FRITS-Kh submitted a review, later dismissed

2022-06-02 08:09 UTC, FRITS-Kh requested changes

2022-06-02 08:09 UTC, FRITS-Kh commented on docs/marketplace/dev/front-end/table-design/table-column-types/table-column-type-image.md
> +    alt?: string;
Please also adjust the table config above.

2022-06-02 08:14 UTC, FRITS-Kh submitted a review, later dismissed

2022-06-02 10:48 UTC, gibmirmilch approved these changes

2022-06-02 10:53 UTC, merged