[AC-1374] Create document structure for payment partners (unzer)
spryker/spryker-docs pull request #993
Opened 2022-06-09 09:30 UTC by VadymSachenko

## PR Description

Jira ticket: https://spryker.atlassian.net/browse/AC-1374

2022-06-20 13:30 UTC, andriitserkovnyi requested changes

2022-06-20 13:30 UTC, andriitserkovnyi commented on docs/pbc/all/payment/unzer/configuration-in-the-back-office/add-unzer-marketplace-credentials.md
> +---
When a section consists only of guides, start the name with a bare infinitive to indicate that. A good name for this section would be `Add Unzer credentials in the Back Office`.

2022-06-20 13:30 UTC, andriitserkovnyi commented on docs/pbc/all/payment/unzer/configuration-in-the-back-office/add-unzer-marketplace-credentials.md
> +3. On the **External Merchant Credentials** tab, click **Add Merchant Unzer Credentials**.
Do new fields appear or does a page open?

2022-06-20 13:30 UTC, andriitserkovnyi commented on docs/pbc/all/payment/unzer/configuration-in-the-back-office/add-unzer-marketplace-credentials.md
> +9. Click **Save**.
What happens?

2022-06-20 13:30 UTC, andriitserkovnyi commented on docs/pbc/all/payment/unzer/configuration-in-the-back-office/add-unzer-marketplace-credentials.md
> +The following table describes the attributes you select and enter when adding Unzer credentials:
The heading explains this, so you can remove this sentence

2022-06-20 13:30 UTC, andriitserkovnyi commented on docs/pbc/all/payment/unzer/configuration-in-the-back-office/add-unzer-marketplace-credentials.md
> +The following table describes the attributes you select and enter when adding Unzer credentials:
Apply the comments for the previous table to this one.

2022-06-20 13:30 UTC, andriitserkovnyi commented on docs/pbc/all/payment/unzer/configuration-in-the-back-office/add-unzer-standard-credentails.md
> +---
Apply the comments from the previous do to this one.

2022-06-20 13:30 UTC, andriitserkovnyi commented on docs/pbc/all/payment/unzer/domain-model-and-relationships/domain-model-and-relationships.md
> +title: Domain model & relationships
```suggestion
title: Domain model and relationships
```

2022-06-20 13:30 UTC, andriitserkovnyi commented on docs/pbc/all/payment/unzer/domain-model-and-relationships/domain-model-and-relationships.md
> +title: Domain model & relationships
https://developers.google.com/style/word-list?hl=en#letter-symbol

2022-06-20 13:30 UTC, andriitserkovnyi commented on docs/pbc/all/payment/unzer/domain-model-and-relationships/domain-model-and-relationships.md
> +title: Domain model & relationships
Specify what the model and relationships belong to. There are multiple domain models for different features and customers should be able to find them via search

2022-06-20 13:30 UTC, andriitserkovnyi commented on docs/pbc/all/payment/unzer/domain-model-and-relationships/domain-model-and-relationships.md
> +# Domain model for Unzer payments
remove

2022-06-20 13:30 UTC, andriitserkovnyi commented on docs/pbc/all/payment/unzer/extend-and-customize/frontend-for-a-credit-card.md
> +---
Don't need a separate doc just to give a link. Shall we move it to `unzer.md`?

2022-06-20 13:30 UTC, andriitserkovnyi commented on docs/pbc/all/payment/unzer/unzer.md
> +## Unzer USP
Blank section

2022-06-20 13:30 UTC, andriitserkovnyi commented on docs/pbc/all/payment/unzer/install-unzer/integrate-unzer.md
> +Before integrating Unzer into your project, make sure you have [installed and configured the Unzer module](/docs/pbc/all/payment/unzer/install-unzer/install-and-configure-unzer.html).
```suggestion
[Install and configure the Unzer](/docs/pbc/all/payment/unzer/install-unzer/install-and-configure-unzer.html).
```

2022-06-20 13:30 UTC, andriitserkovnyi commented on docs/pbc/all/payment/unzer/extend-and-customize/frontend-for-a-credit-card.md
> +---
You can create a next steps sections in that doc and include this link there as well.

2022-06-21 10:27 UTC, VadymSachenko commented on docs/pbc/all/payment/unzer/configuration-in-the-back-office/add-unzer-marketplace-credentials.md
> +   7. Select **STORE RELATION**.
changed to "7. Select **STORE RELATIONS**"

2022-06-22 08:11 UTC, andriitserkovnyi approved these changes

2022-06-22 08:12 UTC, merged